# -*- coding: utf-8 -*-
"""D8 聚合 · 步骤6a：簇定义（手写口径）。中文引号一律用「」，避免与 Python 定界符冲突。"""

TASKS = [
dict(id="ACSD-T00", short="唯一门禁入口与注册表自描述", wave="W0", tier="P0", domain="门禁",
 title="消灭双入口分叉与隐式继承：注册表逐单元自描述",
 objs=["eng/ci/run.py", "eng/ci/run_checks.py", "eng/ci/checks.json", "eng/ci/checks.schema.json",
       "eng/ci/validate_registry.py", "eng/ci/tests/test_deep_profiles.py",
       "eng/ci/tests/test_runner_selection.py", "docs/ci/CI_SPEC.md", "docs/ci/01_CHECKS.md",
       "docs/ci/03_GATES.md", "ACCEPTANCE_SPEC.md", ".github/"],
 basis="《门禁体系设计》(D7) §2.1–2.6 与 §2.6 五批事务表；「复核-门禁入口」W1（判定：确认，机制与「agent 入口可零执行报绿」两条主链全部成立；成稿规模数 345/93% 待订正）；标准 05 §2（判据须有判别力）、§3（fail-closed）、§5（注册表与实际可执行检查一致）；CONTROL_PACK_SPEC §5（文件域互斥）。",
 how=["建共享模块并实现 `index_steps(registry) -> [unit]`，输出解析后自描述的单元（每单元带全量字段、不含「待定」）",
      "把两入口（`run.py` / `run_checks.py`）改为调用同一 `index_steps` 与同一零有效执行守卫",
      "让 `--strict` 校验器新增「逐单元全字段必填」规则，但只判已存在的形态",
      "注册表字段扩表：schema + validator + 执行器三方同批改，并逐 step 回填 `waivable/heavy/requires_monitor/mutates_workspace/outputs/inputs/optional_inputs/prerequisite_tools/changed_paths/timeout_seconds/platform/profiles/command`，同批删除 `INHERIT_FIELDS` 路径",
      "把 `platform` 值域收敛为 `{any, linux, windows}`；投递渠道（`fatduck`）改挂档位属性并从 `platform` 值域摘除",
      "将 workflow 改指唯一执行器；删除 `eng/ci/run.py` 的裁决路径；其单测迁移到共享模块",
      "把 `01_CHECKS.md §2` 命令列切换为生成器产物；`ACCEPTANCE_SPEC.md` 两处「通过标准 = `run_checks.py --check … exit 0`」补限定为「由唯一执行器在同平台执行且 effective>0」",
      "把 R12 反转为 R12b；清理聚合项顶层 command"],
 seq=["D7 §2.6 表内 5 批为硬顺序：批 2 的 schema/validator/executor/数据回填四改必须同提交（任一先动即全红，D7 §3.4 白名单死结）；批 3 晚于批 2；批 4 晚于批 3；批 5 最后",
      "本任务是 W0 的根节点：ACSD-T01/T04/T05/T08/T10 的门名与字段登记都挂在其注册表扩表之后"],
 blocks=["与 ACSD-T07、ACSD-T10 共改 `eng/ci/checks.json`：注册表结构性改动必须同一提交，否则出现「改了校验器数据全红」或「改了数据校验器全红」的中间态落 main",
         "与 ACSD-T01 共用「有效执行数」定义：入口未唯一化前，普查门的「通过」无可信语义"],
 neg=["删掉任一 step 的 `platform` ⇒ 注册表校验判红（现状：一个红、一个继承、一个当 any）",
      "任一档的 `platforms` 为空，或其成员在该平台「有效执行数 = 0」 ⇒ `GATE-PROFILE-PLATFORM` 判红",
      "`platform: fatduck` 之类非平台值出现 ⇒ 判红（C-c）",
      "把 `CHK-ALGO-WIRING`（`platform: linux`、进 `windows-main`、`waivable: false`）原样留着 ⇒ 该门在两读数面不一致，须判红；改数据与改判据不同提交 ⇒ 提交门判红"],
 forbid=["不得以 waiver 盖住分叉红灯；不得保留第二入口「零有效执行仍报绿」的路径",
         "不得在批 2 之前单独回填数据或单独改校验器"],
 note="成稿给的规模数（345 step / 93%）被第②层判为待订正，本任务按其复算口径登记，不沿用原数。"),

dict(id="ACSD-T01", short="fail-closed 普查门改测真实对象", wave="W0", tier="P0", domain="门禁",
 title="全门禁 fail-closed 普查：把「测谁」与「通过」的充要条件钉死并入库读数",
 objs=["eng/ci/failclosed_survey.py", "eng/ci/monitor_evidence.py", "eng/contracts/resource_gate_v1.json",
       "eng/ci/checks.json", "eng/ci/run.py", "eng/ci/run_checks.py",
       "artifacts/evidence/release-05/FAILCLOSED_SURVEY.md", "docs/ci/01_CHECKS.md",
       "docs/ci/03_GATES.md", "docs/ci/CI_SPEC.md", "artifacts/ci/"],
 basis="「复核-门禁入口」W2（判定：确认，数据流、「通过」的充要条件、文档授权面、数值漂移四项全部独立复算成立）；标准 05 §2（恒真、不读真实对象的检查无证据资格）、§6（退出码、判据值、日志与证据落档可复核）。",
 how=["改写普查脚本：被数对象由注册表 `index_steps` 现算，禁止内置副本清单",
      "把「通过」定义为「逐单元 rc 与 effective>0 同时可核」，并把每档读数写成跟踪件（`artifacts/ci/<sha>/`）",
      "把 `resource_gate_v1.json` 的阈值与实测值改为指针引用同一读数件，删除文档侧数值副本",
      "文档面（`docs/ci/*`）只引用跟踪路径与读数键名，不重述数值",
      "补 `--self-test`：内置正例与负例夹具，夹具落临时目录不写仓库"],
 seq=["前置：ACSD-T00 批 2（字段自描述）与批 3（唯一执行器）"],
 blocks=["与 ACSD-T02 共用 `artifacts/ci/` 落位约定 ⇒ 同批定字段名，否则两侧读不同件"],
 neg=["把一个档的成员全部置为 `prerequisite` 不可满足 ⇒ 普查必须判红而非判绿（现状：零有效执行仍报绿）",
      "删除跟踪读数件或置为零字节 ⇒ 判红",
      "文档数值与读数件不一致 ⇒ 判红"],
 forbid=["不得以「本机不可达」为由把红降级为 SKIP（标准 05 §6：不把 SKIP 计入通过）"],
 note="本任务不判科学阈值对错（D7 §0.3 显式不覆盖）。"),

dict(id="ACSD-T02", short="门读数与科学证据入库", wave="W0", tier="P1", domain="门禁+文档",
 title="两条入库门规：门的汇总读数与科学文档证据路径必须命中跟踪件",
 objs=["artifacts/ci/", "artifacts/evidence/", "docs/science/PHOTOMETRY.md", "docs/science/STAR_DETECTION.md",
       "docs/algorithms/GATES_AND_TOLERANCES.md", "docs/science/PHASE2_UPM.md",
       "docs/algorithms/PHASE2_SAMPLER.md", "实验/additive-sky-seamless/README.md",
       "实验/absolute-snr/README.md", "lib/algorithms/psf/tests/p1psf/p1psf_centroid_gate.cpp",
       "lib/algorithms/psf/tests/p1psf/CMakeLists.txt",
       "lib/algorithms/photometry/cpp/test/gate4_dr3sp_gaiaxpy/evidence/gate2_result.json",
       "artifacts/evidence/audit-2026-01/FIX_LEDGER.csv", ".gitignore"],
 basis="《链路间口径对表》§8 合案建议①②（四链同族的「证据落档缺失」同一根因）；「复核-AUD201」V6（判定：降级 — 读数、跟踪性、台账措辞复现，但「该读数属一条科学门」定性不成立 ⇒ 现状既不能判红也不能判绿）；《天光无缝核验报告》DEV-03（`.gitignore:17` = `run/*`，跟踪面 `git ls-files` 计数 0）；标准 05 §2。",
 how=["新增门规 A：在册门的汇总读数 JSON（数百字节级）登记进 `artifacts/ci/<sha>/` 或 `实验/*/results/`，文档只引用跟踪路径",
      "新增门规 B：`docs/science/**`、`docs/algorithms/**`、`docs/plugins/**` 中形如 `run/…`、`evidence/…` 的证据指针必须命中跟踪件，否则判红",
      "把 `PHASE2_SAMPLER.md:292,:297` 两处「实测」字样改指到入库读数件，或如实标「不可复核」",
      "质心门 p95 超容差那条改标「该读数不属科学门，既不能判红也不能判绿」，并按 `docs/science/STAR_DETECTION.md:15`/`:135` 与门表 `GATES_AND_TOLERANCES.md:52`、`:77` 的锚订正",
      "台账 `artifacts/evidence/audit-2026-01/FIX_LEDGER.csv` 与 `lib/photometric_calib/**` 全量悬空证据路径改指或删除",
      "把 `orchestrator/memory.md`、`pipeline/orchestrator/cpp/include/star_coord_contract.h` 等过程件按标准 04 §4 移出生产目录"],
 seq=["前置：ACSD-T01 的读数件字段名；与 ACSD-T06 同族，本任务的指针门复用其解析器"],
 blocks=["与 ACSD-T06 必须同批或 T06 先：两者都判「指针可解析」，两侧解析器不同即口径分裂",
         "与 ACSD-T09 共改 `FIX_LEDGER.csv` 与 `docs/KNOWN_LIMITATIONS.md`"],
 neg=["在任一科学文档写 `run/NOTHING/evidence/x.json` 作为证据指针 ⇒ 判红",
      "删除某在册门的汇总读数件 ⇒ 判红",
      "以零字节文件充当证据 ⇒ 判红"],
 forbid=["不得用 waiver 让「证据缺失」继续判绿；不得把不可复核的数字写成实测值"],
 note="同时消化《链路间口径对表》措辞 W6：`78%` vs `72.6%`、`0.459 dex`/`0.0107 mag` 一类只有历史或包内读数、无跟踪副本的数字，引用时改标「不可复核/口径未记」，并只写有跟踪副本的那一个。"),

dict(id="ACSD-T03", short="假绿与恒真判据族", wave="W0", tier="P0", domain="门禁+科学",
 title="零离散度假绿通道、对插值算子恒 0 的重建误差判据、求和型守恒门的错分盲区",
 objs=["docs/science/PHOTOMETRY.md", "eng/ci/fixtures/provenance/", "eng/contracts/schemas/",
       "lib/infrastructure/pipeline/orchestrator/memory.md",
       "lib/algorithms/integration/v6/src/weight_chain.cpp",
       "lib/algorithms/noise_snr/cpp/src/snr_science.cpp",
       "docs/plugins/algorithms_phase1/13_integration.md", "docs/plugins/algorithms_phase2/13_integration.md",
       "lib/algorithms/drizzle/healpix_drizzle/tests/reference_overlap.cpp",
       "docs/algorithms/DRIZZLE_GEOMETRY.md", "实验/shared/synthetic/noise_model.py",
       "lib/algorithms/drizzle/healpix_drizzle/v6_spherical_overlap.h"],
 basis="「复核-AUD201」V5（判定：确认，独立构造可达、判据实读放行）；「复核-AUD202-补」V5②③（判定：确认，18 组换源自测逐位 0，唯一能红面已被上游 `:479-486` 门接管 ⇒ 可达输入集上恒 0）；「复核-AUD204」W1（判定：确认 — 面积闭合是代数恒等，「1e-15 闭合」无证据资格）；《链路间口径对表》§8 形态一与合案建议④；标准 05 §2；AGENTS.md §5（判据必须非退化）。",
 how=["给 `sigma_residual` 类只卡上界与有限性的判据补退化侧守卫：零离散度 ⇒ 判红或显式具名「不可估计」",
      "把 `node_reproduction_max_abs` 改为「n=0 即红」守卫 + 换源必红断言（第②层给出的补项）",
      "求和型守恒判据补「定位句 + 同堂错分负例」：构造总量不变、逐叶/逐源错分的夹具，判据必须判红",
      "撤销「构造闭合 ⇒ 面积口径正确」的证据资格：在 `DRIZZLE_GEOMETRY.md` 与各报告里写明该判据只判代数恒等",
      "把测光 `sigma_residual` 与天光 `civar`/`cvar` 的「不可估计/零散度」哨兵统一到同一具名退化点（复用 `upm.cpp:2954-2962` `p2_upm_control_variance()` 的 `return 1` 写法）"],
 seq=["与 ACSD-T24（X5 哨兵表示）互为依据：哨兵形态与本族的退化侧守卫须同批定名"],
 blocks=["与 ACSD-T04（未注册可执行件）必须同批：本任务写的错分负例要落在真正在册的门上，否则负例无判红主体"],
 neg=["注入「总量守恒、逐叶错分」夹具 ⇒ 守恒判据必须判红（现状恒过）",
      "把插值算子的重建误差换成另一实现源 ⇒ `node_reproduction_max_abs` 必须非 0（现状逐位 0）",
      "把 `sigma_residual` 置为 0 ⇒ 判红而非判绿（现状放行）"],
 forbid=["不得以「再加一个上界」替代退化侧守卫；不得把恒真判据降格为「信息性输出」以规避红灯"],
 note="测光 V3 的「改锚分箱轴」路径已被第②层判为无效整改路径，本任务不采纳；分箱轴对色项缺陷趋零属「度量与缺陷不同源」，改走 T31。"),

dict(id="ACSD-T04", short="未注册可执行件入册", wave="W0", tier="P1", domain="门禁+测试",
 title="在仓但被明文不注册的可执行件与逐叶分配门定案",
 objs=["lib/algorithms/drizzle/healpix_drizzle/tests/CMakeLists.txt",
       "lib/algorithms/drizzle/healpix_drizzle/tests/drizzle_pf_sb_gate.cpp",
       "lib/infrastructure/aio/tests/", "eng/tests/", "eng/ci/checks.json", "docs/ci/01_CHECKS.md"],
 basis="「复核-AUD204」W4（判定：确认，并订正「逐 leaf 分配环节没有任何门」为「没有任何在册门；两件可执行件已在仓但被显式不注册」）；《链路间口径对表》§9 X7；标准 05 §5（孤儿检查器定案：注册、改造或删除）。",
 how=["逐件定案：能判红者按 `tests/CMakeLists.txt:255-268`、`:157-173` 注册进 ctest 并登记到 `eng/ci/checks.json`；不注册者删除并在退役注释块写明替代承载位（标准 04 §4）",
      "把 pixfrac parity 断言改为可触发形态（其现状按构造永不触发），并给同批注入的负例",
      "补逐叶几何门容差的唯一登记（`1e-6/1e-5/1e-7` 三处口径归一）"],
 seq=["前置：ACSD-T00 批 2 之后才能登记新门字段"],
 blocks=["先注册新门再改判据会自红 ⇒ 注册动作必须与判据改动同批（与 T21/T22 共改 `tests/CMakeLists.txt`）"],
 neg=["注入逐叶错分 ⇒ 新注册的门必须判红；若该门仍不在册 ⇒ 孤儿检查器门判红",
      "把 `drizzle_pf_sb_gate.cpp` 从不注册改为注册但不改 parity 断言 ⇒ parity 负例仍不触发 ⇒ 判红"],
 forbid=["不得为凑门数注册无判别力的件；不得以「探针能加载」充当科学判据"],
 note=""),

dict(id="ACSD-T05", short="默认值一致性与死键登记面", wave="W0", tier="P1", domain="门禁+配置",
 title="配置一致性门补数值比较，死键与键名对齐入同一条判据",
 objs=["eng/packaging/config/defaults.json", "eng/packaging/config/config_registry.json",
       "eng/ci/checks.json", "eng/ci/ledgers/dead_config_keys.json",
       "eng/ci/prod_wiring_baseline.json", "eng/tests/config/check_cfg002_registry.py",
       "eng/tests/config/test_cfg001_contracts.py", "eng/tests/cli/", "docs/contracts/CONFIG_CONTRACT.md"],
 basis="「复核-AUD201」V4（判定：确认 — 四条子 claim 全部独立复算成立，含死键 6/6；「造假 vs 漂移」这一层由第②层补做）；「复核-AUD202」V4（判定：确认 — `snr_path` 死键与三臂对象错配，结果件里 `snr` 出现 0 次、dense 两条生产者都不可达）；《链路间口径对表》§8 形态四「配置/登记键无消费者」；标准 05 §3（不静默取默认）。",
 how=["改一致性判据：从「只比键集合」升级为「逐键比数值 + 比键名对齐」，覆盖配置模板/出厂默认/登记册/合同/CLI 协议/生产入口各侧",
      "把 `defaults.json` 六条 `dead_config_key:photometry.*` 与 `snr_path`、`sparse_snr_spacing_px` 逐键定案：接线（补消费者）或删除（合同与登记面同批摘除）",
      "`prod_wiring_baseline.json` 与 `dead_config_keys.json` 的基线随数据同批回填",
      "对「配置缺键时的兜底取值」补值级断言：兜底值必须等于登记值，否则判红（消除 fail-open）",
      "在判据里点名「生产入口是否落在比较集合内」，杜绝只在模板 `blocks[]` 与 CLI 骨架等面外比较的历史形态"],
 seq=["无前置；与 ACSD-T25（X6 常数载体）、ACSD-T41（阶数六侧）共用同一批键与同一条判据"],
 blocks=["T05 / T25 / T41 三个簇共改 `defaults.json`、`dead_config_keys.json`、两个 cfg check ⇒ 必须同批或严格串行（同一提交）",
         "门与数据同批：把某键改成新值会触发一条锁旧值的门，二者不同提交即中间态全红"],
 neg=["把任一侧默认值改成与登记值不同 ⇒ 一致性门判红（现状：从不比较数值，判绿）",
      "新增一个无消费者的配置键 ⇒ 死键门判红",
      "删掉 `photometry.fit.spatial_gain_order` 的全部登记而装配层仍兜底取二阶 ⇒ 判红"],
 forbid=["不得以「文档已写明」替代数值比对；不得保留只判自合成夹具模式的判据充当值级门"],
 note=""),

dict(id="ACSD-T06", short="锚门与引用可解析面扩面", wave="W0", tier="P1", domain="门禁+文档",
 title="三道锚门的结构性盲区：把任意路径形态与 doc_globs 覆盖面纳入判据",
 objs=["docs/algorithms/anchors/check_doc_line_anchors.py", "docs/algorithms/anchors/anchor_contract.json",
       "docs/algorithms/anchors/unresolved_registry.json", "eng/ci/check_registration_anchors.py",
       "eng/ci/ledgers/registration_anchor_ledger.json", "eng/ci/check_no_weight_mode.py",
       "eng/tools/quality/check_path_domain_anchors.py", "docs/research/SNR_WEIGHT_RESEARCH_PACK.md",
       "reports/v6/contract-review/02_CONFLICT_AND_GAP_AUDIT.md"],
 basis="「复核-合同层」W2（判定：确认存在（引用悬空成立）＋定性降级为「锚号/出处失效」，不是「依据丢失」；并确认该引用面处在三道锚门的结构性盲区）；标准 05 §2、§5。",
 how=["把 `anchor_contract.json` 的 `doc_globs` 从只认 `docs/**` 扩到 `lib/**`、`实验/**`、`工程控制/**` 与根治理件（与索引门 C10 同一定义）",
      "`EXTERNAL_REFERENCE` 类条目改判「指向的锚号/出处是否存在」，不再用「依据丢失」定性",
      "`unresolved_registry.json` 回填实测未决项，注册即判红可见并计数",
      "把 `check_registration_anchors.py` 与 `check_path_domain_anchors.py` 合并到同一路径解析器，避免两侧口径",
      "为 `docs/research/SNR_WEIGHT_RESEARCH_PACK.md` 的外引指针补跟踪副本，或改标不可复核"],
 seq=["无前置；建议早于 ACSD-T02，令其指针门复用本任务产出的解析器"],
 blocks=["与 ACSD-T02 同族（同一解析器）⇒ 同批或 T06 先；`check_no_weight_mode.py` 与 T20/T28 的权臂口径互相触发 ⇒ 同批"],
 neg=["在 `lib/` 或 `工程控制/` 下写一条指向不存在行的 `路径:行` ⇒ 判红（现状：`doc_globs` 只含 `docs/` 而失明）",
      "把锚号改成不存在的节号 ⇒ C7/C8 判红",
      "清空扫描面 ⇒ 判红而非判绿（零对象守卫）"],
 forbid=["不得以「已注册为未决」当作免罪：未决条目必须计数可见"],
 note="`工程控制/RELEASE-02/GAP_AUDIT.md` 一类正文需从历史提交取回（`git show ae0f1e63^:工程控制/RELEASE-02/GAP_AUDIT.md`），属取证动作，不是整改对象。"),

dict(id="ACSD-T07", short="命名写法门与过程层出库同批", wave="W0", tier="P1", domain="门禁+文档",
 title="清包前必须先解门名与注释锚：写法门与 `工程控制/` 出库同批改",
 objs=["eng/ci/check_naming_surface.py", "eng/ci/ledgers/naming_surface.json",
       "eng/tools/doccheck/check_doc_hygiene.py", "eng/ci/checks.json", "工程控制/", "memory.md",
       "docs/audit/", "artifacts/evidence/"],
 basis="「复核-结果层与收口层」R1（判定：确认，方向 = 判红而不是失明；并补两条成稿未落的独立发现；来源为 DB-20 §0.2 反向咬合条 / 条目 I-14 / P1-5）；《迁移合并清单》W6 过程层出库；标准 04 §4（历史控制包、一次性过程脚本、过期台账不留在生产目录）；AGENTS.md §7（根目录条目须登记）。",
 how=["先解绑：把 `naming_surface.json` 中以门名/注释锚形式指向 `工程控制/**` 的条目改指到替代承载位（归档 `artifacts/evidence/`）或删除并登记",
      "同步订正 `check_doc_hygiene.py` 中硬编码的包外路径集合，避免清包后判据对象集为空而 fail-open",
      "以「先改门与登记面、后删目录」的顺序分两个原子提交，中间态不得落 main",
      "`memory.md` 处置：按《迁移合并清单》要求先点名「所有指向本文的跟踪引用清单与替代承载位」，再执行删除（该行现为 E5 待定案）",
      "为写法门补 `--self-test` 正负例（含「清空扫描面即红」守卫）"],
 seq=["前置：ACSD-T10 索引门 C1–C4 先落，否则出库后的对象集无判据可读",
      "《迁移合并清单》把出库排在 W6，本任务是它的门禁侧前置"],
 blocks=["门与数据同批（本仓已证死结形态）：若与 ACSD-T05/T06 跨同一 `eng/ci/checks.json`，必须同一提交",
         "整目录移除前必须先解开门名与注释锚 —— 引用规模见总览 §6 的固定命令读数"],
 neg=["仅删除 `工程控制/RELEASE-05/**` 而不改 `naming_surface.json` ⇒ 命名门必须判红（第②层已确认方向为判红），据此验证该门确有判别力",
      "把写法门扫描面清空 ⇒ 判红而非判绿"],
 forbid=["不得先删目录再补门（留下 fail-open 中间态落 main）；不得用 waiver 盖 R1 的红灯；不得删除 `testdata/`、用户数据或交付物（AGENTS.md §10）"],
 note="口径登记：本任务按「git -c core.quotePath=false grep -l -I 工程控制 -- . :!工程控制」计 128 个包外文件、命中行 263、命中处 285（`-c` 求和 = 263、`-o` 逐处 = 285）；`RELEASE-05` 单词形为 48 文件 / 208 处。派单口径给的「84 个包外文件、246 处引用」未被上述任一定义复现，已登记为待订正（见总览 §7）。"),

dict(id="ACSD-T08", short="退役模式扫描扩面", wave="W0", tier="P1", domain="门禁+文档",
 title="被禁 token 仍列生产模式：退役门扫描面扩到登记件与验证档案",
 objs=["eng/ci/check_psfsw_retired.py", "eng/contracts/data/v6_clause_registry_v1.json",
       "eng/contracts/schemas/unified/", "docs/validation/v6/", "docs/science/PSF_SIGNAL_WEIGHT.md",
       "eng/ci/checks.json", "lib/algorithms/coverage/tests/weight_mode_retire_negative_test.cpp",
       "docs/contracts/DATA_SEMANTICS.md", "docs/DOCUMENT_INDEX.yaml"],
 basis="「复核-DB13」W1（判定：确认）：被科学正本与两份现行合同判为「禁用 token、接受面 = 空」的 `psfsw_robust`，在验证档案层 6 件（在册 `ACTIVE_NORMATIVE`）与其机器源里仍列为生产模式；合同机器登记件自身三处相反（`weight_modes.production` 2 值 vs 同名 FROZEN 条款 3 值 vs `G-EPSF-PRESENT` 条件仍写「三生产模式」）；退役门扫描面只及 `eng/contracts/schemas/unified` ⇒ 拦不住；标准 04 §4。",
 how=["扩 `check_psfsw_retired.py` 扫描面到 `eng/contracts/data/**`、`docs/validation/v6/**` 与全部登记件",
      "把 `v6_clause_registry_v1.json` 三处取值改为同一值（或指向同一 value 源）",
      "把 `FZ-MODE-RETIRED` 正式入册 `eng/ci/checks.json`",
      "验证档案 6 件按「就地改成 2 模式」或「降级出正式文档层并扩退役门扫描面」二选一执行（第②层推荐后者，但三条取证路互斥，属负责人取向选择）"],
 seq=["判据扩面须晚于 ACSD-T00 批 2（否则新门字段不齐）"],
 blocks=["`PSF_SIGNAL_WEIGHT.md`、`DATA_SEMANTICS.md` 与 T21/T36 共改 ⇒ 同批或由同一簇领改；`docs/DOCUMENT_INDEX.yaml` 与 T10 同批"],
 neg=["在任一登记件把 `psfsw_robust` 写回 production 分类 ⇒ 退役门判红",
      "修好判据：跟踪集内 `psfsw_robust` 不再出现在任何 production 分类；登记件三处同值；`FZ-MODE-RETIRED` 入册"],
 forbid=["不得只改说明层不改机器登记件；不得以「档案已声明历史」免除扫描"],
 note="整改路线（就地订正 vs 降级出层）已进 UNRESOLVED（该复核件「必须负责人裁的」节），不阻塞判据扩面半边。"),

dict(id="ACSD-T09", short="状态档位词表与对外结论门", wave="W0", tier="P2", domain="文档+门禁",
 title="状态阶梯唯一词表回正本，对外发布结论补真值判据",
 objs=["eng/ci/check_version.py", "eng/ci/checks.json", "eng/ci/tests/test_ci001_failclosed.py",
       "eng/tools/quality/check_conclusion_truth.py", "docs/standards/DOCUMENTATION_STANDARD.md",
       "docs/owner/RELEASE_STATUS.md", "docs/KNOWN_LIMITATIONS.md",
       "artifacts/evidence/audit-2026-01/FIX_LEDGER.csv", "artifacts/evidence/audit-2026-01/OWNER_DECISIONS.md",
       "docs/modules/MODULE_MAP.yaml", "docs/research/COMPRESSION_CODEC_RESEARCH_PACK.md",
       "docs/owner/ARCHITECTURE_OVERVIEW.md", "docs/owner/PIPELINE_OVERVIEW.md"],
 basis="「复核-负责人面与索引」V1（判定：降级 —「加判据」与「发布结论越界」成立；「自造状态词百级传染」与「闭环」两处口径不成立，需按实测重写，实测 `files=153 occ=517`）、V4（判定：确认 — 缺陷成立、该判据的 PASS 资格现在不成立，但「四档并存」的定性要收窄）；《索引重建规格》§7（现 `status_legal` 校验的是自定四态分类，与 §12.5 状态阶梯混名）；AGENTS.md §6（不宣布发布）。",
 how=["把索引/登记面的自造状态词与 §12.5 状态阶梯解名：`status_legal` 改名，状态词表交回 §12.5 正本供给",
      "`check_conclusion_truth.py` 补「结论句必须指向跟踪读数件」的实读断言，越界发布结论判红",
      "`RELEASE_STATUS.md` 里三档并存的一条审稿结论（SCI-B / I2 fail-closed 对拍）按 `OWNER_DECISIONS.md` 定案并写唯一档",
      "按第②层实测重写规模口径：登记计数 + 命令，不写「百级传染」这类未复算措辞",
      "`FIX_LEDGER.csv` 只当线索（旧台账不作出证），其证据路径由 ACSD-T02 的入库门接管"],
 seq=["前置：ACSD-T10 C5/C6（role 与 canonical 判据）"],
 blocks=["`docs/owner/*` 与 W3 批量字句波共改 ⇒ 结构改动先于措辞收口"],
 neg=["把一条对外「已验收」结论接到无跟踪读数支撑的证据 ⇒ 判红",
      "在索引里写一个 §12.5 词表外的状态值 ⇒ 判红"],
 forbid=["不得由 agent 或本任务书宣布发布与版本号（AGENTS.md §6/§10）"],
 note=""),

dict(id="ACSD-T10", short="索引门判据 C1–C12 重建", wave="W0", tier="P0", domain="门禁+文档",
 title="文档索引判据重建：12 条检查各带零对象守卫与正负例，先于一切迁移",
 objs=["eng/tools/doccheck/check_doc_index.py", "docs/DOCUMENT_INDEX.yaml",
       "docs/audit/doc_classification.csv", "docs/TRACEABILITY.csv", "eng/tools/doccheck/dangling_ledger.json",
       "eng/ci/checks.json", "reports/v19r2/source_manifest.csv",
       "artifacts/evidence/doc-hygiene/baseline.json", "docs/API_REFERENCE.md"],
 basis="《索引重建规格》(D2) §6 判据清单 C1–C12、§7 与现有门的能力差、§8 事务顺序第 1–2 条；「复核-负责人面与索引」V3（判定：降级 —「争角色」不成立，唯一索引已把 `docs/audit/doc_classification.csv` 判为历史快照并声明权威在本索引）；标准 05 §2。",
 how=["按规格 §6 逐条实现 C1–C12，每条带零对象守卫、正例、负例，`--self-test` 夹具落临时目录不改仓库文件",
      "把登记对象集唯一锚定为 `git ls-files` 派生（含 `实验/`、`工程控制/`），排除面每条带 `reason ∈ {生成物, 证据快照, 第三方}` 且命中数与声明数一致",
      "`upstream` 校验补「号—标题双要素」（C7/C8），修掉现状 73 条「号错标题也错」仍能长绿的形态",
      "C10 扫描面按「任意路径形态」实现（含反引号内 `路径:行`、非 `docs/` 前缀如 `lib/`、`实验/`、`工程控制/`、根文件），替换现行只认 `docs/` 的 token 判据",
      "把 `docs/audit/doc_classification.csv` 按第②层结论定角色（历史快照、权威在本索引），不删文件、不改权威",
      "先落 C1–C4（对象集与口径），再落 C6 canonical，才允许启动《迁移合并清单》W1 起的任何迁移"],
 seq=["本任务是 ACSD-T07（过程层出库）与整个 W4 迁移波的前置（《索引重建规格》§8 第 1、2 条）",
      "C11 写法词表（日期形态、流水号形态、散列长度阈值）留给 D7《门禁清单》细化 ⇒ 缺件时登记为「待 D7 合入」，本任务只落「命中即红 + 给行号」"],
 blocks=["`docs/DOCUMENT_INDEX.yaml` 同时被 ACSD-T08/T09 与本任务改：同一文件的 role/status/登记面改动必须同批，否则互相覆盖",
         "`docs/TRACEABILITY.csv` 与 ACSD-T39 共改 ⇒ 同批"],
 neg=["删除一条登记 ⇒ C3 判红；把口径缩回只查 `docs/**` ⇒ C3 判红（口径判定见 C4）",
      "复制一份同主题文档并同样标 `canonical: true` ⇒ C6 判红；一条都不标 ⇒ C6 判红",
      "在任一文档写 `` `docs/不存在的页.md:12` `` ⇒ C10 判红",
      "把 `downstream: auto` 的快照 255 手工改成 3 ⇒ C12 判红并输出差值",
      "删除 §8.1 的「索引：」行 ⇒ C9 判红（现状 73/0 类断点即此形态）",
      "把 `实验/` 写进排除面而不带理由 ⇒ C4 判红"],
 forbid=["`DOC-INDEX` 门不可 waiver；红灯不得以「索引未跟踪」或「解析器缺失」降级为跳过 —— 这两种情形本身即 C1/C2 的红"],
 note="本任务只重建判据；实际迁移与登记动作在 W4 波，按《迁移合并清单》W0–W6 行级顺序执行。"),

# ------------------------------------------------------------------ W1
dict(id="ACSD-T20", short="X1 逐像素科学权重来源面", wave="W1", tier="P1", domain="科学",
 title="阶段二逐像素权重来源面定案：叠加权须含源项，实现侧新增含源项加权方差面",
 objs=["lib/infrastructure/scheduler/src/module_adapters.cpp", "docs/science/NOISE_MODEL.md",
       "ASTROCS_DESIGN.md", "docs/plugins/algorithms_phase1/07_noise_snr.md",
       "docs/science/CONTROL_WEIGHT_SNR.md", "docs/design/UNIFIED_MODEL.md",
       "lib/algorithms/noise_snr/cpp/src/snr_science.cpp", "eng/ci/check_no_weight_mode.py"],
 basis="《链路间口径对表》§9 真互斥 X1（科学方向已定：叠加权必须含源项，非两篇文档打架、不需裁决 ⇒ 待定案的只是「两侧各改什么」）；「复核-AUD202」V1（判定：确认，两臂定性不同须拆开定级；臂 B 只在 `ivar` 缺失时进入且显式声明 `uncertainty_available=false`/`weight_source=frame_snr` ⇒ 属已声明降级、非缺陷）；《SNR链路核验报告》R-1、DEV-01/DEV-02。",
 how=["实现侧：新增按含源项 σ 求值的逐像素加权方差面（`module_adapters.cpp:11936` 所在权臂）",
      "文档侧：给 `NOISE_MODEL.md:9`、`:328` 两句补适用域；把「降级路径且无逐像素权」与「权重链闭合」分开陈述，不得并列声称科学完备",
      "先跑 R-1 复测钉死现行生产走哪条臂：查 `p1_final.json#products` 是否含 `variance`/`ivar`、`p2_integrated.json` 的 `weight_basis`/`weight_source`/`uncertainty_unavailable_reason`，并按 `08_drizzle.md:70` 附 `n_variance_tiles>0` 的磁盘证据",
      "把 `07_noise_snr.md:138`（scheduler 未挂 variance 块 ⇒ 恒走帧级常量）与 `module_adapters.cpp:7880-8230`（variance 块已挂载且 fail-closed）两条互斥陈述由复测读数收敛为一条"],
 seq=["前置：ACSD-T01（复测读数需入库面）、ACSD-T05（同一批配置键的值级断言）"],
 blocks=["`module_adapters.cpp` 被 T20/T24/T29/T30/T31/T36/T41 七簇点到 ⇒ 同一文件的口径改动必须串行或合成一个提交（见总览 §5 冲突表）",
         "文档与实现同批：改权臂数据会触发一条锁旧口径的门（`check_no_weight_mode.py` 族），不同批改必红",
         "`NOISE_MODEL.md` 与 T32/T40 共改 ⇒ 同批"],
 neg=["把控制点权重的 σ 换成不含源项的背景 σ ⇒ 含源项断言必须判红",
      "在文档把「降级路径」与「权重链闭合」并列声称 ⇒ 口径门判红",
      "把稀疏层接上但控制点仍不按含源项 σ 求值 ⇒ 判红（第②层明示：接稀疏层不解决源项缺失）"],
 forbid=["不得为规避实现工作量而反向放宽文档（科学方向已定）；不得引 Zackay & Ofek 2017 支撑源受限域结论（其题名限定语 = 背景主导噪声极限）"],
 note=""),

dict(id="ACSD-T21", short="X2/X4 核权重分母与几何预算", wave="W1", tier="P1", domain="科学",
 title="面积口径两真互斥：核权重分母 `A_drop` vs `A_pixel`、冻结几何预算被违反 2–5 个数量级",
 objs=["lib/algorithms/drizzle/healpix_drizzle/drizzle_engine.cpp", "docs/contracts/DATA_SEMANTICS.md",
       "docs/algorithms/DRIZZLE_GEOMETRY.md", "ASTROCS_DESIGN.md", "docs/science/DRIZZLE.md",
       "lib/algorithms/drizzle/healpix_drizzle/spherical_overlap.cpp", "docs/KNOWN_LIMITATIONS.md",
       "docs/science/PSF_SIGNAL_WEIGHT.md", "docs/algorithms/DRIZZLE_ALGORITHMS.md"],
 basis="《链路间口径对表》§9 X2、X4 与措辞 W4；《面积交叠核验报告》DEV-04/DEV-05；「复核-AUD204」W1（确认）、W2（判定：降级 — 成稿两处口径混用、折线缝精度平台不可当作几何事实，但另有更大的真实预算违反）。",
 how=["定案核权重分母（`A_drop` 或 `A_pixel`），并在 `DATA_SEMANTICS.md:47`、`DRIZZLE_GEOMETRY.md:337-346`、`ASTROCS_DESIGN.md:209` 与 `drizzle_engine.cpp:1617` 四处写同名量与同一选择",
      "把 `k = pixfrac²` 改写为 `pf²·(1+⟨δ⟩)`，点名旧 `flux_conservation_factor = pf²` 已作废，「通量守恒」一律带量名",
      "面积口径改用真曲线边界（现成件 `subdivide_healpix_edge`，调用点从 `nb=4/samples=1` 接回）；或至少对极冠/face 角点邻域启用细分并保证共享边两侧采样一致",
      "同批登记代价：从极冠边偏差 `0.0809·hp_res` 起算逐层 ÷4，降到自身阈值 `1e-6·hp_res` 需 `d > log(8.09e4)/log(4) = 8.15` 层，而 `HP_ADAPTIVE_MAX_DEPTH = 8` ⇒ 极点邻边触底截断（残差 `1.234e-6·hp_res`，超阈 23%）、每边 256 段 = 1024 顶点/像素",
      "订正 `DRIZZLE_GEOMETRY.md:313` 的预算表述与 `:558-562` 的「对所有 NSIDE 统一使用自适应边细分」（注释与调用点相反）",
      "与 `docs/KNOWN_LIMITATIONS.md:139` 已登记但被低估（只说「与 1e-6 同阶」）的同一现象合并处理"],
 seq=["前置：ACSD-T03（守恒判据的错分负例）—— 否则改面积口径无门可验",
      "与 ACSD-T22 同批执行（同文件、同节、同容差面）"],
 blocks=["`DRIZZLE_GEOMETRY.md` 由 T03/T21/T22 三簇共改 ⇒ 必须同批；`docs/KNOWN_LIMITATIONS.md` 由 T02/T09/T21 共改 ⇒ 同批",
         "`DATA_SEMANTICS.md` 由 T08/T21/T28/T33/T36/T37/T38 共改 ⇒ 见冲突表，须由一个簇统一领改，其余簇以指针引用"],
 neg=["构造总量不变、逐叶错分的分配夹具 ⇒ 求和型守恒门必须判红（现状恒过）",
      "把 `subdivide_healpix_edge` 的调用点留在 `nb=4` ⇒ 逐叶面积误差 `-9.97%…+0.54%` 复现并判红（两路独立实现同值，99.55% 的边超阈）",
      "在文档写 `k = pixfrac²` ⇒ 作废因子门判红"],
 forbid=["不得以放宽冻结阈值（如该节既有「`hp_res·1e-12` 对非大圆弧边永不收敛、已废弃」式处理）代替精确边界；改默认容差须走变更流程（AGENTS.md §6）"],
 note="常量面亮度场的 `S_p` 因分子分母同错而不受影响：受影响面为 `support/coverage`、亚叶通量再分配、跨帧叠加的几何一致性 —— 判据须落在这三面上。"),

dict(id="ACSD-T22", short="X3 support 同表示", wave="W1", tier="P1", domain="科学+门禁",
 title="support 分子分母同表示与逐叶分配的在册容差登记",
 objs=["lib/algorithms/drizzle/healpix_drizzle/astro_sphere_sink.cpp",
       "lib/algorithms/drizzle/healpix_drizzle/tests/CMakeLists.txt",
       "docs/algorithms/DRIZZLE_GEOMETRY.md", "eng/ci/checks.json"],
 basis="《链路间口径对表》§9 X3（support 的分子分母同表示问题：弦面积 ÷ 真叶面积）、X7（逐叶分配是否有在册门 + 逐叶几何门的容差登记缺失，`1e-6/1e-5/1e-7` 三处口径）；标准 05 §5。",
 how=["把 `astro_sphere_sink.cpp:330-332`、`:520-521` 的 support 分子分母统一到同一表示",
      "在 `DRIZZLE_GEOMETRY.md §9` 登记逐叶几何门的容差唯一值，消掉三处口径",
      "与 ACSD-T04 的注册动作同批提交（门名与判据同批，防自红）"],
 seq=["前置：ACSD-T03；与 ACSD-T21 同批"],
 blocks=["T21/T22/T04 共改 `DRIZZLE_GEOMETRY.md` 与 `tests/CMakeLists.txt` ⇒ 三者同批或由 T21 统一领改"],
 neg=["构造「分子弦面积、分母真叶面积」的错配注入 ⇒ support 判据判红",
      "把逐叶容差写成第二个值 ⇒ 容差登记一致性门判红"],
 forbid=["不得只改一处容差而留下另两处"],
 note=""),

dict(id="ACSD-T24", short="X5 不可估计哨兵与退化侧守卫族", wave="W1", tier="P1", domain="科学+代码",
 title="把「零散度/不可估计」从伪装有限值改回具名退化，并抬到帧级门与产品声明面",
 objs=["lib/algorithms/coverage/src/sampler.cpp", "lib/algorithms/coverage/src/sky_plane.cpp",
       "lib/algorithms/star_detection/cpp/src/star_matcher.cpp",
       "lib/infrastructure/scheduler/src/module_adapters.cpp", "lib/algorithms/coverage/src/upm.cpp",
       "docs/science/PHASE2_UPM.md", "docs/algorithms/PHASE2_SAMPLER.md",
       "lib/algorithms/noise_snr/cpp/src/snr_estimator.cpp",
       "lib/infrastructure/pipeline/orchestrator/src/orchestrator.cpp", "docs/science/NOISE_MODEL.md"],
 basis="《链路间口径对表》§9 X5（测光与 UPM 同族）；「复核-AUD203」V1（判定：确认，定级 P1）：采样侧 1e-12 数值保护量把「零方差」伪装成 7.609e-27 的有限方差、逆方差 1.314e26，绕过下游 rc=2 的 fail-closed 门并独取该 cell 权重；《天光无缝核验报告》DEV-01 与反证行（同模块正确写法 `upm.cpp:2954-2962`，整改可直接复用该具名函数）；《测光链路核验报告》DEV-08（`snr_estimator.cpp:148,:322,:596` 返回码 2 把整幅 SNR 填 1.0；`orchestrator.cpp:4493-4494` 记日志后跳过 `snr_model` 块并 `return true`）。",
 how=["删除 `sampler.cpp:863-877` 与 `sky_plane.cpp:296`、`:306-307` 同款第二处的 1e-12 钳位，改为显式不可估计具名退化（方差非有限、逆方差 0）",
      "复用 `p2_upm_control_variance()` 的 `return 1` 写法作为唯一退化点，禁止再造第二套口径",
      "把已有的 rc/哨兵抬到帧级门与产品声明面：`sigma_residual ≤ 0` 时测光帧不得静默判绿，产品面须声明「此帧散度不可信」",
      "撤销 `snr=1.0` 作为缺省填充值（与 ACSD-T28 术语面同批），改 NaN 或合同侧显式允许",
      "同步订正 `docs/science/PHASE2_UPM.md`、`docs/algorithms/PHASE2_SAMPLER.md` 中把 1e-12 当物理量的表述"],
 seq=["前置/同批：ACSD-T03 的退化侧守卫定义（同一族，须同批定名）"],
 blocks=["`module_adapters.cpp` 同文件簇（与 T20/T29/T30/T31/T36/T41）⇒ 同批或串行",
         "`PHASE2_UPM.md` 与 T02/T29/T35 共改 ⇒ 同批",
         "与 ACSD-T28 必须同批：哨兵语义与术语面一处改、一处留即自相矛盾"],
 neg=["常数天光块（零方差）⇒ `control_ivar == 0` 且 `control_variance` 非有限（第②层给出的修好判据）；若仍得 1.314e26 ⇒ 判红",
      "注入 `sigma_residual = 0` ⇒ 帧级门判红（现状：记日志后跳过并 `return true`）",
      "删除 `1e-12` 而不同时补显式退化 ⇒ 负例夹具判红"],
 forbid=["不得以「数值保护」为名保留伪装有限方差；不得改冻结容差而不走变更流程"],
 note="跨链传导风险由测光报告 DEV-08 登记：一个看起来合法的假 SNR 会流入下游，故帧级声明与产品面声明都是必要落点。"),

dict(id="ACSD-T25", short="X6 常数出处的活载体", wave="W1", tier="P1", domain="科学+配置",
 title="常数出处登记为配置键的六条死键与 CFG001/CFG002 判据退化",
 objs=["eng/packaging/config/defaults.json", "docs/science/PHOTOMETRY.md",
       "eng/tests/config/check_cfg002_registry.py", "eng/tests/config/test_cfg001_contracts.py",
       "eng/ci/prod_wiring_baseline.json", "eng/ci/ledgers/dead_config_keys.json",
       "docs/algorithms/GATES_AND_TOLERANCES.md"],
 basis="《链路间口径对表》§9 X6（含 `tukey_c` 的「登记即错」例外与 CFG001/CFG002 判据退化）；「复核-AUD201」V4（判定：确认 — 四条子 claim 全部独立复算成立：`PHOTOMETRY.md:218` 与 `:220` 权威回链行号大面积指错、`:220` 把「证据出处」写成配置键 `photometry.mag_tolerance`、死键 6/6 成立、`sourced` 状态字段本身没说谎）。",
 how=["逐键定案六条 `dead_config_key:photometry.*`：接线或删除；删除须同批摘除合同、登记册、文档三处引用",
      "把常数出处载体定为单一面（代码字面量 或 配置键，二选一），并在 `PHOTOMETRY.md:218`/`:220` 写清该面",
      "`tukey_c` 的「登记即错」例外按第②层口径写入判据例外表，不再当活键",
      "修 CFG001/CFG002 的判据退化：从「键名存在」升级为「值与文档回链同号同值」",
      "`PHOTOMETRY.md` 的权威回链行号逐条按实测订正"],
 seq=["同批：ACSD-T05（值级一致性门）—— 门与数据同批改，否则新数据触发锁旧值的门"],
 blocks=["T05/T25/T41 共改 `defaults.json`、`dead_config_keys.json`、两个 cfg check ⇒ 必须同一提交"],
 neg=["把某常数在文档里的回链改指到一个不存在的键 ⇒ CFG 判据判红（现状：判绿）",
      "在 `defaults.json` 写一个值、文档写另一个值 ⇒ 值级判据判红"],
 forbid=["不得以「配置里有这个键」充当科学证据出处"],
 note="第②层已就「造假 vs 漂移」下判断（成稿未做这一层），本任务按该结论登记处置面，不再上呈。"),

dict(id="ACSD-T27", short="排异档界七处与两条相反测试", wave="W1", tier="P1", domain="科学+测试",
 title="排异三档正本跟改 7 处对侧口径，并修一条与正本相反的测试断言",
 objs=["docs/plugins/algorithms_phase2/12_rejection.md", "docs/science/REJECTION.md",
       "docs/algorithms/PHASE2_REJECTION.md", "docs/contracts/PUBLIC_API.md",
       "docs/design/PHASE2_DETAILED_DESIGN.md", "docs/modules/phase2_rej.md",
       "docs/modules/registry/astrocs.phase2.reject.md", "eng/tests/unit/p2_rejection_test.cpp",
       "eng/tests/unit/p2002_unc_rej_prov_test.cpp", "lib/algorithms/coverage/src/rejection.cpp",
       "docs/traceability/TRACEABILITY_MATRIX.json", "docs/traceability/TRACEABILITY_MATRIX.csv",
       "ASTROCS_DESIGN.md"],
 basis="「复核-DB13」W3（判定：确认，范围与严重度上修：对侧 7 处而非成稿的 2 处，含现行合同 `PUBLIC_API.md:1376-1378`、两份模块页、`PHASE2_REJECTION.md:90` 同文件自我否定、`rejection.cpp:1129-1131` 注释与代码互否）；唯一正本 = `12_rejection.md` §9 三档（`ASTROCS_DESIGN.md:422` 点名并自证「本节不复制档界与取值」），现行代码走三档 ⇒ 口径不需裁决。",
 how=["按正本跟改 7 处对侧口径（文档 + 合同 + 模块页 + 注释）",
      "修 `p2002_unc_rej_prov_test.cpp:550-551` 的相反断言（系 M3 提交 `139a2bc4` 漏改），使其与 `p2_rejection_test.cpp:212-218` 对同一 profile 同一入口一致",
      "订正成稿给出的 `ASTROCS_DESIGN.md:420 → :422` 锚（`:420` 实为「路由依据 N = 该输出像素的几何可贡献帧数」）",
      "登记实跑前置（本只读阶段禁跑）：`python3 eng/tools/monitoring/mem_guard.py --max-rss-gb 4 -- ctest --test-dir build -R ^(p2002_unc_rej_prov|p2_rejection)$ --output-on-failure`"],
 seq=["无前置（口径六面单向，第②层已定案，不上呈）"],
 blocks=["`PUBLIC_API.md` 由 T27/T28/T36 共改 ⇒ 同批；`ASTROCS_DESIGN.md` 由 T00/T20/T21/T27 共改 ⇒ 见冲突表"],
 neg=["修好判据：`git grep` 对侧 0 命中；两条 ctest 同跑全绿（现状对同一入口断言相反，必有一条红）",
      "在任一文档写回两档口径 ⇒ 排异档界一致性门判红"],
 forbid=["不得把「两条测试相反」以 SKIP 消化；不得为让测试变绿而改档界取值"],
 note="第②层定级口径：实跑确认前 P1，确认为红则 P0 —— 本任务书按 P1 登记并挂复测项。"),

dict(id="ACSD-T28", short="snr=1.0 术语面归一", wave="W1", tier="P1", domain="科学+文档",
 title="术语表把合法测量值当缺失标记：一行改口径 + 改锚，可结案一条待裁",
 objs=["docs/GLOSSARY.md", "docs/science/CONTROL_WEIGHT_SNR.md", "docs/algorithms/PHASE2_SAMPLER.md",
       "docs/contracts/DATA_SEMANTICS.md", "docs/contracts/PUBLIC_API.md",
       "lib/algorithms/coverage/include/astro/phase2/upm.h", "lib/algorithms/coverage/tests/synthetic_gate.cpp",
       "eng/ci/check_no_weight_mode.py"],
 basis="「复核-DB13」W4（判定：确认，可结案不必上呈）：`docs/GLOSSARY.md:15` 的「snr=1.0 一律按 unknown 显式标注」与正本 §5/§6/§7、两份现行合同、算法文档、实现头 `upm.h:51-54`、测试 `synthetic_gate.cpp:3938` 六面逐字相反（把合法测量值当缺失标记 = 正本明列的不可接受变化）；其自证锚 `#42` 只定义符号别名，同行还把被否定的 `support×snr²` 通道当活定义。",
 how=["把 `docs/GLOSSARY.md:15` 一行改为与正本六面一致的表述（1.0 是合法测量值；不可估计另用具名哨兵）",
      "改自证锚 `#42` → `#153`，并把同行 `support×snr²` 的活定义改指现行通道",
      "与 ACSD-T24 的哨兵改法同批落地（同一语义、两处承载面）",
      "撤下负责人待裁清单中「snr=1.0 两篇相反」一项"],
 seq=["同批：ACSD-T24"],
 blocks=["`DATA_SEMANTICS.md`/`PUBLIC_API.md` 与 T27/T36/T38 共改 ⇒ 同批"],
 neg=["修好判据：全仓 `snr=1.0` 语义单向（`git grep` 无第二读法）；任一文档仍把 1.0 当 unknown ⇒ 术语一致性门判红"],
 forbid=["不得在改口径的同时改默认容差"],
 note="该条同时消解一条已登记待裁事项，交付后需在 UNRESOLVED 清单勾销。"),

dict(id="ACSD-T29", short="additive_mode 四处注释口径统一", wave="W1", tier="P2", domain="文档+注释",
 title="注释与代码默认打架：四处措辞统一到正本记法，不动码",
 objs=["lib/infrastructure/scheduler/src/module_adapters.cpp", "docs/modules/phase2_upm.md",
       "docs/science/PHASE2_UPM.md", "docs/plugins/algorithms_phase2/11_upm.md",
       "eng/packaging/config/config_registry.json"],
 basis="「复核-AUD203」V3（判定：确认，定级 P2；行为正确 ⇒ 纯注释/符号口径缺陷）：三处注释里 `:9820`（默认 c、δ 从不施加）与 `:10300`（c = 全减含 B_ref）为假、`:9834` 为真，另有成稿漏的第四处 `docs/modules/phase2_upm.md:75-76`；《天光无缝核验报告》DEV-04（`:9820` 自称的锚点 `:5503` 处实为 `mark_frame_fail` lambda ⇒ 锚点也已漂移；`upm.cpp:976-977` 把分量参考帧帧行恒置 0 ⇒ mode c 对参考帧是恒等变换；默认实为 delta）。",
 how=["按 `docs/modules/phase2_upm.md:70-72` 的强制消歧规则，把四处统一到正本 `C_f = 帧分量（仅偏差）`／`b_k = 全量`",
      "在 `docs/modules/phase2_upm.md:75-76` 写「实现面默认已为 delta」，删除「属待改」的错误断言",
      "订正 `:9820` 的失效锚 `:5503`",
      "`additive_mode` 键补登记（`config_registry.json:1855` 现记 finding=unregistered）"],
 seq=["无前置"],
 blocks=["`module_adapters.cpp` 同文件簇（见 T20 行）⇒ 同批或串行；`config_registry.json` 与 T05/T36 共改"],
 neg=["注入一条「`additive_mode = c` 即全减背景」的注释 ⇒ 与正本消歧规则比对判红",
      "注释锚 `:5503` 未订正即留 ⇒ ACSD-T06 的锚门判红"],
 forbid=["不得动码（第②层判定：行为面正确且可审计，默认 delta、缺产物时显式降级、manifest 全落）；不得以改注释顺带改默认值"],
 note="唯一真实风险是误用：把 `additive_mode=c` 当论文里的「全减背景退化臂」来跑，得到的其实是另一套仍保背景的、对齐到参考帧的加性扣除。"),

dict(id="ACSD-T30", short="tolerance_relative 与 session 通道下线", wave="W1", tier="P2", domain="配置+代码",
 title="生产侧合规、永不调度的 session 侧漏设回落 0：随 ARCH-DEBT-01 下线或统一冻结装配",
 objs=["lib/phase2_session/p2_session.cpp", "lib/infrastructure/cli/commands.cpp",
       "lib/infrastructure/scheduler/src/module_adapters.cpp", "docs/algorithms/PHASE2_UPM_IMPL.md",
       "docs/science/PHASE2_UPM.md", "eng/packaging/config/defaults.json"],
 basis="「复核-AUD203」V4（判定：确认，定级 P2）：生产侧 = 1（合规），永不调度的 session 侧漏设回落 0（违正本「禁绝对容差」）；影响的是收敛判定本身而非仅日志；不构成活的 fail-open，但存在「覆盖键在一条路上静默失效」的不对称；标准 04 §1（阶段会话能力归并后独立会话目录退役）。",
 how=["二选一：随 ARCH-DEBT-01 下线 `lib/phase2_session/**` 通道，或把两条装配路径的默认装配统一为同一冻结函数",
      "在 `defaults.json` 与合同侧显式登记「该键的绝对容差禁用」语义，禁止兜底 0",
      "若下线：按标准 04 §4 以统一注释块标注退役原因、替代实现与日期口径，或直接删除"],
 seq=["前置：ACSD-T43（阶段调度器接线与 LIB 会话归并，取决于负责人裁-2）—— 下线哪条通道取决于阶段调度器身份"],
 blocks=["与 T46 同批或标先后；`module_adapters.cpp` 同文件簇"],
 neg=["在不带该键的装配路径上跑一次收敛判定 ⇒ 必须显式降级并写明原因；静默取 0 ⇒ 判红"],
 forbid=["不得在「不动默认容差」的约束下私自把 0 改成别的值来让断言变绿"],
 note=""),

dict(id="ACSD-T31", short="测光 λ 因子前提显式化与刻度锚", wave="W1", tier="P2", domain="科学",
 title="λ 因子成立前提写成约束 + 绝对刻度锚改述为「仓库内无可复核锚」",
 objs=["lib/algorithms/photometry/cpp/src/spectrum_integrator.cpp",
       "lib/algorithms/photometry/cpp/test/gate4_dr3sp_gaiaxpy/xpsd_production_validation.py",
       "docs/science/PHOTOMETRY.md", "lib/algorithms/photometry/README.md",
       "docs/plugins/algorithms_phase1/06_photometry.md"],
 basis="《测光链路核验报告》DEV-01/DEV-02；「复核-AUD201」V1（判定：降级 —「存活」确认、「可达产品路径」推翻、「星等计两次」机理与 0.459 dex 判待证；生产路径调用者 = 0，`pc_api.cpp:385` 已注释「不再使用 uint8*10^(-0.4G) 猜测公式」）、V2（判定：推翻 — 推翻的是「25× 裕度」这条论证；λ 因子本身的正确性由别的路径成立，正本无需订正）、V3（判定：降级 — 「色项型缺陷在星等分箱下趋零」复现，但「判据无证据资格」结论过宽，且成稿给的整改路径无效）。",
 how=["在正本 §2a.2 把「`λ` 因子成立 ⟺ 解码后的 `F_λ` 为能量谱辐照度」写成正向约束（常数须有推导，不得只写结论）",
      "把 §2a.6/:50/:408 的「绝对刻度由本轮真实数据实证锚定」改述为「目前无仓库内可复核锚」，并删去对该锚的引用",
      "色项判据的落点改到容器解码谱上：跟踪 CSV 两臂同源、不经容器解码 ⇒ 对该缺陷恒绿，不可作整改落点",
      "删除 `spectrum_integrator.cpp:279` 虚报生产可达的注释（「被 pc_api.cpp OpenMP 并行循环调用」与 grep 实数矛盾），并按标准 04 §5 处理退役叙述",
      "处置该两函数的死代码面：不在任何公共头/导出面、调用者全在测试与工具树（含 CMake 里无目标的 `test_spectrum_integrator.cpp`），按标准 04 §4 删除或标退役",
      "不再引用 0.459 dex 作为独立测得值（其来源目录被 `.gitignore:17` 排除、跟踪面 0 文件）"],
 seq=["前置：ACSD-T02（读数入库面就绪才能补刻度锚证据）"],
 blocks=["`PHOTOMETRY.md` 由 T02/T03/T05/T25/T31 共改 ⇒ 同批；`filters.json` 与 T05 共改"],
 neg=["在能量/光子两支约定上注入反向选择 ⇒ 缺判据时不得判绿（现状：唯一判据缺位）",
      "把色项判据建在跟踪 CSV 上 ⇒ 去掉 `λ` 因子后仍判绿 ⇒ 该判据不得入册"],
 forbid=["不得因 V2 论证被推翻而改动 λ 因子本身（正本无需订正）；不得以「注释里有说明」替代可达性事实"],
 note="历史可达性：生产切换到 XPSD 解码发生在 `70edb842`（2026-08-08，「fluxMin/fluxMul 线性解码替代 uint8*10^-0.4G」）⇒ 该式曾是生产通道，早于该提交的产物才可能带偏差，HEAD 不带。"),

dict(id="ACSD-T32", short="SNR 三口径对拍与分子口径", wave="W1", tier="P1", domain="科学+实验",
 title="三口径图谱测的是 σ̂ 估计器而非 SNR：补一组以 F_ref 为分子的三臂对拍",
 objs=["docs/science/NOISE_MODEL.md", "docs/plugins/algorithms_phase1/07_noise_snr.md",
       "lib/algorithms/noise_snr/cpp/src/snr_science.cpp", "lib/algorithms/noise_snr/cpp/include/snr_estimator.h",
       "实验/absolute-snr/code/b3_domain_map.py", "实验/absolute-snr/results/b3_domain_map.json",
       "docs/science/CONTROL_WEIGHT_SNR.md", "ASTROCS_DESIGN.md", "docs/science/DRIZZLE.md"],
 basis="《SNR链路核验报告》§3 R-2 与其 DEV 表；《链路间口径对表》§9（同名不同物：帧级 `frame_snr` 分子是 `F_ref`，稀疏控制点侧被登记为同一对象的写入点分子是逐源 `F_i`；整改是「新增生产 + 改消费算子」）与措辞 W1/W3；「复核-AUD202」V1（两臂须拆开定级）。",
 how=["补一组以 `F_ref`（或 §2b 的 `S_src`）为分子的 SNR 场三臂对拍：`dense`（须先补生产者）/`sparse_reconstruct`/`frame_reconstruct` 同一输入逐像素比，报 `max|SNR_a/SNR_b − 1|`，含「真值无源 ⇒ 归零」负例",
      "若三臂不能同物理量且互差受控 ⇒ 撤销「三口径并存」的文档主张",
      "把 ADU ↔ 合成通量刻度的唯一换算式只写一次，`F_ref` 与 `k_photo` 各引一端（措辞 W1）",
      "订正 `07_noise_snr.md:201` 的「只存」列举不全（层级向下，措辞 W3）",
      "撤销等值门 `snr_phot == median(SNR_F)` 把帧级量钉在逐源中位数上的形态",
      "明确 `control_ivar`（稀疏控制点）与 `ivar`（稠密背景面）不得互换指称；「归一在消费侧」须点名在哪一层归一（措辞 W2）"],
 seq=["前置：ACSD-T01（对拍读数须入库）；与 ACSD-T33 同批（稀疏层对象是本任务的第三臂）"],
 blocks=["`NOISE_MODEL.md` 由 T20/T32/T40 共改 ⇒ 同批；`CONTROL_WEIGHT_SNR.md` 由 T28/T32/T33/T40 共改"],
 neg=["真值无源夹具 ⇒ 三臂 SNR 必须归零；若不归零 ⇒ 判红（判据非退化要求）",
      "以 σ̂ 估计器充当 SNR 场 ⇒ 口径门判红"],
 forbid=["不得用「已声明降级」替三臂缺生产者事实；不得引书目层证据支撑超出其限定语的结论"],
 note=""),

dict(id="ACSD-T33", short="稀疏层预测方差对象缺失", wave="W1", tier="P1", domain="科学+合同",
 title="合同要求的逐像素预测方差在 `SparseReconstruction` 里无字段，manifest 以它物顶替其名",
 objs=["eng/contracts/schemas/unified/sparse_snr_layer.schema.json", "docs/science/CONTROL_WEIGHT_SNR.md",
       "eng/ci/ledgers/dead_config_keys.json", "实验/absolute-snr/docs/snr-propagation-design.md",
       "docs/plugins/algorithms_phase2/13_integration.md", "lib/algorithms/integration/v6/src/weight_chain.cpp",
       "docs/contracts/DATA_SEMANTICS.md"],
 basis="「复核-AUD202」V2（判定：确认，定性从「写错对象」收窄为「生产根本没有该对象 + 消费侧按已作废的相对语义实现」）；「复核-AUD202-补」V5（判定：确认②③ — 合同要求的逐像素预测方差在 `SparseReconstruction` 里无字段，而 manifest 用 `node_reproduction_max_abs` 顶替「重建误差」之名）。",
 how=["在 `SparseReconstruction` 侧新增合同所要求的逐像素预测方差字段；或把合同条款改为指向实际存在的对象（二选一并登记）",
      "manifest 停止用 `node_reproduction_max_abs` 冒名「重建误差」；`sparse_snr_spacing_px`/`snr_path` 死键按 ACSD-T05 定案",
      "消费侧的已作废相对语义实现改为按正本绝对语义（与 `CONTROL_WEIGHT_SNR.md` 对齐）",
      "在文档里补 `predicted_variance_adu2` 的对象辨析：实验侧同名字段不是合同对象（第②层给的三类命中辨析）"],
 seq=["同批：ACSD-T05（死键处置）、ACSD-T32（三臂）"],
 blocks=["`CONTROL_WEIGHT_SNR.md`/`DATA_SEMANTICS.md` 与 T28/T32/T36 共改 ⇒ 同批"],
 neg=["合同声明字段而产品无该字段 ⇒ 合同一致性门判红（现状：结果件里 `snr` 出现 0 次仍判绿）"],
 forbid=["不得以顶替名继续出具「重建误差」读数"],
 note="根因与 T20 同源（预测方差未实现、`sparse_reconstruct` 生产链缺失）：第②层建议按同一工单合并处置、不重复计数，两任务须同批交付。"),

dict(id="ACSD-T34", short="实验头条数字改闭式", wave="W1", tier="P2", domain="实验",
 title="归档头条取自 N=1000 单次 MC 实现值：改引用 seed 无关的闭式并补判据",
 objs=["实验/absolute-snr/REPORT_paper.md", "实验/absolute-snr/code/b2_noise_terms.py",
       "实验/absolute-snr/results/b2_noise_terms.json", "实验/absolute-snr/results/ctest_evidence.md",
       "实验/absolute-snr/results/EXP06_TABLES.md", "实验/absolute-snr/results/REVIEW.md"],
 basis="「复核-AUD202-补」V6（判定：确认，定级 P2 — 头条 +12.8% 是 N=1000 单次实现值，分母样本噪声 sd 2.94pp；同物理点四条轴四个数、极差 4.84pp；seed 无关的闭式 +14.5009% 就在同一 JSON 里；约束它的 `max_abs_diff`（7.00pp）判定方 0 处；本仓 `REPORT_paper.md:225/:371` 已自登记）。",
 how=["把引用面的数字改为同一 JSON 内的闭式值",
      "为 `max_abs_diff` 补一条真判红的面（判定方现为 0 处 = 恒真）",
      "在报告里点名四条轴与极差，不把单轴读数当物理量",
      "补「真值无双计 ⇒ 归零」负例（AGENTS.md §5 判据非退化）"],
 seq=["无前置"],
 blocks=[],
 neg=["把闭式值换回单次实现值 ⇒ 判据必须判红（现状无判定方，不红）"],
 forbid=["不得以「如实登记偏差」代替改正引用面；不得另立一条「未披露」性质的 P1（第②层已把成因降级）"],
 note=""),

dict(id="ACSD-T35", short="接缝门统计量与证据同源", wave="W1", tier="P1", domain="科学+门禁",
 title="出厂接缝门含可相消的法向梯度项，与验收证据用的是两个统计量",
 objs=["eng/tools/e2e/seam_footprint.py", "实验/additive-sky-seamless/code/sci_c_common.py",
       "实验/additive-sky-seamless/README.md", "实验/additive-sky-seamless/REPORT_paper.md",
       "docs/science/PHASE2_UPM.md", "eng/tests/backend/test_p2003_seam_oracle.py",
       "实验/additive-sky-seamless/results/c1_additive.json", "实验/additive-sky-seamless/results/c5_weights.json"],
 basis="「复核-AUD203」V2（判定：确认，定级 P1）、V5（判定：确认，P2 证据缺口）；《天光无缝核验报告》DEV-02（门判据含可正可负的法向梯度项 ⇒ 相干结构读数可达门限 72.6%；分子是有符号量，梯度项与台阶代数相加、反号相消 ⇒ 实测门自己声明的确定性下限 1.005% 台阶被判绿，漏检面上推到 Δ/L ≈ 1.73%；「结构假阳性可区分」的证据属另一统计量 C4 N5 off-locus excess，而出货门 v2 已主动移除 off-locus）；AGENTS.md §9（能红能绿）。",
 how=["把「相干梯度无台阶必须绿」与反号相消算例补进 `REQUIRED_SELFTEST_CASES`（不动门限）",
      "§17.3 增列「梯度反号相消」漏检面，并把「Δ/L>1.005% 必判红」限定为「梯度项为零时」",
      "验收证据里把「结构可区分」限定为需与 `step_net`、d 扫描联合判读，明写 C4 N5 的 off-locus 结论不自动迁移到 boundary-only 门",
      "订正 docstring 的 78% 与正本 §17.4 的 72.6%（同一处两个写法 = 口径未同步，取正本值）",
      "补 `stalled=2` 的可驱动 stall 夹具（正/负例）并复跑 c5 归档（跟踪结果件现观测到的收敛态只有 {0,1}，且四态码比归档数据晚一天落地）"],
 seq=["前置：ACSD-T02（读数入库）"],
 blocks=["`PHASE2_UPM.md` 与 T02/T24/T29 共改 ⇒ 同批；`seam_footprint.py` 与 T42 共改"],
 neg=["构造反号梯度与真台阶代数相消的夹具 ⇒ 门必须判红（现状静默判绿）",
      "构造相干梯度无台阶 ⇒ 必须判绿（否则门误红）",
      "`stalled=2` 无夹具驱动 ⇒ 该态无证据资格，登记为待补"],
 forbid=["不得放松门限来掩盖相消面；不得把另一统计量的结论直接迁移为本门的证据"],
 note=""),

dict(id="ACSD-T36", short="机器层同名互斥事实源与合同数值快照退位", wave="W1", tier="P1", domain="合同",
 title="`pixel_area_power` 机器层两事实源同名互斥；`CONFIG_CONTRACT.md` 越位成第二登记面",
 objs=["eng/contracts/schemas/unified/variance.schema.json", "docs/contracts/unified_object_registry.json",
       "eng/contracts/data/v6_clause_registry_v1.json",
       "eng/contracts/schemas/product_family_field_constraints.schema.json",
       "docs/contracts/CONFIG_CONTRACT.md", "docs/contracts/DATA_SEMANTICS.md",
       "eng/ci/check_product_contract.py", "eng/packaging/config/config_registry.json",
       "eng/tests/config/", "eng/tests/contracts/test_unified_object_contract.py",
       "lib/algorithms/resample/p3_rsmp_units.cpp", "lib/infrastructure/aio/v6/src/v6_bunit.cpp",
       "lib/algorithms/drizzle/healpix_drizzle/v6_drizzle_science.cpp", "eng/ci/checks.json",
       "lib/infrastructure/aio/v6/src/v6_provenance.cpp", "eng/tests/unit/v6_p1_drz/v6_p1_drz_test.cpp",
       "eng/contracts/schemas/unified/examples/"],
 basis="「复核-合同层」W1（判定：确认，但成稿事实面不完整 —— 冲突不是「说明层 vs 机器层」而是「机器层内部两个事实源同名互斥」）、W3（判定：确认＋定级上调 —— 性质不是「抄了旧快照」，是「越位成第二套登记面」，且其复制对象自身也已漂移；按实现逐位复算，在册门 `UT-CONFIG` 在当前 HEAD 必红）。",
 how=["为每个同名键指定唯一源，其余面改为指针；`variance.schema.json` 与 `unified_object_registry.json` 二者取一并删除另一处的数值",
      "把 `CONFIG_CONTRACT.md` 的数值快照整体退位为指针 + 校验规则（合同里不该出现可漂移的计数值），并同步其复制对象 `config_registry.json` 的漂移",
      "补「合同文本不得含可漂移计数值」的机检判据（按第②层给出的可机检替代判据）",
      "`UT-CONFIG` 与其数据同批改：门与数据同批，否则出现「改了校验器数据全红」或「改了数据校验器全红」的中间态"],
 seq=["前置：ACSD-T00 批 2 的字段自描述（同一条 `STEP_REQUIRED` 面）"],
 blocks=["死结形态登记：`UT-CONFIG` 门 + `CONFIG_CONTRACT.md` + `config_registry.json` 三者必须同一提交",
         "`DATA_SEMANTICS.md` 由 T08/T21/T22/T27/T28/T33/T36/T37/T38 共改 ⇒ 必须由一个簇领改，其余簇改指针"],
 neg=["两侧事实源同名不同值 ⇒ 合同一致性门判红（现状：判绿）",
      "合同文本出现计数值（如 `docs/contracts/CONFIG_CONTRACT.md` 的 field_count 一类） ⇒ 新机检判红"],
 forbid=["不得以文档说明层「解释」机器层互斥而保留两源；不得把 `UT-CONFIG` 现有红灯以豁免覆盖"],
 note=""),

dict(id="ACSD-T37", short="must_contain 双向判据", wave="W1", tier="P1", domain="合同+门禁",
 title="`must_contain` 与唯一源互斥：改双向判据，不采纳会引入新 fail-open 的指针判据",
 objs=["eng/contracts/schemas/hips_storage_form.schema.json", "docs/contracts/HIPS_STORAGE_FORM_CONTRACT.md",
       "docs/design/PRODUCT_STORAGE_FORM.md", "eng/tools/hipsform/check_hips_storage_form.py",
       "eng/ci/checks.json", "docs/ci/CI_SPEC.md", "docs/design/PHASE1_DETAILED_DESIGN.md",
       "docs/design/PHASE2_DETAILED_DESIGN.md", "docs/design/PHASE3_DETAILED_DESIGN.md",
       "docs/interfaces/io/IO_002_HIPS_INPUT_INTERFACE.md", "docs/interfaces/io/IO_003_ATOMIC_OUTPUT_PUBLISH.md"],
 basis="「复核-合同层」W4（判定：确认（互斥成立、触发面缺口成立）＋处置方案降级 —— 成稿给的「换成指针判据」会净失一项现行判据强度，引入新 fail-open；须改为双向判据）；标准 05 §3。",
 how=["把判据改为双向：说明层声明的必备字段 ⊆ 机器层实际约束，且机器层约束 ⊆ 说明层声明（两侧各一条判红）",
      "补触发面：`check_hips_storage_form.py` 缺声明输入、配置缺失时按合同判红或按声明路径处理，不静默取默认",
      "订正 `PRODUCT_STORAGE_FORM.md` 与合同对同一约束的两种表述"],
 seq=["前置：ACSD-T36（先定唯一源，才能判「子集」方向）"],
 blocks=["与 ACSD-T38 共改 `HIPS_STORAGE_FORM_CONTRACT.md` 与同一 schema ⇒ 必须同批"],
 neg=["机器层多出一个说明层未声明的约束 ⇒ 反向判据判红；说明层声明一个机器层未约束的字段 ⇒ 正向判据判红（现状：只一侧有判据）"],
 forbid=["不得以「指针判据」替代双向判据（第②层已判其净失一项现行判据强度）"],
 note=""),

dict(id="ACSD-T38", short="裸形态产品级索引口径", wave="W1", tier="P1", domain="合同",
 title="裸形态是否允许没有产品级索引：五处口径 + 同一判据两侧相反，合同自身条款互斥到不可同时满足",
 objs=["docs/contracts/HIPS_STORAGE_FORM_CONTRACT.md", "docs/design/PRODUCT_STORAGE_FORM.md",
       "eng/contracts/schemas/hips_storage_form.schema.json", "eng/tools/hipsform/check_hips_storage_form.py",
       "eng/ci/ledgers/dead_config_keys.json", "lib/infrastructure/cli/session_commands.h", "eng/tools/"],
 basis="「复核-合同层」W5（判定：确认 —— 冲突成立且比成稿说的更硬：不是「三方」而是「五处口径 + 同一判据两侧相反」，其中合同自身条款互斥到不可同时满足）；标准 05 §3（读端不识别必要结构时 fail-closed）。",
 how=["先消掉合同自身互斥的两条条款（不可同时满足 = 结构缺陷，不是方向选择）",
      "把五处口径归一为一句正向约束：裸形态在 {允许|禁止} 无产品级索引，并点名读端行为",
      "把 `check_hips_storage_form.py` 的两侧相反判据改为同一方向的单一判据",
      "把 `session_commands.h` 的读端实现与合同声明比对，缺结构时判红"],
 seq=["同批：ACSD-T37（同一 schema、同一文件）"],
 blocks=["`HIPS_STORAGE_FORM_CONTRACT.md` + 该 schema 由 T37/T38 必须同批；若归一出现互斥产品方向（HiPS 产品数据模型的破坏性变更）⇒ 按 AGENTS.md §10 上呈，不自行取舍"],
 neg=["构造「裸形态 + 无产品级索引」输入 ⇒ 判据必须给出与声明一致的单一结论（现状两侧相反）"],
 forbid=["不得保留两侧相反判据中的任一侧"],
 note=""),

dict(id="ACSD-T39", short="追溯合同正则与反向连线", wave="W1", tier="P1", domain="合同+文档",
 title="ID 正则与被审对象、与检查器互斥；反向权威 `INDEX.yaml` 承载不了被委派的那几层",
 objs=["docs/contracts/INDEX.yaml", "eng/contracts/schemas/traceability_matrix.schema.json",
       "docs/TRACEABILITY.csv", "docs/traceability/TRACEABILITY_MATRIX.json",
       "docs/traceability/TRACEABILITY_MATRIX.csv", "eng/tools/traceability/check_traceability_matrix.py",
       "eng/ci/checks.json", "docs/design/UNIFIED_MODEL.md", "docs/traceability/"],
 basis="「复核-DB13」W2（判定：确认，头条数字降级）：30/30 行 `module_id` 对规范非法、对门合法；规范承诺的「两表关系」一节内容不存在（全文 `requirement_id` 0 次）；「八层 vs 九层」同文档两处；被指定的反向权威 `INDEX.yaml` 承载不了它被委派的那几层，且它与追溯矩阵之间没有任何在册门做反向连线（`CONTRACT-GRAPH`、`TRACEABILITY-MATRIX` 各自成立、互不相读）；反向面默认只 WARN、CI 不带 `--strict` ⇒ fail-open。定性＝主体缺规则、缺值只 10 条。",
 how=["统一规范正则 == 检查器正则 == 30/30 实际取值（三处同批）",
      "补规范 §5「两表关系」一节的实际内容；「八层 vs 九层」取一处",
      "给 SRC 规则与反向索引指认补内容；把 4 条超册项入基线或补锚",
      "把 `INDEX.yaml` ↔ 追溯矩阵的反向连线入册为新门，并让 CI 侧带 `--strict`（默认 WARN = fail-open）",
      "第②层口径入档：非占位 ID / 零命中 / VERIFIED 三个头条数不采信，改用复核口径（159 / 91 / 140 / 75）并写明统计口径"],
 seq=["前置：ACSD-T10（C3 覆盖 `实验/`、`工程控制/` 后，追溯对象集才与索引同源）"],
 blocks=["`docs/TRACEABILITY.csv` 与 `docs/traceability/**` 同时被 ACSD-T10 的迁移行指向 ⇒ 与 W4 迁移波同批或先于它"],
 neg=["修好判据：规范正则 == 检查器正则 == 30/30 取值；`--strict` 跑通且基线条目数 == 实际 WARN 数",
      "删一条反向连线 ⇒ 新门判红"],
 forbid=["不得把反向面留在默认 WARN；不得沿用未被复算的 137/64/53 一组数（已进作废表）"],
 note="成稿举例 `ALG-P1-WR-001`、`ALG-P2-RES-001`、`ALG-P2-SMP-001`、`ALG-P3-005` 四条「VERIFIED 零命中」已被推翻，见总览作废表。"),

dict(id="ACSD-T40", short="结果层数值口径与占位骨架", wave="W1", tier="P2", domain="实验+文档",
 title="同一物理量两值未标口径、手写报告字面量与自家 JSON 矛盾、未填充骨架占 `docs/` 位",
 objs=["docs/science/NOISE_MODEL.md", "docs/science/CONTROL_WEIGHT_SNR.md",
       "docs/plugins/algorithms_phase1/07_noise_snr.md", "docs/smooth-lambda.md",
       "实验/absolute-snr/README.md", "实验/absolute-snr/results/b1_sky_scan.json",
       "实验/absolute-snr/results/b2_noise_terms.json", "实验/absolute-snr/results/EXP06_TABLES.md",
       "实验/healpix-polar/docs/EXP-07-POLAR-摘要.md", "实验/healpix-polar/results/t17_extent.csv",
       "实验/additive-sky-seamless/REPORT_paper.md", "eng/tools/doccheck/doc_fact_authority.json",
       "eng/ci/check_doc_unverified_cite.py", "eng/tools/doccheck/check_doc_index.py",
       "实验/healpix-polar/docs/EXP-07-POLAR.md"],
 basis="「复核-结果层与收口层」R2（判定：降级 —— 4 条中 3 条成立、第 4 条推翻；SNAPSHOT 子核确认 47/47 通过）、R3（判定：确认 —— 差因＝口径未声明非取数错；SCI-B 读噪双计正式文档 34% 低估，现行正确值 = 最坏 +36.6%；healpix 同页 1.12e-8 与 2.79e-8 两值都真、差在样本面未写）、R4（判定：确认 —— 三处不一致全部复现，定级按是否进判据/对外主张分档）、R5（判定：确认 —— 占位与 5/7 结论行逐位复现，并补一条比成稿更重的观察）。",
 how=["在每个数值引用点补口径标注（样本面/统计量/实现值 vs 闭式），或改指唯一有跟踪副本的那一个",
      "把 SCI-B 读噪双计比例在正式文档改为最坏 +36.6%（现行 34% 低估缺陷量级）",
      "让手写报告层的三处字面量与 `doc_fact_authority.json` 对齐，并为该判据补实读断言（不一致即判红）",
      "`docs/smooth-lambda.md` 按 R5 处置：迁回 `实验/additive-sky-seamless/docs/` 或补全后转正，不留未填充骨架占正式文档层位",
      "R2 的第 4 条不执行（已被推翻，进作废表）"],
 seq=["前置：ACSD-T02（读数入库面），否则口径标注仍无跟踪副本"],
 blocks=["`NOISE_MODEL.md`/`CONTROL_WEIGHT_SNR.md` 与 T20/T32/T33 共改 ⇒ 同批；`check_doc_index.py` 与 T10 共改 ⇒ 同批"],
 neg=["报告字面量与其自家 JSON 不一致 ⇒ 判据判红；无跟踪副本的数字被当实测引用 ⇒ `check_doc_unverified_cite.py` 判红",
      "未填充骨架（5/7 结论行）留在 `docs/` ⇒ 角色/骨架判据判红"],
 forbid=["不得以删除整段冒充订正（判已修要看被点名的行本身）"],
 note="M42 帧级 σ 两份结果差约 4 倍：第②层判为口径未声明、两侧数值各自可回溯，属登记口径缺陷而非取数错。"),

dict(id="ACSD-T41", short="空间增益阶数六侧贯穿", wave="W1", tier="P1", domain="配置+代码",
 title="`photometry.fit.spatial_gain_order` 六面零登记、装配层兜底取二阶（前置：负责人裁-6）",
 objs=["cfg:photometry.fit.spatial_gain_order", "lib/infrastructure/scheduler/src/module_adapters.cpp",
       "eng/packaging/config/defaults.json", "eng/packaging/config/config_registry.json",
       "docs/plugins/algorithms_phase1/06_photometry.md", "lib/algorithms/photometry/README.md",
       "eng/tools/e2e/make_vis_configs.py", "eng/tools/quality/check_photometry_apply.py",
       "eng/tests/validation/release02/fix_p1_photometry_apply/"],
 basis="「复核-测光默认阶数」（判定：确认 —— 事实链全部成立 ＋ 定性与定级须修正，定级建议 P1 并给出升 P0 的唯一触发条件）；《UNRESOLVED 清单》裁-6；《链路间口径对表》§7 常数登记状态；AGENTS.md §6（不动科学公式与默认容差，除非按变更流程批准）。",
 how=["先取裁-6 的一句裁决（「验收前提是否算已过」）：未过 ⇒ 按现行条款退回零阶；已过 ⇒ 把条款改写为现状合法并补三口径复跑记录",
      "无论哪条路：补六面登记（配置模板、出厂默认、登记册、合同、CLI 协议、生产入口）＋ 值级断言（接 ACSD-T05）",
      "删除装配层「缺键静默取二阶」的兜底，改为显式报错或显式降级并写明原因（标准 04 §3）",
      "在生产启用件里显式带该键，消除「覆盖键在一条路上静默失效」的不对称"],
 seq=["前置：负责人裁-6；ACSD-T05 的值级判据"],
 blocks=["与 T05/T25 共用键与同一判据 ⇒ 必须同一提交"],
 neg=["配置不带该键跑一次 normalize ⇒ 实际生效值必须与登记值一致，否则判红（现状：没有任何现存判据会因此变红）",
      "六面中任一面缺登记 ⇒ 一致性门判红"],
 forbid=["不得在裁-6 未回前自行选数；不得把六侧不一致写成「仅文档问题」；不得以「无判据会红」作为不改的理由"],
 note="无裁决前本任务登记为 BLOCKED（AGENTS.md §10），不硬编、不预判。"),

dict(id="ACSD-T42", short="hips_profile 两形态等价性", wave="W1", tier="P1", domain="科学+代码",
 title="`hips_profile=0` 与 `=1` 在默认参数下不等价，误差来自 uint8 支撑格（前置：负责人裁-5）",
 objs=["lib/infrastructure/aio/src/hips/aio_hips_writer.cpp", "lib/algorithms/coverage/src/sampler.cpp",
       "eng/tools/e2e/seam_footprint.py", "eng/tools/e2e/render_vis.py", "eng/tools/quality/frame_qc_grid.py",
       "eng/tests/validation/release02/q2_snr_smoothness/realdata/realdata_seam.log",
       "docs/design/PRODUCT_STORAGE_FORM.md"],
 basis="「复核-AUD204」W3（判定：确认，并补两条成稿未报的更大分支；负责人待裁事项可据此定案）：`=1` 一侧除以按 8 位格点量化的支撑面积，误差随支撑变小而放大（典型量级千分之一点几、低支撑处可达百分之二以上，比 fp32 累加噪声差约四个数量级），支撑低于一个量化格时该像素按「未覆盖」发布、信号值为 NaN；`profile=0` 无偏移（已结案）；《UNRESOLVED 清单》裁-5。",
 how=["取裁-5：若判「必须等价」⇒ 把该腿改为除以精确面积或补归一，并加一条「两形态逐像素一致」的门",
      "若判「允许不同」⇒ 在设计（`PRODUCT_STORAGE_FORM.md`）与合同里写清两形态适用域与精度差，并解释 NaN 像素在产品侧如何被消费",
      "无论哪条路：补「低支撑 ⇒ 未覆盖 + NaN」的可驱动负例夹具"],
 seq=["前置：负责人裁-5"],
 blocks=["`seam_footprint.py` 与 ACSD-T35 共改 ⇒ 同批"],
 neg=["同一输入两形态逐像素比对 ⇒ 差异复现并判红（若选等价路线）；选允许不同路线时，文档未写精度差 ⇒ 口径门判红"],
 forbid=["不得以默认 profile 掩盖差异；不得自行裁定两形态是否必须等价"],
 note="我方倾向「必须等价」（差异由量化格式而非物理引入），但该选择属产品方向，未回前登记 BLOCKED。"),
]
