# -*- coding: utf-8 -*-
"""四链路报告（AUD-201..204）与其第②层复核件里的常数／公式／算法／容差条目。
逐条转写，不新增判读；凡复核改判者以复核为准，并在"来源成稿与条目"里两个都列。
字段顺序：符号｜类别｜值｜单位｜坐标系｜精度｜有限域｜来源现状｜出处｜处置｜适用域｜冲突｜成稿条目｜复核态｜位置补充
"""

# CAT: 常数/公式/算法/容差  DISP: 文献值/公式导出/实验标定/待确认/不适用
# CONF: 冲突标记文本（空=无）；REV: 是否已复核
CHAIN = [
# ---------------- AUD-201 测光链路 ----------------
dict(sym="F_syn 合成通量积分式", cat="公式",
     val="F_syn = ∫ F_λ(λ)·T(λ)·Q(λ)·λ dλ", unit="W·m⁻²·nm",
     coord="仪器/合成通量域；不含 10^(−0.4·G)", prec="由 location 吸收与星无关常数，无独立精度陈述",
     dom="Gaia XPSD 解码 F_λ 为能量谱辐照度时成立",
     src="文献值（A 一手：Gaia DR3 官方 §5.4.1 式(5.41)＋xp_sampled_mean_spectrum 单位声明）＋独立推导",
     ref="docs/science/PHOTOMETRY.md:44（§2a.1）、:55；AUD-201 §1 与 AUD201-002；hc=1.986445857e−16 J·nm 数值闭合",
     disp="公式导出", app="创新点① 测光定标全链",
     conf="", src2="AUD-201-测光核验 §1／AUD201-002", rev="是（复核-AUD201 V1/V2 独立复算）",
     pos=["lib/algorithms/photometry/cpp/src/spectrum_integrator.cpp:350",
          "lib/algorithms/photometry/cpp/src/spectrum_integrator.cpp:447"]),

dict(sym="被正本否定的通量式 ×10^(−0.4·mag_G)", cat="公式",
     val="F_syn' = ∫S(λ)T(λ)Q(λ)λ dλ × 10^(−0.4·mag_G)", unit="不闭合",
     coord="星等域与通量域混乘", prec="不适用",
     dom="任务书／派单文字；正本 §2a.1/:55/§2a.6 显式否定",
     src="无来源（被本仓正本否定的写法仍以「非生产通道」存活并被测试覆盖）",
     ref="AUD-201-测光核验 AUD201-001；复核-AUD201 V1（「被活跃调用」一项经复核改判）",
     disp="待确认", app="测光通量式选型（文档＋非生产通道）",
     conf="红：正本与任务书／在库非生产通道两种 F_syn 式并存（AUD201-001；复核-AUD201 V1）",
     src2="AUD-201-测光核验 AUD201-001／复核-AUD201 V1", rev="是（第②层复核覆盖成稿定性）", pos=[]),

dict(sym="λ 因子的成立前提", cat="公式",
     val="λ ∈ 被积式", unit="nm",
     coord="能量谱辐照度→光子计数率换算核（E=hc/λ）", prec="严格（差与星无关常数，被 location 吸收）",
     dom="仅当解码 F_λ 为能量谱辐照度；若容器给光子谱通量 ph·s⁻¹·m⁻²·nm⁻¹ 则必须去掉",
     src="文献值（A：Gaia DR3 官方 §5.4.1＋字段单位声明）＋第一性推导",
     ref="AUD201-002（CONFIRMED，正本无需订正）；前提未显式登记 → AUD201-003",
     disp="公式导出", app="XPSD 解码消费边界",
     conf="", src2="AUD-201-测光核验 AUD201-002／AUD201-003", rev="是（复核-AUD201 V2 独立复算）", pos=[]),

dict(sym="hc（λ 因子闭合用）", cat="常数",
     val="1.986445857e−16", unit="J·nm",
     coord="物理定义常数（6.62607015e−34 × 2.99792458e8）", prec="定义值，无容差",
     dom="全链通用", src="文献值（SI 定义）",
     ref="AUD-201-测光核验 AUD201-002 推导过程", disp="文献值", app="量纲闭合论证",
     conf="", src2="AUD-201-测光核验 AUD201-002", rev="是", pos=[]),

dict(sym="photometry.tukey_c / _TUKEY_C", cat="常数",
     val="4.685", unit="MAD 倍数（无量纲）",
     coord="Tukey biweight 尺度参数 c", prec="对应 95% 高斯渐近效率（eff=0.95 反解 c=4.6851）",
     dom="测光 IRLS 稳健位置；|z|>4.685 仅 2.8 ppm ⇒ 用 r_inliers 算 MAD 不引入截断偏差",
     src="公式导出（本审查独立复现：A(ψ,Φ) 积分扫表 c=4.685→0.95000）；书目侧 UNPROVEN",
     ref="docs/science/PHOTOMETRY.md:31/:207（真陈述行）；正本 :295 引 PMC6768164、:303 Beaton & Tukey 1974 未取回；star_matcher.cpp:23；spatial_gain.cpp:40 kTukeyC（重复定义）",
     disp="公式导出", app="测光 IRLS",
     conf="红：登记锚 :24 自始不含该值（复核判定「登记即错，0/8 从未成立」，与其余四条「漂移」不同源）；同值第二处 spatial_gain.cpp:40 无引用关系",
     src2="AUD-201-测光核验 AUD201-016／AUD201-017；复核-AUD201 V4（第 4 项历史裁决）",
     rev="是（复核-AUD201 V4 确认并加「登记即错 vs 漂移」分层）", pos=[
          "lib/algorithms/photometry/cpp/src/star_matcher.cpp:23",
          "lib/algorithms/photometry/cpp/src/spatial_gain.cpp:40"]),

dict(sym="_MAD_SCALE（1/Φ⁻¹(3/4)）", cat="常数",
     val="0.6744897501960817", unit="无量纲",
     coord="MAD→σ 换算因子", prec="1 ulp（独立解 0.67448975019608182，相对差 −1.646e−16）",
     dom="高斯模型下 σ=MAD/Φ⁻¹(3/4) 一致估计", src="公式导出（本审查独立推导复现）",
     ref="docs/science/PHOTOMETRY.md:34/:296（1.482602218505602 与之差 0）；star_matcher.cpp:21；四位截断 0.6745 偏差 +1.5196382e−05 与正本吻合",
     disp="公式导出", app="测光 sigma_residual／Phase1 稳健尺度",
     conf="", src2="AUD-201-测光核验 AUD201-016", rev="是（独立推导复现）",
     pos=["lib/algorithms/photometry/cpp/src/star_matcher.cpp:21"]),

dict(sym="photometry.mag_tolerance", cat="容差",
     val="3.0", unit="mag",
     coord="|delta_i − median(delta)| 预过滤阈", prec="未标注",
     dom="测光星等一致性预过滤；实测 sigma_residual≈0.045 mag ⇒ 3.0 mag=15.85 倍亮度，几乎不滤",
     src="有文献（本仓 SCI §5/:191/:202）；登记面为死键（生产无读取点）",
     ref="docs/science/PHOTOMETRY.md:34（真陈述行，注册件引 :30 偏 +4）；pc_api.cpp:145/:435 字面量 3.0；defaults.json 标 dead_config_key",
     disp="文献值", app="测光预过滤",
     conf="红：注册键死＋真值在代码字面量两处；正本 :218 指代码、:220 指配置键，同文档互相指认",
     src2="AUD-201-测光核验 AUD201-008／AUD201-013／AUD201-017；复核-AUD201 V4/V5；AUD-402-判读-A1 F-15",
     rev="是（复核-AUD201 V4 定 P1：溯源验证机制空转）",
     pos=["lib/algorithms/photometry/cpp/src/pc_api.cpp:145",
          "lib/algorithms/photometry/cpp/src/pc_api.cpp:435"]),

dict(sym="photometry.min_reference_stars", cat="常数",
     val="3", unit="星数", coord="r_consistent 进 IRLS 的最少参考星", prec="整数，无精度",
     dom="|r_consistent| ≥ 3 才进 IRLS，否则 NO_DATA", src="有文献（SCI §4/:191）",
     ref="docs/science/PHOTOMETRY.md:191（真行，注册件引 :44 偏 +147）；star_matcher.cpp:518 字面量",
     disp="文献值", app="测光定标入口判据",
     conf="红：注册键死＋日志文案另写一次 3（star_matcher.cpp:519-521）；同为「最少星数」语义的 min_stars_order1=50 无登记侧",
     src2="AUD-201-测光核验 AUD201-008；复核-AUD201 V4；AUD-402-判读-A1 F-15", rev="是",
     pos=["lib/algorithms/photometry/cpp/src/star_matcher.cpp:518"]),

dict(sym="photometry.min_inlier_stars", cat="常数",
     val="2", unit="星数", coord="估计 sigma_residual 的最少 inlier", prec="整数",
     dom="|r_inliers| ≥ 2 才估 sigma_residual，否则置 0", src="有文献（SCI §4/:191）",
     ref="docs/science/PHOTOMETRY.md:191（注册件引 :44 偏 +147）；star_matcher.cpp:616 字面量",
     disp="文献值", app="测光残差尺度估计",
     conf="红：n=2 时 MAD 无统计意义（判读层判「下限应随稳健尺度估计自由度提高」）＋注册键死",
     src2="AUD-201-测光核验 AUD201-008；复核-AUD201 V4；AUD-402-判读-A1", rev="是",
     pos=["lib/algorithms/photometry/cpp/src/star_matcher.cpp:616"]),

dict(sym="kMinFitStars", cat="常数",
     val="3", unit="星数", coord="空间增益/测光拟合的最小匹配星", prec="整数",
     dom="n_matched ≥ 3 即拟合合格；n_matched 就是 Tukey inlier 数",
     src="有文献（代码具名常量，无文档条款）",
     ref="AUD201-011（frame_photometry_fit.h:89）", disp="文献值", app="测光帧级拟合合格判定",
     conf="", src2="AUD-201-测光核验 AUD201-011", rev="是（复核-AUD201 V5 同链）",
     pos=["lib/algorithms/photometry/cpp/src/frame_photometry_fit.h:89"]),

dict(sym="sigma_residual 的「不可估计」编码", cat="容差",
     val="0.0", unit="dex",
     coord="两出口：样本不足、mad_in==0", prec="不适用（哨兵，非测量值）",
     dom="可达构造：r_inliers={2.0,2.0,5.0} ⇒ median 偏差=0 ⇒ sigma_residual=0 且 fit_ok=true",
     src="无来源（0 兼表「完美」与「不可估计」两义，区分只活在注释）",
     ref="star_matcher.cpp:614 注释自证；docs/science/PHOTOMETRY.md:191/§3/§8 无具名不可估计值",
     disp="待确认", app="测光标定质量门",
     conf="红：唯一消费门 P1_PHOT_MAX_SIGMA_DEX=1.0 只卡上界与有限性 ⇒ 假绿通道（fail-open）",
     src2="AUD-201-测光核验 AUD201-011；复核-AUD201 V5", rev="是（复核-AUD201 V5）",
     pos=["lib/algorithms/photometry/cpp/src/star_matcher.cpp:615",
          "lib/algorithms/photometry/cpp/src/star_matcher.cpp:621"]),

dict(sym="P1_PHOT_MAX_SIGMA_DEX", cat="容差",
     val="1.0", unit="dex", coord="帧级测光残差尺度上限", prec="未标注",
     dom="!isfinite ∥ > 1.0 ⇒ 帧 fail", src="无来源（代码具名常量，无文档登记）",
     ref="module_adapters.cpp:5327 定义、:5747-5748 判定；AUD201-011",
     disp="待确认", app="测光标定退化保护",
     conf="红：只卡上界 ⇒ 与 sigma_residual=0 的假绿同族（缺下界侧判定）",
     src2="AUD-201-测光核验 AUD201-011", rev="是（复核-AUD201 V5）",
     pos=["lib/infrastructure/scheduler/src/module_adapters.cpp:5327",
          "lib/infrastructure/scheduler/src/module_adapters.cpp:5747"]),

dict(sym="kMaxSpatialAmplitudeDex", cat="容差",
     val="1.0", unit="dex（max|log10 m|）", coord="空间增益幅度硬界",
     prec="实测真值 pp 7%、真机 3 帧 ≈0.1 dex ⇒ 10× 裕度",
     dom="超限 ⇒ FailKind::kHard 整帧 fail（错误码 PHOT_SPATIAL_GAIN_FIT_FAILED）",
     src="无来源（自述「约定值」，与 c=4.685、3× 抽样允差同类）",
     ref="spatial_gain.cpp:49 定义、:521 判定、:494-497 自述；defaults.json 无该键；UNRESOLVED 台账零命中",
     disp="待确认", app="Phase1 低阶乘性空间增益",
     conf="", src2="AUD-201-测光核验 AUD201-013；复核-测光默认阶数（影响面第 2 条）",
     rev="是（复核-测光默认阶数：该码全仓零登记）",
     pos=["lib/algorithms/photometry/cpp/src/spatial_gain.cpp:49",
          "lib/algorithms/photometry/cpp/src/spatial_gain.cpp:521"]),

dict(sym="m_cut 极限星等初值式", cat="公式",
     val="m_cut = 6.0 + 1.5·log10(f_mm) + 2·log10(t_s)", unit="mag",
     coord="割线迭代初值（estimate_mag_lim_iterative）", prec="只需作种子，常数取歪只多花 Gaia 查询次数",
     dom="PlateSolver 星表引导选星", src="无来源（三常数只在源码注释；正本零登记）",
     ref="ipv_select.cpp:335（注释）/:343-345（代码）；docs/plugins/algorithms_phase1/03_star_detection.md:25 与 phase_config_normalize.schema.json:358 声明派生输入含「画幅」",
     disp="待确认", app="星表引导检测的候选完备度",
     conf="红：文档声明输入集（焦距＋画幅＋曝光）与代码输入集（焦距＋曝光）不符；物理核对天光限域应为 1.25、读噪限域 2.5，代码 2.0 两域都不对应",
     src2="AUD-201-测光核验 AUD201-012", rev="是（第②层未单列，成稿独立第一性推导）",
     pos=["lib/algorithms/platesolve/cpp/ipv/src/ipv_select.cpp:335",
          "lib/algorithms/platesolve/cpp/ipv/src/ipv_select.cpp:343"]),

dict(sym="星密度指数（旧 1.3 → 实测 0.2885）", cat="常数",
     val="1.3（旧）→ 实测 α 0.243–0.456、中位 0.2885", unit="dex⁻¹（logN–logS 斜率）",
     coord="选星密度模型", prec="实测区间已给", dom="PlateSolver 目标星数反解",
     src="实验标定（订正只活在代码注释，正本沉默）",
     ref="ipv_select.cpp:360-365 注释自证「该偏差尚未在 docs/algorithms 登记为 DISP 条目」",
     disp="实验标定", app="星表引导选星",
     conf="红：旧值使模型高估 4–5 个数量级，订正未登记为 DISP 条目",
     src2="AUD-201-测光核验 AUD201-012", rev="否（仅成稿）",
     pos=["lib/algorithms/platesolve/cpp/ipv/src/ipv_select.cpp:360"]),

dict(sym="带内色项（未建模量）", cat="常数",
     val="0.0107 mag（斜率 ~0.0023 mag/(BP−RP)）", unit="mag",
     coord="带通内色项", prec="实测", dom="现行「非目标」豁免条只覆盖带通外色项",
     src="实验标定（实测数存在，既未建模也未登记）",
     ref="AUD201-009", disp="待确认", app="测光色项适用域",
     conf="", src2="AUD-201-测光核验 AUD201-009", rev="否（仅成稿）", pos=[]),

dict(sym="photometry.fit.spatial_gain_order / kDefaultSpatialGainOrder", cat="算法",
     val="代码兜底 2；算法层结构体默认 0；文档 §6(0)(c) 判「默认保持 0」、同文档 :89 又写「默认 order 1」、:434 写「配置默认 1」",
     unit="阶（整数）", coord="Phase1 低阶乘性空间增益 m(x,y) 的请求阶（0=关闭⇒m≡1；>2 钳到 2）",
     prec="不适用（离散档）",
     dom="出厂模板无 photometry 段 ⇒ 通道整条不使能；任何显式启用测光通道的运行 ⇒ 实取 2",
     src="无来源（六张登记面全空：出厂模板／defaults.json／config_registry／schema properties／合同说明与 CLI 协议／插件文档与 README；另 config_default_divergences watch_keys 亦无）",
     ref="module_adapters.cpp:5471 constexpr int kDefaultSpatialGainOrder=2、:5472-5476 读取式、:5489 通道使能门、:5708/:5716/:6072-6075 施加链；frame_photometry_fit.h:74=0；spatial_gain.h:80 order_requested=0；实验/photometric-magnitude/docs/p1-spatial-gain.md:454/:89/:434",
     disp="待确认", app="创新点① 产品像素面（逐像素乘 k_photo·m(x,y)）",
     conf="红：同一参数在生产两处入口与三处文档取不同值（0／1／2），且键在六面零登记 ⇒ 操作者无从发现、无从关闭；is_number_integer() 静默兜底使 0.0、「0」、错键名一律回到 2",
     src2="复核-测光默认阶数（一、四侧对齐表；二、问1-3；三、判定）；AUD-101-DB-18 §1.10",
     rev="是（复核覆盖成稿：定级 P1，并给出升 P0 的唯一触发条件）",
     pos=["lib/infrastructure/scheduler/src/module_adapters.cpp:5471",
          "lib/infrastructure/scheduler/src/module_adapters.cpp:5489",
          "lib/infrastructure/scheduler/src/module_adapters.cpp:6072"]),

dict(sym="min_stars_order1 / min_stars_order2", cat="常数",
     val="50 / 200", unit="星数", coord="空间增益升阶的星数门", prec="未标注",
     dom="spatial_gain.h:85 默认、frame_photometry_fit.h:76/:377 透传",
     src="无来源（同为「最少星数」语义，50 无任何登记侧）",
     ref="AUD-402-判读-A1 F-15；results 侧 N=100/200 聚集档 o2 形状误差 24.36%/21.38%",
     disp="待确认", app="Phase1 空间增益升阶阶梯",
     conf="红：与已登记的 photometry.min_reference_stars=3 同语义不同档、无横向说明",
     src2="AUD-402-判读-A1 F-15；复核-测光默认阶数 §一·附", rev="是",
     pos=["lib/algorithms/photometry/cpp/src/spatial_gain.h:85",
          "lib/algorithms/photometry/cpp/src/frame_photometry_fit.h:76"]),

# ---------------- AUD-202 SNR 链路 ----------------
dict(sym="σ_i² 逐像素噪声组成式", cat="公式",
     val="σ_i² = σ_sky,i² + (RN/g)² + F·P_i/g", unit="ADU²",
     coord="三项同为 ADU²（读噪只出现一次）", prec="独立 MC 复算 σ_F 两点 ≤3σ（z=+0.35 / −1.75）",
     dom="Σ_i P_i = 1 在截断网格上成立；half=12→60 时 ΣP² 第 5 位起不动 ⇒ 截断不构成误差源",
     src="文献值（A：Horne 1986 PASP 98 609；本仓 NOISE_MODEL.md:324 §9a）＋独立推导＋独立 MC",
     ref="docs/science/NOISE_MODEL.md:324；docs/plugins/algorithms_phase1/07_noise_snr.md:110；snr_science.cpp:200-202/:198",
     disp="公式导出", app="Phase1 逐源 SNR／Phase2 权重",
     conf="", src2="AUD-202-SNR核验 AUD202-011（证真条目）", rev="是（第②层复核未推翻，成稿即独立复算）",
     pos=["lib/algorithms/noise_snr/cpp/src/snr_science.cpp:200",
          "lib/algorithms/noise_snr/cpp/src/snr_science.cpp:201",
          "lib/algorithms/noise_snr/cpp/src/snr_science.cpp:202"]),

dict(sym="sigma_sky_source 的择一（生产写死）", cat="算法",
     val="SNR_SIGMA_SKY_EMPIRICAL_TOTAL_RMS（无条件赋值）", unit="枚举",
     coord="σ_sky 的口径来源", prec="不适用",
     dom="决策树分支 1（shot_noise_only 且 gain>0 的散粒口径）从生产不可达；自估增益主路径（NOISE_MODEL §5c 第 1 条 V=σ0²+S/g 斜率–截距回归）未实现",
     src="有文献（§4.2a 决策树与 §5c 主路径为本仓 SCI 条文）＋代码接线事实",
     ref="module_adapters.cpp:7159 赋值、:7151 noise_sigma 入参、:7130-7136 upper_bound_no_gain（此点证真）；docs/plugins/algorithms_phase1/07_noise_snr.md:118-122；docs/science/NOISE_MODEL.md:223-242",
     disp="待确认", app="跨帧绝对 SNR（创新点②）",
     conf="红：设计本意分支在生产不可达，择一由接线层写死而非由声明面决定",
     src2="AUD-202-SNR核验 AUD202-005", rev="是（CONFIRMED）",
     pos=["lib/infrastructure/scheduler/src/module_adapters.cpp:7159"]),

dict(sym="snr.gain_e_per_adu 的默认", cat="常数",
     val="0.0（配置缺省⇒未知）", unit="e⁻/ADU",
     coord="增益", prec="不适用",
     dom="schema 明文「缺失 = 未知 gain/ZP（天空受限最优提取，m_5 = null）」；M42 真实帧 124 个关键字中 GAIN/RDNOISE/EGAIN 全缺",
     src="无来源（defaults.json 与出厂模板均无 snr.gain_e_per_adu 默认值登记 ⇒ 四侧默认缺位形态）",
     ref="phase_config_normalize.schema.json:229；module_adapters.cpp:6794；docs/science/NOISE_MODEL.md:239-240",
     disp="待确认", app="SNR 口径选择",
     conf="红：键有语义、有消费点，但无任何默认侧登记",
     src2="AUD-202-SNR核验 AUD202-005", rev="是", pos=[
          "lib/infrastructure/scheduler/src/module_adapters.cpp:6794"]),

dict(sym="intra_snr（Phase2 帧内项）", cat="算法",
     val="恒 1.0（in.sparse = nullptr）", unit="无量纲",
     coord="actual_snr = frame_snr × intra_snr", prec="不适用",
     dom="稀疏 SNR 层未接入生产数据面 ⇒ 逐帧常数权",
     src="不适用（结构性：未接线的降级路径，且已显式声明 uncertainty_available=false、weight_source=frame_snr）",
     ref="weight_chain.cpp:714 double intra = 1.0、:739、:779；module_adapters.cpp:11534 in.sparse=nullptr",
     disp="不适用", app="Phase2 叠加权（臂 B）",
     conf="", src2="AUD-202-SNR核验 AUD202-003；复核-AUD202 V1", rev="是（复核改判：臂 B 判为「已声明降级＝非缺陷」，与臂 A 拆开定级）",
     pos=["lib/infrastructure/scheduler/src/module_adapters.cpp:11534"]),

dict(sym="Phase2 逐像素科学权重（臂 A）", cat="公式",
     val="w_used = 1/σ_bg²（背景面 ivar）；最优 w_opt = 1/(σ_bg² + S_src/g)", unit="ADU⁻²",
     coord="比值 R = w_used/w_opt = 1 + S_src/(g·σ_bg²)", prec="第②层复算倍数表：F=10³→7.6×（σ_bg=5,g=1.3）；F=10⁶→6645×",
     dom="σ_bg² 只在 S_src≡0 或 S_src/g ≪ σ_bg² 时等于样本方差",
     src="公式导出（Cauchy–Schwarz 取等条件 w_i ∝ 1/v_i；photutils calc_total_error σ_tot=√(σ_bkg²+I/g_eff)；Zackay & Ofek 2017 II 标题自带背景主导限定）",
     ref="ASTROCS_DESIGN.md:156-158/:168-174；docs/science/NOISE_MODEL.md §5b/§5c/§10；module_adapters.cpp:11936/:8155/:12004",
     disp="公式导出", app="创新点②③ 叠加权＋产品误差面",
     conf="红：背景方差面冒充逐像素物理总方差场入权；mosaic variance=1/W 使亮源像素误差棒按构造偏小 1–3 个数量级（写入交付产品）",
     src2="AUD-202-SNR核验 AUD202-001/AUD202-010；复核-AUD202 V1（P0）",
     rev="是（复核-AUD202 V1 定 P0；V3 推翻「两篇 FROZEN 互斥需裁决」，降为 P2 文档订正）",
     pos=["lib/infrastructure/scheduler/src/module_adapters.cpp:11936",
          "lib/infrastructure/scheduler/src/module_adapters.cpp:8155",
          "lib/infrastructure/scheduler/src/module_adapters.cpp:12004"]),

dict(sym="无增益上界解析式 SNR_rep/SNR_true", cat="公式",
     val="文档式 √(1 + F/σ_bg²)", unit="文档式非无量纲（ADU⁻¹）",
     coord="天空受限口径的 SNR 高估倍数", prec="不适用",
     dom="应为 sqrt(ΣP²/σ_bg² · (ΣP²/(σ_bg²+FP_i/g))⁻¹)，必带 ΣP² 与 1/g 因子",
     src="无来源（文档式量纲不齐；41%/347% 两锚点 φ 未定义不可复算）",
     ref="docs/plugins/algorithms_phase1/07_noise_snr.md:121；AUD-202 复算表 1.028…3.717 倍",
     disp="公式导出", app="文档侧误差声明",
     conf="红：式子与它自己给出的数字不属同一对象",
     src2="AUD-202-SNR核验 AUD202-006；复核-AUD202-补 V5/V6 改判一览",
     rev="是（复核改判：41%/347% 改判为可复算 = 1/√(1−φ)；「1.03–3.72 倍」归因订正＝主项是缺 ΣP² 而非缺 1/g）",
     pos=["docs/plugins/algorithms_phase1/07_noise_snr.md:121"]),

dict(sym="node_reproduction_max_abs（「重建误差」）", cat="容差",
     val="0.0（结构体默认；实算恒 0）", unit="与被重建量同单位",
     coord="控制点自身复现最大绝对残差", prec="不适用",
     dom="算子被约束为「在控制点处精确复现节点值」⇒ 该量对三个插值算子恒等于 0（构造性质）",
     src="不适用（恒真判据，无证据资格）",
     ref="weight_chain.h:167 声明、weight_chain.cpp:544 赋值；docs/interfaces/data/DATA-002_PHASE_PRODUCT_EXCHANGE.md:99 要求的是「预测方差」（未实现）；docs/plugins/algorithms_phase1/07_noise_snr.md:193 约束③",
     disp="不适用", app="Phase2 SNR 重建精度声明",
     conf="红：合同要求的 prediction_variance 未实现，被一个构造恒 0 的量顶替",
     src2="AUD-202-SNR核验 AUD202-008；复核-AUD202-补 V5（18 组换源自测逐位 0，证据升级）",
     rev="是（复核 CONFIRMED 并加强）",
     pos=["lib/algorithms/integration/v6/include/astrocs/v6/weight_chain.h:167"]),

dict(sym="sparse_snr.spacing_px（Δ）的「够密」论证", cat="常数",
     val="64", unit="px", coord="稀疏 SNR 控制点间隔", prec="不适用",
     dom="注册件写 Δ/ℓ ≈ 1.1–1.6「够密」；Δ/ℓ > 1 按采样定理是欠采表述",
     src="无来源（几何便利 tile_width/8，非由 SNR 场空间尺度导出；本仓体实验 Δ*=32 px 起失效）",
     ref="eng/packaging/config/defaults.json:694；docs/plugins/algorithms_phase1/07_noise_snr.md:102；docs/science/CONTROL_WEIGHT_SNR.md:215 §8b；AUD-402-判读-A1 F-9/E-4/X-（schema 描述仍写 ℓ=48）",
     disp="待确认", app="Phase1 稀疏 SNR 层",
     conf="红：同一裁决三种口径（ℓ=48 作废 / 40.4–57.9 / schema 仍写 ℓ=48 且 Δ/ℓ=1.33）；64=512/8 两处独立字面量无派生链断言；该键生产零读取（死键台账 :110-122）",
     src2="AUD-202-SNR核验 AUD202-008②；AUD-402-判读-A1 F-9/E-4", rev="是（成稿 CONFIRMED；复核-AUD202-补 声明该项未核、维持成稿原状待另派）",
     pos=["eng/packaging/config/defaults.json:694"]),

dict(sym="双计偏差头条数 +12.8%/+34.0%", cat="常数",
     val="+12.791%（source_flux_e 轴）／+15.922%（read_noise_e 轴，同一物理点）／+33.954%（RN=50）；全证据面最坏 +36.62%",
     unit="相对偏差", coord="σ_F 因读噪双计的高估量", prec="MC 单次实现值，抽样噪声未随头条数字告示",
     dom="B2 扫描面内最坏 +34.0%；跨 B1（暗源 B=0）最坏 +36.6%",
     src="实验标定（归档 JSON 逐字段可回读，但分母取该 seed 的 MC 经验散度）",
     ref="实验/absolute-snr/results/b2_noise_terms.json、b1_sky_scan.json:36-38；docs/science/NOISE_MODEL.md:324；docs/science/CONTROL_WEIGHT_SNR.md:201；docs/plugins/algorithms_phase1/07_noise_snr.md:123",
     disp="实验标定", app="创新点② 论文主张与豁免条",
     conf="红：正式文档三处取 34.0%、实验与任务书四处取 36.6%，同文两值；把扫描面内极值标成「最坏点」",
     src2="AUD-202-SNR核验 AUD202-012；复核-AUD202-补 V6 改判一览；复核-结果层与收口层 R3②",
     rev="是（复核改判：成因降级为「引用面选择噪声量」，定 P2；现行正确值 = 最坏 +36.6%）", pos=[
          "实验/absolute-snr/results/b2_noise_terms.json"]),

dict(sym="pred_doublecount_bias（解析值）", cat="常数",
     val="+14.500914%（基准点）／+38.252%（RN=50）", unit="相对偏差",
     coord="σ_F_from(v_emp)/σ_F_from(v_corr) − 1", prec="纯解析量，与网格 half=12..60 无关（第②层复算恒 14.501%）",
     dom="seed 无关、可独立复核", src="公式导出",
     ref="实验/absolute-snr/code/b2_noise_terms.py:105；AUD202-012 表",
     disp="公式导出", app="文档头条数的应取值",
     conf="", src2="AUD-202-SNR核验 AUD202-012；复核-AUD202-补 V6", rev="是",
     pos=["实验/absolute-snr/code/b2_noise_terms.py:105"]),

dict(sym="G4c_pred_vs_measured_mc_max_abs_diff", cat="容差",
     val="0.070030", unit="绝对相对偏差", coord="解析预测 vs MC 实测的最大偏离",
     prec="不适用", dom="被算出但无门约束", src="不适用（记录量，未升为门）",
     ref="实验/absolute-snr/results/b2_noise_terms.json gates.G4c_pred_vs_measured_mc_max_abs_diff",
     disp="待确认", app="SCI-B 实验门表",
     conf="红：偏离被算出却无门约束 ⇒ 门卡在不会红的量上",
     src2="AUD-202-SNR核验 AUD202-012；复核-AUD202-补 V6③", rev="是",
     pos=["实验/absolute-snr/results/b2_noise_terms.json"]),

dict(sym="SKY_E+DARK+RN²（σ_sky,e² 声明常数）", cat="常数",
     val="300.5", unit="e⁻²", coord="实验侧声明常数", prec="不适用",
     dom="用于反解成稿权重退化表的隐含 P_0", src="不适用（实验夹具常数）",
     ref="实验/absolute-snr/code/b3_domain_map.py:41；复核-AUD202 V1(c) 反解",
     disp="不适用", app="SCI-B 实验可复核性",
     conf="红：成稿头条倍数未随文写 P_0/PSF 宽度与 σ_sky 取值 ⇒ 不可独立复核（同一 σ_sky 下 PSF 放宽到 σ_px=2.0 时 ×1058 降到 ×398）",
     src2="复核-AUD202 V1（与成稿差异第 1 条）", rev="是",
     pos=["实验/absolute-snr/code/b3_domain_map.py:41"]),
]
