# -*- coding: utf-8 -*-
MODE = "append"
ROWS = [
["tests 目录内但无 target 编译的测试源：lib/algorithms/drizzle/healpix_drizzle/tests/ 的 19 个 TU（bench_drizzle.cpp, bench_write.cpp, concurrency_cache_test.cpp, drizzle_l0_test.cpp, drizzle_l2_test.cpp, drizzle_science_completion_test.cpp, hiss_write_probe.cpp, kcorr_matrix_test.cpp, oracle_edge_crossing_test.cpp, oracle_independent_test.cpp, p0_sip_order_guard_test.cpp, probe_reverse_steps.cpp 等）",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（复核：AUD-401 机器表 bucket=ORPHAN 且路径含 /tests/ 者共 51 条，其中 drizzle/healpix_drizzle/tests 19 条；本审查独立复核 git grep -cw -e drizzle_l2_test.cpp -- CMakeLists.txt eng lib => 0 命中）",
 "否——没有任何 CMake 源清单命名 ⇒ 不建、不跑、不计入 ctest",
 "先解引用再删：这批是**写了但从未接线的测试**，属「测试静默漏跑」而不是纯死码。逐条判：仍描述现行合同 ⇒ 接进 eng/tests 或模块 test target；已被别的门覆盖 ⇒ 删",
 "若接线：新增 add_test 会影响 ctest 计数类门（红灯数须附档位与 skip 计绿那类台账）；若删：须确认无文档以之为证据",
 "高（判反即错）：这类最容易被整批删掉，而其中 oracle_* 两个 TU 按命名是**独立 Oracle**（验收第四层证据），删了等于削证据；必须先与 Oracle 面比对",
 "中——23 条未逐条读实现，接线/删除的逐条判定缺「该测试断言是否已被别处覆盖」",
],

["tests 目录内但无 target 编译的测试源：lib/infrastructure/aio/ 下 13 个 TU",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（同族命令；aio 全域还被 CHK-RETIRED-CODE 以 AIO_WHITELIST_PREFIX=lib/infrastructure/aio/ 排除扫描 ⇒ 双重不可见）",
 "否",
 "先解引用再删（同上）",
 "无门；但若接线进 ctest 会影响 CHK-RETIRED-CODE 的 R1/R2 命中面（它现在扫不到 aio）",
 "高：aio 既不在构建图也不在退役检查面，是全仓**最不受门保护**的一片；批量删的风险由人承担",
 "中"],

["tests 目录内但无 target 编译的测试源：其余 19 个 TU（lib/infrastructure/pipeline/ 5、lib/algorithms/shared/ 3、noise_snr/ 2、photometry/ 2、platesolve/ 2、calibration/ 1、coverage/ 1、projection/ 1、resample/ 1、star_detection/ 1、其余 0）",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（同族命令）",
 "否",
 "先解引用再删（同上；lib/algorithms/coverage/tests/sanitize_driver.cpp 属 sanitizer 驱动，须单独判是否由手工脚本面使用）",
 "无",
 "中",
 "中"],

["六个零引用头：lib/algorithms/shared/dirent_win.h、lib/infrastructure/aio/include/aio_ahpx_format.h、lib/infrastructure/cli/memory_growth.h、lib/infrastructure/pipeline/orchestrator/cpp/include/spill_manager.h、lib/infrastructure/aio/third_party/cfitsio/f77.inc、lib/infrastructure/pipeline/typed_dag_contract.h",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记1（复核：AUD-401 的后缀全匹配普查在 354 个头中判 6 个零引用；本审查对 typed_dag_contract.h 独立复核 git grep -cw -e typed_dag_contract -- lib eng docs => 仅自身与问题台账命中）",
 "否——但 typed_dag_contract.h 已有问题台账条目 L28c-E-001（artifacts/evidence/audit-2026-01/FIX_LEDGER.csv:106，状态 OPEN）记为「全仓零消费者、不在任何构建/测试源列表」⇒ 属**已登未处理**",
 "分组处置：dirent_win.h／f77.inc（vendored 上游文件）保留并说明理由；aio_ahpx_format.h **不许删**（是 AHPX 三件套测试 target 的类型来源，见 AUD-404 行 6-8）；memory_growth.h／spill_manager.h／typed_dag_contract.h 删除",
 "若删 typed_dag_contract.h ⇒ 须同步 L28c-E-001 台账状态；spill_manager.h 属 orchestrator 子图（ALONE 档独立构建树），删前核其独立 CMake",
 "高（档极易写错）：aio_ahpx_format.h 的「零引用」是因为引用它的 TU 自己也不在生产 target ⇒ 两层死码互相遮蔽；把它当零引用头删掉，AHPX-WEIGHT-RETIRED 门的测试就编不过",
 "中"],

["CMakeLists.txt:337（「…退役; 落地取 §9.66-B 选项 1 = 源文件直接编入 astrocs_phase1_noise」）",
 "退役未清理",
 "不被任何 target 编译",
 "生产1(本行注释)/测试0/文档0/登记0（复核：git grep -n -e 退役 -- CMakeLists.txt => 2 行，即 :337 与 :804）",
 "是——本行引用 ASTROCS_DESIGN §9.66-B 选项 1 作为编译归属依据，是**构建决策的留痕**；同族 §9.66 条款由文档接线门核对",
 "加统一退役标注→实际应为改写：这是「已按选项 1 落地」的历史叙述（标准 04 §5:49 注释不含已撤销设计的历史叙述），应改写为正向陈述「本 TU 由 §9.66-B 选项 1 直接编入 astrocs_phase1_noise」",
 "无",
 "低（对门）；中（对规范）：保留章节号引用违反标准 04 §5:47「注释中的任务编号、控制包章节引用清理」",
 "高"],

["CMakeLists.txt:804（「B 已退役, 不再编入。」）",
 "退役未清理",
 "不被任何 target 编译",
 "生产1(本行注释)/测试0/文档0/登记0（同族命令；本行同时含实测数据「A 全算法 <=0.35% (独立复现, 3 seed)」）",
 "是——本行的实测数是 benchmark 结论，若被 §9.66 或 ISA 条款引用为凭据则不可轻删",
 "加统一退役标注：B 方案属「等待被删的历史实现说明」，按 ENGINEERING_SPEC §2 五字段块登记（WHAT/WHY-KEPT/STATUS/EXIT/AUTHORITY），别留半句话",
 "无（若 B 的源文件仍在树 ⇒ 那才是真死码，本行只是它的墓碑）",
 "低；但注意本行的实测数是**唯一留痕**（无对应跟踪证据件），删掉即失去可追溯的取舍依据",
 "中"],

["lib/algorithms/coverage/src/coverage.cpp:369-390（RETIRED-OBJECT-REJECT / PSFSW-RETIRE-01 注释块）",
 "退役未清理",
 "已退役",
 "生产2/测试2/文档3/登记3（复核：git grep -n -e RETIRED-OBJECT-REJECT -- lib eng docs；本块显式指向 eng/contracts/data/unified_object_compatibility_map_v1.json:133-143）",
 "是——三重承载：①负例门 lib/algorithms/coverage/tests/retired_object_reject_negative_test.cpp 与 weight_mode_retire_negative_test.cpp（「能红能绿」）；②门 CHK-PSFSW-RETIRED-STATIC（ID 出处 eng/ci/checks.json，command=eng/ci/check_psfsw_retired.py）；③合同 eng/contracts/data/unified_object_compatibility_map_v1.json:133-143（14→13 退役登记）＋ v6_clause_registry_v1.json#weight_modes.retired",
 "不许删：这是退役对象 **psfsw_robust_weight 的显式拒绝面**（fail-closed），删掉即从「显式拒绝」退化为「静默接受」，负例门立即判红",
 "无——保持现状；若将来要清，须先撤 CHK-PSFSW-RETIRED-STATIC 与两个负例测试与合同登记（四者同批）",
 "高（改对反而判红的最强一类）：看起来是「旧对象的残留字符串」，实际是判据本体；且它的**存在**是合同条款的实现载体",
 "高"],

["lib/algorithms/coverage/include/astro/phase2/coverage.h:78-93 与 :160-161（FZ-MODE-RETIRED 词表与「不得另造词表」条款）",
 "退役未清理",
 "已退役",
 "生产2/测试2/文档2/登记2（本头 :88-89 指到 docs/science/PSF_SIGNAL_WEIGHT.md §1/§4 与 coverage.cpp 的 RETIRED-OBJECT-REJECT 块，并声明「本头文件不得另造词表（C-004.3）」）",
 "是——C-004.3 条款（合同/配置门 CHK-CFG-004 族；复核：eng/tests/config/test_cfg004_unified_contract.py 含 RETIRED 命中）＋ CHK-PSFSW-RETIRED-STATIC",
 "不许删：拒绝面的词表定义位置；:160-161 已如实改述为「退役对象的显式拒绝面」而非在役权重，写法合规",
 "docs/science/PSF_SIGNAL_WEIGHT.md（权威口径面）",
 "高：删词表 ⇒ 拒绝面失去单一来源，另造词表的风险正是 C-004.3 禁止的事",
 "高"],

["lib/algorithms/coverage/include/astro/phase2/{coverage.h:93,sampler.h:172}（「历史单位项 psfsw_robust_weight=1 随该对象退役」）",
 "退役未清理",
 "已退役",
 "生产2/测试0/文档2/登记1（v6_drizzle_science.cpp 的单位表侧另有 PSFSW-RETIRE-03 声明「行已物理删除」）",
 "是——单位项枚举由 v6 单位表面与 CHK-PSFSW-RETIRED-STATIC 共同核对；lib/algorithms/drizzle/healpix_drizzle/v6_drizzle_science.cpp:65 明写原 RETIRED 占位行已物理删除",
 "加统一退役标注→更准确是改写：单位项既然已物理删除，头里这两句属「已撤销设计的历史叙述」（标准 04 §5:49），应改写为正向约束「单位表不含该符号；出现即拒绝」",
 "lib/algorithms/drizzle/healpix_drizzle/v6_drizzle_science.cpp:65,93；docs/contracts/PUBLIC_API.md:2175,2201（同族叙述）",
 "中：PUBLIC_API.md:2175 已用删除线＋作废标注处理，头文件侧未同步 ⇒ 同一事实在两面的写法不一致",
 "中"],

["lib/algorithms/coverage/tests/retired_object_reject_negative_test.cpp 与 lib/algorithms/coverage/tests/weight_mode_retire_negative_test.cpp",
 "退役未清理",
 "不在生产 target",
 "生产0/测试2/文档1/登记2（由 lib/algorithms/coverage/CMakeLists.txt:153-163 的「PSFSW-RETIRE-01 退役对象负例门（能红能绿）」注册）",
 "是——CHK-PSFSW-RETIRED-NEGATIVE（ID 出处 eng/ci/checks.json）与该 CMake 段；两文件是负例门的载体",
 "不许删：它们是标准 04 §4:42「退役处置可由检查器核对，防止旧实现回流」的**唯一防回流机制**；删了就没有门能发现旧实现回流",
 "lib/algorithms/coverage/CMakeLists.txt:153-163",
 "高：这两个文件的名字里有 retired/retire，最容易被当成退役残留删掉，实际恰恰相反——它们是**防退役对象回流的门**",
 "高"],

["lib/algorithms/coverage/src/rejection.cpp:2622-2640（RETIRED-CODE-RETAINED 块，EXIT 段提到 DOC-402 与 coverage.cpp:376 同批删除）",
 "退役未清理",
 "已退役",
 "生产1/测试0/文档0/登记1（本审查注释块普查：六 token 齐备 ⇒ 合规；EXIT 文本含跨文件同批约定）",
 "是——CHK-RETIRED-CODE 的 R3 判据对象（本块合规）；其 EXIT 自指「与 coverage.cpp:376 同批删除：DOC-402 整体退役 frozen 的…」⇒ 删除条件是**另一个变更**完成",
 "保留并说明理由：合规保留件；不得因「看到 RETIRED 就删」。它的 EXIT 未成立（DOC-402 未收口）⇒ 现在删属违规",
 "coverage.cpp:376（EXIT 点名的同批对象）；DOC-402 收口面",
 "高：EXIT 里写死的 :376 行号已可能漂移（同文件另有 :369 起的 RETIRED-OBJECT-REJECT 块）⇒ 行号式 EXIT 不可机械核对，这正是「退役标注不合规」的第四种形态（见 .md 提案）",
 "高"],

["lib/algorithms/drizzle/healpix_drizzle/healpix_core.cpp:1 与 healpix_core.h:1（RETIRED-CODE-RETAINED 块在文件第 1 行）",
 "退役未清理",
 "已退役",
 "生产2/测试1/文档0/登记0（普查命中：两块六 token 齐备）",
 "是——CHK-RETIRED-CODE 的 R2 判据把 RETIRED 当横幅 token 只看前 40 行，本二件因**有** RETAINED 块而豁免 ⇒ 它们是 R2 的正例",
 "保留并说明理由：合规保留件；但横幅出现在文件第 1 行意味着「整文件退役」，与「仍被测试 target 编译」矛盾 ⇒ 须核 EXIT 是否已成立",
 "若 EXIT 成立：连同其测试面同批删",
 "中：EXIT 条件是否已满足未核（缺：EXIT 字段指向的收口事实）",
 "中"],

["lib/algorithms/star_detection/wrapper_phase1/star_detector.cpp:30（RETIRED-CODE-RETAINED 块）与 lib/infrastructure/pipeline/orchestrator/cpp/include/orchestrator.h:1（同）",
 "退役未清理",
 "非四档项（双档冲突，逐件分列）：star_detector.cpp 在生产 target；orchestrator.h 属 ALONE 档独立构建闭包，其 RETAINED 块按已退役登记",
 "生产2/测试0/文档1/登记0（普查命中 2 块，均六 token 齐备；orchestrator.h 属 ALONE 档独立构建树）",
 "是——CHK-RETIRED-CODE R2/R3 的正例；orchestrator.h 另受 ALONE 子图的独立构建面管辖",
 "保留并说明理由（两块均合规）；注意 star_detector.cpp **同时**带 RETAINED 块又列在生产 target ⇒ 这是「在产但自述保留件」的档冲突，须按 EXIT 判定并消解",
 "lib/algorithms/star_detection/CMakeLists（生产源清单面）",
 "高（档冲突）：若按「已退役」档直接删 ⇒ 生产 astrocs_phase1_stars 少源文件；若按「在生产 target」档不管 ⇒ 退役标注与生产事实互相打脸。本条是全清单里唯一「既在产又已标退役」的双档冲突",
 "中——需要 EXIT 字段所指的收口事实才能定档"],

["lib/algorithms/{noise_snr,photometry,platesolve,star_detection}/wrapper_phase1/ 四个目录 ＋ lib/algorithms/integration/v6_phase1/",
 "模板复制残留",
 "非四档项：在生产 target 且被生产面调用（因目录命名违规入表，不得按死代码处置）",
 "生产5/测试3/文档5/登记0（复核：AUD-401 机器表 4 个 wrapper TU 全为 PROD：astrocs_phase1_noise / _phot / _wcs / _stars；v6_phase1/src/phase1_product.cpp 为 astrocs_v6_phase1_product）⇒ 四档写「不在生产 target」是**错的**，正确记法见风险栏",
 "是——标准 04 §1:18 明令「模块按算法命名，不按阶段嵌套」；ASTROCS_DESIGN §8.4 与 ARCH-001 迁移台账把这些目录登记在案（eng/cmake/ARCH-001-migration-manifest.md 列 lib/healpix_db → 新址的同族迁移）",
 "改注册（迁移目录，不删代码）：把 wrapper_phase1/ 的内容并到模块根或 lib/include 面，目录名去阶段词；v6_phase1 同理。代码本身在产，删之即破产品",
 "各模块 CMakeLists 的源路径；module.yaml / types.h 宏 / install_layout.cmake 安装面；docs/modules/registry 生成页；ID 迁移台账 eng/ci/id_migration_map.json",
 "高（改名半贯穿的先例）：本仓已因改名半贯穿造成 UT-ABI 恒红与生产入口零登记 ⇒ 迁移目录必须一次贯穿（CMake＋yaml＋types.h＋integration.json＋安装面＋文档生成页），任一面漏改就是新的恒红门",
 "高"],

["工程控制/RELEASE-05/ 全部 31 个跟踪文件",
 "退役未清理",
 "不被任何 target 编译",
 "生产0/测试0/文档4/登记0（复核：git ls-files 工程控制 | wc -l => 31，全部在 RELEASE-05 子目录）",
 "是——AGENTS.md §7 把 工程控制/ 登记为控制包目录并注明「收口后按 CONTROL_PACK_SPEC §9 清理」；标准 04 §4:41「历史控制包…不留在生产目录，需要留证的落归档或 evidence 目录」",
 "改注册：RELEASE-05 若已收口 ⇒ 需要留证的部分迁 artifacts/evidence/，其余删除；若未收口 ⇒ 保留并说明理由（写明所属轮次）",
 "docs/ 内以 工程控制/RELEASE-05/OPEN_QUESTIONS.md 为锚的引用（复核：astrocs.phase{2,3}.resample 的 -F 命中面各含该文件 1 处）",
 "中：OPEN_QUESTIONS.md 被两枚未接线条目的对账引用 ⇒ 删之前须把其结论并入 docs/KNOWN_LIMITATIONS.md，否则限制陈述失去出处",
 "中——RELEASE-05 是否已收口属流程事实，本审查无法从跟踪面判定"],

["lib/infrastructure/cli/ 三命令「薄入口」（normalize/mosaic/export 三个头与 commands.cpp 的对应入口函数）",
 "占位模块",
 "在生产调用面零引用",
 "生产3/测试2/文档4/登记1（复核：AUD-401 AUD401-019 的「三命令薄入口零调用」论断；本审查独立复核其 CLI 头在生产调用面的命中数）",
 "是——CLI 三命令是对外合同面（docs/contracts/PUBLIC_API.md 的 CLI 章节与 CLI 协议测试 eng/tests/api/test_cli_protocol.py）；命令名本身不可删",
 "不许删：命令面是合同；其「零调用」指内部辅助入口，整改是把入口接到调度器而非删命令。本条入表是为防止按「薄入口零调用」字面去删命令",
 "无",
 "高（删之即破三命令划分这一顶层合同）：属 .md 里「不许删」那组的第二典型",
 "高"],

["lib/infrastructure/acr/ 的 108 个 ALONE 档 TU ＋ lib/infrastructure/hips_browser/ 的 18 个 ＋ lib/algorithms/platesolve/cpp/ipv 测试 8 个",
 "占位模块",
 "不在生产 target",
 "生产0/测试134/文档2/登记0（复核：AUD-401 机器表 bucket=ALONE 共 158 条，分布 acr 108／hips_browser 18／platesolve ipv test 8／integration 2／其余 cfitsio 独立子图）",
 "是——ACR 与 HiPS 浏览器各有**独立构建树**（自身 CMakeLists，不在根 add_subdirectory 闭包内）；ACR 生产不可达是最高设计既定边界",
 "保留并说明理由：它们不是死码，是「闭包外独立构建」，被误并入四档任何一档都会判错处置；标准 04 §4 不适用",
 "若有人把它们并入根图：会触发 ACR 生产可达性与 cfitsio 符号重复等既有约束",
 "高（档最易写错的一类）：按 CMake 根图判「不被任何 target 编译」是**错**的——它们在 ALONE 档；本审查用机器表的 ALONE 桶单列，正是为了避免这类误判",
 "高"],

["源代码注释指向 run/ 下未跟踪产物的指针（示例：lib/algorithms/coverage/include/astro/phase2/{upm.h,sampler.h,rejection.h} 五处「见 run/WIRING-W16-01/REPORT.md」；eng/tests/unit/v6_p3_proj/sin_roundtrip_gate.py:20-21「run/FIX-406/SIN_ROUNDTRIP_ORACLE.md」；eng/ci/retired_code_allowlist.json:5「run/CLEAN-401/RECEIPT.md」）",
 "未跟踪产物名",
 "不被任何 target 编译",
 "生产20/测试7/文档0/登记9（复核命令：git grep -oE 「run/[A-Za-z0-9_.-]+」 -- lib => 按目录计数 run/WIRING-W16-01 20 次、run/PROJECT-GOVERNANCE-01 7 次；lib/eng 合计 run/<task>/<file> 形态 1774 次）",
 "否——门不核注释里的 run/ 指针；但 eng/ci/checks.json 里 CHK-RETIRED-CODE 与 CHK-PROD-WIRING 的 --json-out 也写 run/**，说明 run/ 是**输出根**而非证据根",
 "改注册：run/ 是 gitignore 的临时产物根（AGENTS.md §7），把注释里的「见 run/…」改成可长期解析的指针：或迁 artifacts/evidence/ 并指过去，或删指针只留结论。标准 04 §5:47 要求「实验编号作为证据指针可保留并指向实验单元」，而 run/ 不满足「可长期解析」",
 "与 AUD-404 行 1-10 的退役注释同批（那 10 行里有 5 行的去向指针就是 run/WIRING-W16-01/REPORT.md）",
 "中：改指针不判红；**不改**则注释与登记面共同依赖一个仓库里不存在的文件 ⇒ 复核者无法验证退役裁决，属「看起来有依据、实际无凭据」",
 "高"],

["eng/ci/retired_code_allowlist.json（9 处 RETIRED 命中；条目为逐条豁免台账）",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记1（复核：CHK-RETIRED-CODE 默认 allowlist 路径 = eng/ci/retired_code_allowlist.json，见 check_retired_code.py 的 DEFAULT_ALLOWLIST_REL）",
 "是——它**就是** CHK-RETIRED-CODE 的输入：--allowlist 缺省时读本文件；显式传入而文件不存在 ⇒ rc=2 fail-closed",
 "不许删：删了会让检查器在「文件不存在」上行为分叉（默认路径缺失时只提示不判红，见其 :7 说明），且 9 条已复核假阳性失去豁免 ⇒ R1/R2 立即回潮",
 "无",
 "高：这是「豁免台账 = 门的必需输入」，属 .md 里「不许删」那组；删它不是清残留而是拆门",
 "高"],

["eng/ci/ID_MIGRATION_MAP.md 与 eng/ci/id_migration_map.json（9 与 29 处 RETIRED 命中）",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试2/文档3/登记2（复核：git grep -c RETIRED -- eng/ci/ID_MIGRATION_MAP.md eng/ci/id_migration_map.json => 9/29）",
 "是——ID 迁移台账被 STD-REG/ID 族门读取（eng/ci/checks.json 内含以 id_migration_map 为输入的条目；gen_id_migration_map_doc.py 由 JSON 生成 MD ⇒ MD 是**生成件**）",
 "不许删：改名贯穿的唯一登记处；且 MD 不得手改（生成件，须改 JSON 后重跑生成器）",
 "eng/ci/gen_id_migration_map_doc.py；改名相关门（UT-ABI 族曾因半贯穿恒红）",
 "高：手改 MD ⇒ 与 JSON 不一致 ⇒ 文档/登记面互斥；正解永远是改 JSON 再重生成",
 "高"],

["docs/algorithms/PHASE3_PROJ_IMPL.md 的 4 处 RETIRED 叙述",
 "登记面残留",
 "不在生产 target",
 "生产0/测试0/文档4/登记0（复核：git grep -c RETIRED -- docs/algorithms/PHASE3_PROJ_IMPL.md => 4）",
 "是——算法实现文档，被文档行锚族核对；其对象 p3_projection.cpp / p3_proj_v6.cpp 正处「仅测试 target 编译」档（AUD-404 行 60-61）",
 "先解引用再删：文档侧的「已退役」叙述必须与实现侧的实际档位一致；在实现进生产或按 §4 标注之前，文档不能先宣称退役，也不能被删（它是该实现的唯一说明面）",
 "lib/algorithms/projection/{p3_projection.cpp,p3_proj_v6.cpp,CMakeLists.txt}；eng/tests/unit/v6_p3_proj/*",
 "中：改文档而不改实现 ⇒ 文档说退役而代码仍被测试编译；改实现而不改文档 ⇒ 反向不一致。两面同批",
 "中"],

["lib/algorithms/coverage/src/sampler.cpp:86,567,581（K_CORR_DOMAIN 选项 B，scale 维 RETIRED）",
 "退役未清理",
 "已退役",
 "生产3/测试1/文档0/登记0（复核：三处同族叙述，测试面命中 lib/algorithms/coverage/tests/kcorr_lookup_test.cpp:59 「scale 维已退役」）",
 "是——kcorr_lookup_test.cpp 的 F2 段以「scale 维退役」为断言对象 ⇒ 测试与实现共同承载；另 sampler 在产（astrocs_phase2 族）",
 "加统一退役标注（本处目前只是散句，无六字段块）：把「scale 维退役」的原因/替代/去向按 ENGINEERING_SPEC §2 五字段登记；不要删代码路径的拒绝分支",
 "lib/algorithms/coverage/tests/kcorr_lookup_test.cpp:59；docs/science/ 与 docs/algorithms/ 的 K_CORR 条款",
 "高：:581 的 「%.4f（scale 维退役，禁 clamp）」 是**运行期诊断文案**，被测试断言匹配的可能性高 ⇒ 改文案可能判红，须先核 kcorr_lookup_test 是否 assertIn 该串",
 "中——未逐行读该测试的断言"],

["docs/contracts/DATA_SEMANTICS.md（3 处）与 docs/science/{PSF_SIGNAL_WEIGHT.md 2 处, UNIFIED_SCIENCE_MODEL.md 1 处}、docs/design/PHASE2_DETAILED_DESIGN.md、docs/owner/SCIENCE_OVERVIEW.md、docs/plugins/algorithms_phase2/13_integration.md、docs/validation/v6/NEGATIVE_MUTATION_CATALOG.md、docs/algorithms/PHASE3_PROJ_IMPL.md 的 RETIRED/退役叙述",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档14（本行列出的 8 个文件之和；命令：git grep -c -e RETIRED -e 退役 -- <这 8 个文件>）／全 docs 面为 24 文件 75 行（命令：git grep -c -e RETIRED -e 退役 -- docs | wc -l 与其末列求和）",
 "是——docs/science/ 与 docs/algorithms/ 是「只读权威、改动走变更流程」（AGENTS.md §5）；NEGATIVE_MUTATION_CATALOG.md 是负例变异目录（判据载体）",
 "不许删（改文档走变更流程）：科学面与合同面的退役叙述是裁决留痕，其「日期口径」由负责人裁决记录承载；本审查只在表内登记其存在，不提议删",
 "若将来按标准 04 §5:49 清历史叙述 ⇒ 须先把结论正向化，不能直接抹",
 "高：这些是「唯一来源」型文档面；.md 的「不许删」组以此为主。另 docs/ci/01_CHECKS.md 另有 5 处属门说明面，不在本行 8 文件内",
 "高"],

["artifacts/evidence/{governance-01/retire/RETIREMENT_LEDGER.md（5 处）, release-05/FAILCLOSED_SURVEY.md（6 处）, release-05/D-14_STALE_PATH_CLEANUP.md, v6/qa-design/{evidence/mutations.json, oracle/validate_spec.py}}",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记5（复核：git grep -c RETIRED -- artifacts/evidence => 命中集中于上述 5 件）",
 "部分——validate_spec.py 与 mutations.json 属 v6 qa-design 的 Oracle 面；CHK-RETIRED-CODE 的排除规则含「任何 */oracle/* 与 *_oracle.py（独立 Oracle 允许自带历史对照）」⇒ 该二件被检查器**显式豁免**",
 "保留并说明理由：artifacts/evidence/ 是证据根（AGENTS §7），标准 04 §4:41 正是要求「需要留证的落归档或 evidence 目录」⇒ 这些条目位置合规，不属「留在生产目录」",
 "无",
 "低：唯一注意点是别把 evidence 里的退役台账当生产残留清掉——那是裁决证据链",
 "高"],

["reports/v19r2/{file_audit_inventory.csv, source_manifest.csv}（合计 2 处对 astrocs.phase{2,3}.resample、eng/ci/prod_wiring_baseline.json 等现役面的登记）",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记2（复核：两文件的命中来自本审查 astrocs.phase*.resample 的 -F 匹配集）",
 "否——reports/ 非任何门的 changed_paths 输入（复核：git grep -c 「reports/v19r2」 -- eng/ci/checks.json => 0）",
 "改注册：这是**过期台账**（v19r2 轮次的快照，含已退役路径与 SHA/行数）；标准 04 §4:41 明令「过期台账不留在生产目录」。reports/ 不在 AGENTS §7 登记的根目录清单内 ⇒ 属根目录未登记条目",
 "新根目录条目须先登记并经负责人确认（AGENTS §7 末段）⇒ reports/ 的存废本身要上呈",
 "中：删了不判红；留着则每次全仓 grep 都会命中陈旧路径，污染「路径是否还存在」的判定（本审查就遇到 2 次假命中）",
 "高"],
]
