# -*- coding: utf-8 -*-
MODE = "append"
ROWS = [
["docs/audit/doc_classification.csv:33",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记1（命令：git grep -nw -e NEXT_STAGE -- docs eng => 2 行：本行判 present ＋ docs/DOCUMENT_INDEX.yaml:25 自陈已清除）",
 "否——git grep -n doc_classification -- eng/ci/checks.json 无门直接以本 CSV 为 command 输入（文档分类台账由文档面检查器读，未注册为独立门）",
 "删除本行（被登记文件的跟踪集中不存在）；复核命令：git ls-files docs/backlog => 0 文件",
 "docs/DOCUMENT_INDEX.yaml:25（该行的「已在本版清除」本身是历史叙述，按标准 04 §5 与文档口径应一并清）",
 "低：台账行删除不影响任何门；但留着 ⇒ 台账自称 present 而文件不在，属假登记",
 "高"],

["eng/ci/known_failures_baseline.json:257 (F-025)",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记1（条目 evidence 记「占位行数=381」，minimal_command = grep -c 'ADU/pixel/deg per header' docs/contracts/API_CONTRACTS.csv）",
 "是——本文件是已知失败棘轮台账；F-025 把 API_CONTRACTS.csv 的批量占位语义钉成「已知失败」，其 minimal_command 用**行数**做判据",
 "改注册（不删）：F-025 不是死代码而是**待修缺陷的登记**；它随 docs/contracts/API_CONTRACTS.csv 占位清理一并解除",
 "docs/contracts/API_CONTRACTS.csv 全部占位行（复核：git grep -c 'ADU/pixel/deg per header' -- docs/contracts/API_CONTRACTS.csv）",
 "高：以「行数」为判据 ⇒ 任何对该 CSV 的**正确**清理（删退役符号行）都会改变行数，可能让 F-025 的最小复算命令读数偏离而误判；删 AUD-404 行 12 之前必须先确认此判据方向",
 "高"],

["eng/tools/doccheck/dangling_ledger.json (max_entries=50 / entries=50)",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记1（本台账被 CHK-DANGLING 族用；复核：python 读该 JSON len(entries)=50 == max_entries=50）",
 "是——该 JSON 自述 purpose=「跨域未修悬空 docs/ 引用台账（doc-index 门用；只减不增）」，即门 ID CHK-DANGLING（ID 出处 eng/ci/checks.json，step=CON-DOC-SYMBOLS）",
 "保留并说明理由：它是棘轮台账本身不是死代码；但**已饱和**——须先解除条目再新增，否则新的悬空引用无处登记 ⇒ 直接判红",
 "本清单里凡「先解引用再删」的条目，删除后应回收本台账对应项（50 条中 44 条 owner=BLD-401）",
 "高（改对反而判红的最主要来源）：台账满额 ⇒ 开发节点按本表改文档时若引入任何新悬空 token 就无处豁免，只能判红；整改顺序必须是「先清台账再动文档」",
 "高"],

["eng/tools/quality/contracts/fixtures/check_api_contracts/ (valid_min.csv, invalid_sig_mismatch.csv, invalid_missing_symbol.csv)",
 "模板复制残留",
 "不被任何 target 编译",
 "生产0/测试3/文档0/登记0；每份 422 行（复核：git grep -n 'contracts/fixtures' | grep -v '^reports/' => 仅 3 处命中，全在 checks.json 的 check_full_integration/** 与其他目录，无一处指本目录）",
 "否——未接线：这三份夹具不被任何门的 command/args/changed_paths 引用；CON-API-CONTRACTS 真实输入是 docs/contracts/API_CONTRACTS.csv（check_api_contracts.py:19），不读夹具目录",
 "删除整目录（3 文件）或接线：ENGINEERING_SPEC §10 要求每检查项有正负例，若 check_api_contracts.py 无 --self-test，则该门缺可执行负例入口，删夹具前须先补",
 "若删：无连带（无人引用）。若接线：须让 check_api_contracts.py 的 --self-test 真读这三份",
 "低——但注意：夹具里 26 个 lib/* 路径是**改名前快照**（lib/phase2/include/**、lib/plate_solve/cpp/**、lib/orchestrator/cpp/** 等），删掉反而消除了一个「看起来还有效」的误导面",
 "高"],

["eng/tools/quality/contracts/fixtures/check_traceability/ (valid_min.csv, invalid_dup_id.csv, invalid_missing_doc.csv)",
 "模板复制残留",
 "不被任何 target 编译",
 "生产0/测试3/文档0/登记1（唯一命中是 eng/tools/doccheck/dangling_ledger.json:565 把 invalid_missing_doc.csv 记为「负例夹具字符串」）",
 "部分——invalid_missing_doc.csv 在 CHK-DANGLING 的豁免台账里被显式登记为「故意指向不存在文档的夹具」（ID 出处 eng/ci/checks.json→CHK-DANGLING）；valid_min.csv / invalid_dup_id.csv 无任何登记面",
 "改注册：invalid_missing_doc.csv 保留（是负例夹具，且已在台账豁免）；另两份为改名前陈旧快照（lib/phase2/src/upm.cpp 等 6 个路径不在跟踪集），删或重生成",
 "eng/tools/doccheck/dangling_ledger.json 的对应条目（保留项不动）",
 "中：若 valid_min.csv 被某次 --self-test 重新接线，陈旧路径会让自检恒红；现无门 ⇒ 删之不红",
 "高"],

["eng/tools/quality/contracts/fixtures/check_test_contracts/ (valid_min.csv, invalid_missing_assertion.csv, invalid_unregistered.csv)",
 "模板复制残留",
 "不被任何 target 编译",
 "生产0/测试3/文档0/登记0（陈旧路径 lib/calibration/src/calibrator.cpp、lib/dynamic_psf/src/dpsf_psf.cpp、lib/phase2/tests/synthetic_gate.cpp 均不在跟踪集）",
 "否——git grep -n 'contracts/fixtures' -- eng/ci/checks.json 只回 check_full_integration/**；本目录未被引用",
 "删除整目录（3 文件）或按现行路径重生成后接线",
 "无",
 "低",
 "高"],

["eng/contracts/data/aio_abi_contract_v1.json",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记1；内含路径名 lib/astro_image_io/src/aio_abi.cpp（不在跟踪集，现行为 lib/infrastructure/aio/…）",
 "是——合同层文件（eng/contracts/data/ 是机器校验的合同数据面）；同名锚亦登记于 eng/ci/ledgers/registration_anchor_ledger.json ⇒ 该门 CHK-REGISTRATION-ANCHORS（ID 出处 eng/ci/checks.json，command=eng/ci/check_registration_anchors.py）会按锚解析",
 "先解引用再删：把陈旧路径改成现行路径而非删除条目（它是 ABI 合同对实现锚的绑定）",
 "eng/ci/ledgers/registration_anchor_ledger.json 同一锚；ASTROCS_DESIGN §8.4 的 ABI 条款",
 "高（改对反而判红）：CHK-REGISTRATION-ANCHORS 的判据是「锚必须可解析」；把路径改错或删条目 ⇒ 锚不可解析直接判红。必须改成现行真实路径",
 "中——未跑门，锚解析失败是否已现网发生未裁"],

["eng/ci/ledgers/registration_anchor_ledger.json",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记1（同一陈旧路径 lib/astro_image_io/src/aio_abi.cpp 的第二处登记）",
 "是——本文件即 CHK-REGISTRATION-ANCHORS 的台账输入（ID 出处 eng/ci/checks.json）",
 "改注册：更新锚路径为现行；台账性质是「登记」，删除等于解除绑定，不该用",
 "eng/contracts/data/aio_abi_contract_v1.json",
 "高：删条目会让该锚从台账消失 ⇒ 若门核「台账覆盖全部注册锚」则漏项判红",
 "中"],

["eng/contracts/data/phase2_uncertainty_rejection_provenance_v1.json",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记2（lib/astro_image_io/include/aio_hips.h ＋ lib/astro_image_io/src/hips/aio_hips_writer.cpp，两者均不在跟踪集）",
 "是——合同数据面；被 eng/contracts/ 合同校验族读取（CON-CONTRACTS/合同 schema 门族，ID 出处 eng/ci/checks.json 的 eng/contracts/** changed_paths）",
 "先解引用再删：两个路径名换成现行实现路径（现行为 lib/infrastructure/aio/io/hips_core.c 与 lib/infrastructure/aio/src/ahpx/ 三件），不可删条目",
 "本清单 AUD-404 行 51-53（ahpx 三件的「仅测试编译」档）——改锚会把它们的定位一并澄清",
 "高：该 JSON 是「不确定性/拒绝溯源」合同的锚面，删条目 = 该合同条款失去实现载体 ⇒ 合同门判红",
 "中"],

["lib/include/astrocs/core/executor.h:22",
 "登记面残留",
 "不在生产 target",
 "生产1(本行注释)/测试0/文档0/登记0（命令：git grep -nw -e 'lib/core/src/executor.cpp' -- lib => 1 行）",
 "否——纯注释指针；但其指向的实现 lib/infrastructure/scheduler/src/executor.cpp 属「仅被测试 target 编译」档（见 AUD-404 行 56），本行是「该头有实现」的唯一文字凭据",
 "改写：路径改成 lib/infrastructure/scheduler/src/executor.cpp；本行还声明「本头为 RT-004 冻结合同」，须与 RT-004 条款核对后再定",
 "无",
 "低：注释不被符号可解析判据（.h 只喂 token，不喂路径）；但若 CHK-DANGLING 也解析注释里的路径，改错方向会判红",
 "中"],

["lib/infrastructure/cli/commands.cpp:548",
 "登记面残留",
 "不在生产 target",
 "生产1(本行注释)/测试0/文档0/登记0（命令：git grep -nw -e 'eng/eng/' -- lib => 1 行）",
 "否——注释里的路径拼写错（双 eng 前缀），git ls-files eng/eng => 0；真实文件 eng/tools/quality/gen_run_graphs.py 在跟踪集",
 "改写：去掉重复 eng/ 前缀，改成 eng/tools/quality/gen_run_graphs.py",
 "无",
 "低；但不改 ⇒ 生产 CLI 源里留着一个永远不可能存在的路径，读码者会以为该可选步骤恒不触发",
 "高"],

["lib/infrastructure/aio/third_party/cfitsio/win_compat/unistd.h:1",
 "登记面残留",
 "不被任何 target 编译",
 "生产1(文件头自述路径)/测试0/文档0/登记0（命令：git grep -nw -e 'lib/astro_image_io' -- lib => 1 行，命中自身文件头）",
 "否——vendored 第三方文件头自述路径陈旧（改名前 lib/astro_image_io/third_party/…）",
 "保留并说明理由：vendored 第三方不随本仓改名规整（标准 04 §1 要求第三方集中在 third_party/ 并记许可证）；只在文件头加一行「本仓现路径为 …」即可，不改第三方正文",
 "无",
 "低",
 "高"],

["eng/tools/quality/contracts/check_api_contracts.py:20",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记2（本行读 docs/architecture/api_inventory.json；该 JSON 不在跟踪集，真身是 .csv）",
 "是——本脚本是 CON-API-CONTRACTS 的 command（ID 出处 eng/ci/checks.json）；其 :20 的 api_inventory.json 被注释为 「optional cached extract」",
 "先解引用再删：把指针改成 .csv 或直接删该 optional 分支；本条已被 eng/tools/doccheck/dangling_ledger.json 显式登记（token=docs/architecture/api_inventory.json，owner=BLD-401，classification=「历史/退役路径登记面」）",
 "eng/tools/doccheck/dangling_ledger.json 对应条目（修好即回收一条，缓解饱和）",
 "中：optional 分支缺失 ⇒ 该侧比对静默跳过 = fail-open；改成 .csv 会**新开启**一条比对，可能立刻判红（inventory 与 API_CONTRACTS 计数当前是否相等未核）",
 "高"],

["lib/infrastructure/benchmark/cpu/avx512/include/astrocs/cpu/avx512_provider_v1.h:16-17",
 "未跟踪产物名",
 "不被任何 target 编译",
 "生产1(本头两处指针)/测试0/文档0/登记0（命令：git ls-files artifacts/evidence/prerelease-v5 => 3 个文件：ISA-001/002/003/MEASUREMENTS.csv；ISA-004 不在跟踪集）",
 "否——门不读本头；但同类指针在 docs/architecture/ISA_VARIANTS.md 中被 eng/tests/backend/test_isa_avx512.py:94 以 assertIn('MEASUREMENTS.csv', doc) **钉住**，即文档侧不可删该指针",
 "加统一退役标注（本头属未被编译的 provider 侧，见 AUD-404 行 45）：把「热点 profile 台账 = ISA-004 实测」改写为如实口径——ISA-004 工件由 eng/tests/backend/test_isa_avx512.py:76-77 现场生成、不入库，与 ISA-001..003 已入库不同",
 "docs/architecture/ISA_VARIANTS.md（被 test_isa_avx512.py:94 断言，禁删）；eng/tests/backend/test_isa_avx512.py（未在 checks.json 注册为门 command）",
 "高（证据面不对称）：ISA-001..003 入库而 ISA-004 不入库，说明 avx512 的实测台账**当前不在仓库里**；直接删本头会让该结论彻底失去线索，而它又是 §8.4/ISA 条款的唯一指向",
 "中"],

["lib/infrastructure/pipeline/module_loader/secure_loader.c",
 "占位模块",
 "不被任何 target 编译",
 "生产1/测试4/文档3/登记2（命令：git grep -ln secure_loader => 28 文件；其中 eng/tests/abi/ 4 个 pytest 以 cc 现场编译：test_secure_loader.py:225、test_module_registry.py:131、test_abi005_echo.py:223、mod001_install_load_check.py:112）",
 "是——ASTROCS_DESIGN §8.4 指定的唯一 loader 实现；且 eng/ci/ledgers/aio_io_boundary_inventory.json:1926 登记本路径（门 CHK-AIO-IO-BOUNDARY，ID 出处 eng/ci/checks.json）、eng/ci/ledgers/prod_wiring.json:709 记「类 B 处置：属 C ABI 动态装载通道（ABI-003 loader）」",
 "保留并说明理由（**不许按死代码删**）：它是 ABI-003 合同的唯一实现与唯一测试载体；整改动作应是「进构建图」（给独立 add_library 或登记进 orchestrator 的装载器 target），而不是删除",
 "若进图：eng/cmake/install_layout.cmake 安装面、docs/architecture/abi/ABI_003_SECURE_LOADER.md、eng/ci/ledgers/{aio_io_boundary_inventory,prod_wiring}.json、abi003_loader_probe.c",
 "高：删它 ⇒ 4 个 abi pytest 现场 cc 失败（改对反而判红的典型：把「没进构建图」误读成「死代码」）",
 "高"],

["lib/infrastructure/pipeline/module_loader/module_registry.c",
 "占位模块",
 "不被任何 target 编译",
 "生产1/测试4/文档3/登记1（同上一条命令族：eng/tests/abi/{test_module_registry.py:136,test_abi005_echo.py:264,mod001_install_load_check.py,test_abi005_echo.py} 现场 cc）",
 "是——ABI-004 registry 唯一实现；eng/ci/ledgers/aio_io_boundary_inventory.json:1910 登记；eng/ci/ledgers/prod_wiring.json:720 类 B 处置",
 "保留并说明理由＋改注册（进构建图）；与 secure_loader.c 同一批处置",
 "docs/architecture/abi/ABI_004_*（如存在）、eng/ci/ledgers 两条、abi004_registry_probe.c",
 "高：同上，删之必红",
 "高"],

["lib/infrastructure/benchmark/cpu/baseline/src/baseline_provider.cpp",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（复核：git grep -nw -e baseline_provider.cpp -- CMakeLists.txt eng/cmake eng/tests eng/ci => 0 命中；根 CMakeLists 只编 backend_host/*_backend.cpp）",
 "否——未被任何 CMake 源清单、门或合同命名",
 "删除（并补 ISA provider 侧的构建接线，若产品仍要 CPU 变体实测）",
 "若产品要保：需新增 add_library 并让 benchmark profile 装载；若不要：连同 avx2/avx512 provider 与 capability_detect.c 四件一起删，并清理 docs/architecture/ISA_VARIANTS.md 与 eng/tests/backend/test_isa_*.py 三个测试",
 "高：docs/architecture/ISA_VARIANTS.md 被 eng/tests/backend/test_isa_avx512.py:94 断言含 MEASUREMENTS.csv 串 ⇒ 只删 provider 不删文档没事，但**反过来**（清文档不接线）会判红；另 UT-ABI 门族对改名敏感（已裁：改名半贯穿造成 UT-ABI 恒红）",
 "中——是否仍属「待接线的实现」需产品面裁决，故给「删除＋备选」两条"],

["lib/infrastructure/benchmark/cpu/avx2/src/avx2_provider.cpp",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档1/登记0（同族命令；docs/architecture/cpu/CPU_003_AVX2_PROVIDER.md 以其为描述对象）",
 "否——CMake/门/合同三面 0 引用；但其头 lib/infrastructure/benchmark/cpu/avx2/include/astrocs/cpu/avx2_provider_v1.h 引 ISA-001/MEASUREMENTS.csv（**已入库**）",
 "删除（与 baseline_provider.cpp 同批），或改注册进独立构建 target",
 "docs/architecture/cpu/CPU_003_AVX2_PROVIDER.md 需同步为「设计件/未接入」",
 "中：文档门（DOC 族）若核「文档声明的实现文件必须存在」⇒ 删 .cpp 而不改文档会判红",
 "中"],

["lib/infrastructure/benchmark/cpu/avx512/src/avx512_provider.cpp",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档1/登记0（其 :8 区引 ISA-004/MEASUREMENTS.csv，该工件不在跟踪集）",
 "否——三面 0 引用；avx512_backend.cpp（**在产**，target astrocs_cpu_avx512）是它的 host 壳，二者不互相编译",
 "删除，或改注册进 astrocs_cpu_avx512 的源清单（须先确认 ABI 与 PIC/version-script 约束）",
 "lib/infrastructure/benchmark/backend_host/avx512_backend.cpp（在产壳）的 dlopen 目标名；docs/architecture/ISA_VARIANTS.md",
 "高：删 provider 而在产壳仍按名字找它 ⇒ 运行期找不到后端；这是「壳在产、体不在图」的成对件，必须同批处理",
 "中"],

["lib/infrastructure/benchmark/cpu/common/src/capability_detect.c",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（同族命令 0 命中）",
 "否",
 "删除；若 backend_host 三个壳需要能力探测，改为把该 TU 编进 astrocs_cpu_* 三 target 之一",
 "lib/infrastructure/benchmark/backend_host/{baseline,avx2,avx512}_backend.cpp（三壳在产，根 CMakeLists 列出）",
 "中：壳若在运行期依赖其符号 ⇒ 删后 dlopen 失败；须读三壳是否自带探测实现",
 "中"],

["lib/infrastructure/benchmark/backend_host/avx_backend.cpp",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（根 CMakeLists 只列 baseline/avx2/avx512 三壳，不含 avx_backend.cpp）",
 "否",
 "删除",
 "无",
 "低：同目录三壳在产、本文件是第四种 ISA 变体的壳且无人列 ⇒ 删之不碰在产面",
 "高"],

["lib/infrastructure/aio/src/aio_pipeline_engine.cpp",
 "重复实现",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记1（eng/ci/ledgers/aio_io_boundary_inventory.json 族；aio 全域被 CHK-RETIRED-CODE 以 AIO_WHITELIST_PREFIX 白名单排除扫描）",
 "部分——门 CHK-AIO-IO-BOUNDARY（ID 出处 eng/ci/checks.json）以 aio 清单为输入；本 TU 是第二套 PipelineFrame 的实现体（与 lib/infrastructure/aio/include/aio_pipeline.h 族并存）",
 "先解引用再删：它承载 hp_drizzle_run 的第二套 PipelineFrame 语义；须先确认 hp_drizzle_api.cpp 的入参类型改指向哪一套，再删",
 "lib/algorithms/drizzle/healpix_drizzle/hp_drizzle_api.cpp 的 PipelineFrame* 入参（:400,:525,:1324 一带）；docs 的管线合同",
 "高：直接删会切断 hp_drizzle_api 的类型来源；且 aio 域被退役检查器白名单排除 ⇒ 删了也没有门会提醒，属静默风险",
 "中"],

["lib/algorithms/calibration/src/dark_optimizer.cpp",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（复核：git grep -nw -e dark_optimizer -- CMakeLists.txt eng lib/algorithms/calibration => 除自身外 0 命中）",
 "否——calibration 模块内无消费者，也无门/合同列名",
 "删除",
 "无（若它对应 docs 里某条 ALG 的声明实现，须先核 ALG 锚：本审查未在该 CSV 命中其符号名）",
 "低；但须先跑一次 CHK-SPEC-NAMED-IMPL 类门确认无 ALG 锚指它（禁跑脚本 ⇒ 留作开发节点核对项）",
 "中"],

["lib/infrastructure/acr/backends/cuda/bridge/acr_cuda_bridge_host.cpp",
 "占位模块",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（acr 独立子图的 108 个 TU 走 ALONE 档，本件连 ALONE 都不在）",
 "否——ACR 生产不可达是项目既定边界（最高设计：ACR 生产不可达），本件是 CUDA 桥宿主壳",
 "加统一退役标注：它属「等待接线的实现」，按 ENGINEERING_SPEC §2 保留则注释五字段登记（现无块 ⇒ 若前 40 行出现横幅 token 会触 R2；本件当前无 token ⇒ 不红，但按标准 04 §4 二选一仍应标注）",
 "lib/infrastructure/acr/backends/cuda/** 同族；acr 独立构建树说明",
 "低",
 "中"],

["lib/infrastructure/gaia_xpsd_client/example/demo.c",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（命令：git grep -nw -e 'example/demo.c' -- CMakeLists.txt eng lib => 0 命中）",
 "否——示例面，无门无合同",
 "删除（标准 04 §4「无任何引用的…示例/一次性脚本直接删除」）",
 "无；若 README 引用示例须同批改",
 "低",
 "高"],
]
