# -*- coding: utf-8 -*-
MODE = "append"
ROWS = [
["lib/algorithms/calibration/Makefile（MinGW 平行构建面；SRC_DIR=cpp，产物 cosmetic_corrector.dll）",
 "重复实现",
 "不被任何 target 编译",
 "生产1(其自身)/测试0/文档6/登记0（命令：git grep -n 「calibration/Makefile\\|cosmetic_corrector.dll」 => 18 行；其中 CMake 面 0 命中）",
 "否——无任何 CMake/门调用（git grep -n 「cpp/cosmetic_corrector」 -- '*.cmake' CMakeLists.txt => 0）。但 docs 三面把它登记为「遗留通道（不在本合同）」：docs/contracts/PUBLIC_API.md:174,:228；docs/algorithms/COSMETIC_ALGORITHMS.md:292-295（已逐条给退役理由）；docs/algorithms/CALIBRATION_ALGORITHMS.md:325,:607",
 "删除（连同下一行的 cpp/ 分叉）：标准 04 §4:41 一次性过程脚本不留生产目录；本仓根 CMakeLists.txt:4 明令「禁 GLOB (QA-002)」且以 CMake 为唯一构建事实源 ⇒ 一个手写 Makefile 是**第二套构建事实源**",
 "PUBLIC_API.md:174,:228 与 COSMETIC_ALGORITHMS.md:42,:292-295 的「遗留通道」条目（删后可整段清，不留历史叙述）；lib/algorithms/calibration/README.md:150-155（已自陈「旧 README 记载失效」）",
 "中：产物 dll 在当前树不存在（COSMETIC_ALGORITHMS.md:295 实测），且 lib/algorithms/calibration/memory.md:209 还记有 Python 侧 _load_cpp_dll() 加载路径 ⇒ 若有测试按该路径找 dll 会**静默跳过**（找不到即不测），删 Makefile 不红但要看清那处是否 fail-open",
 "高"],

["lib/algorithms/calibration/cpp/{cosmetic_corrector.cpp, cosmetic_corrector.h}（338 行；同能力另一份在 src/cosmetic_corrector.cpp 780 行）",
 "重复实现",
 "不被任何 target 编译",
 "生产2/测试0/文档4/登记0（命令：git hash-object 两份 ⇒ 5e2fcf23 与 c1fe80ee，**内容不同**；git ls-files lib/algorithms/calibration/cpp => 2 文件；git grep -n 「cpp/cosmetic_corrector」 -- CMakeLists.txt lib/*/CMakeLists.txt => 0）",
 "否——CMake 面零命名；仅被上一行的 Makefile 命名。**订正 AUD-401 机器表**：source_prod_membership_v2.tsv 把 cpp/cosmetic_corrector.cpp 记为 PROD（CAL_PROD_SOURCES;COS_PROD_SOURCES;astrocs_calibration），本审查独立复核为 0 命名 ⇒ 该行档应改判 ORPHAN",
 "删除：标准 04 §3:33「同一能力只有一份实现；重复实现保留一份、其余按退役处置」。保留 src/ 那份（astrocs_calibration 与 lib/algorithms/cosmetic/CMakeLists.txt:43 都指它）",
 "lib/algorithms/calibration/memory.md:229（以 cpp/ 路径记述实现锚，须改指 src/）；问题台账 FIX_LEDGER.csv:620 M6a-I-004「遗留 cc_* 通道的同名分叉实现不带 legacy 标记」OPEN 状态可随之解除",
 "高（若反向删）：删 src/ 那份会让 astrocs_calibration 与 cosmetic 两个生产 target 同时缺源；删 cpp/ 才安全。同名是最危险的误删诱因",
 "高"],

["其余 11 个 lib/**/Makefile：drizzle/healpix_drizzle、noise_snr/cpp、photometry/cpp、platesolve/cpp/ipv、psf、shared、star_detection、infrastructure/aio、infrastructure/aio/healpix_db/archive/legacy/healpix_stack、infrastructure/gaia_xpsd_client、infrastructure/pipeline/orchestrator/cpp（另有 hips_browser/healpix_browser_qt/Makefile）",
 "模板复制残留",
 "不被任何 target 编译",
 "生产0/测试0/文档3/登记0（命令：git ls-files 「lib/**/Makefile」 | wc -l => 13；根 CMakeLists.txt:4 禁 GLOB 且构建事实源为 CMake）",
 "否——CMake 与门均不调用；其中 orchestrator 与 hips_browser 两个属 ALONE 档（自身有独立 CMakeLists），其 Makefile 是迁移期残留",
 "分组处置：archive/legacy/healpix_stack/Makefile 随归档目录同批删；orchestrator/hips_browser/aio 三个的 Makefile 若其独立构建树仍被文档指向 ⇒ 加统一退役标注（写明保留原因与删除条件）；其余按「一次性过程脚本」删",
 "删每个前须跑一次 git grep -l 「<该目录名>/Makefile」（本审查未逐个跑，属待证项）",
 "中：这批是**平行的第二构建面**，留着就会与 CMake 漂移（同一模块两套编译选项）；但 orchestrator/hips_browser 确有独立构建需求，不能一刀切",
 "中——13 个 Makefile 的逐个调用面未全核，缺「每个是否被文档或脚本指向」"],

["lib/algorithms/{drizzle/healpix_drizzle,shared/healpix}/healpix_core.cpp（另有第三份在 aio/healpix_db/archive/legacy/healpix_stack/）",
 "重复实现",
 "已退役",
 "生产3/测试2/文档1/登记0（命令：git ls-files 三份路径各 1；drizzle 那份的第 1 行即合规 RETIRED-CODE-RETAINED 块）",
 "部分——drizzle/healpix_core.cpp 与 .h 各带 RETAINED 块（见 AUD-404 行 89）⇒ 它已按 §4 第二种状态登记；archive 那份随目录删；shared 那份是现行共用件",
 "不许删 shared/ 那份（它是 HEALPix 几何的共用来源）；drizzle/ 那份按其 RETAINED 块的 EXIT 条件处理；archive 那份随 healpix_db 目录同批删",
 "lib/algorithms/drizzle/healpix_drizzle/{healpix_core.cpp,healpix_core.h} 的 EXIT 字段",
 "高（三份同名极易删错）：同名 healpix_core.cpp 分散三处，其中一处是共用件；按文件名批量操作必错",
 "中"],

["lib/infrastructure/pipeline/orchestrator/cpp/src/checkpoint.cpp 与 lib/infrastructure/scheduler/src/checkpoint.cpp",
 "重复实现",
 "不被任何 target 编译",
 "生产2/测试0/文档1/登记0（命令：git grep -cw -e checkpoint.cpp -- CMakeLists.txt lib => 各自归属判定；orchestrator 子图属 ALONE 档）",
 "部分——orchestrator 侧在其**独立** CMakeLists（根 add_subdirectory 闭包外）⇒ 机器表判 ALONE 而非 ORPHAN；scheduler 侧在 astrocs_core 族",
 "保留并说明理由：两份分属两套构建事实源（根图与 orchestrator 独立树），不是同图内的重复实现；标准 04 §3 的「只有一份实现」应在**同一构建闭包内**解释，否则判错处置",
 "无",
 "高（档写错即处置错）：把它们当「重复实现删一份」会同时打断 orchestrator 独立构建与根图生产面",
 "高"],

["lib/infrastructure/acr/{topology/cpu_features.cpp, utilization/memory_budget.cpp, core/runtime.cpp} 与 lib/infrastructure/{benchmark/backend_host/cpu_features.cpp, scheduler/src/memory_budget.cpp, scheduler/src/runtime.cpp}",
 "重复实现",
 "不被任何 target 编译",
 "生产6/测试0/文档2/登记0（命令：git ls-files 六路径各 1；acr 侧 108 TU 全在 ALONE 档）",
 "部分——ACR 生产不可达是最高设计既定边界，且根 CMakeLists.txt:972 明写「薄 CLI (显式链接各库; 无 GLOB; ACR 不链)」",
 "保留并说明理由：同名不同域（ACR 资源侧 vs 调度器侧），且 ACR 面按设计不进生产链接；不是死码也不是重复实现",
 "无",
 "高：这是最容易被「同名即重复」规则误杀的一类；本审查据此把「同能力」限定为同构建闭包内同语义",
 "高"],

["lib/algorithms/{calibration,cosmetic,drizzle,drizzle/hips,noise_snr}/src/module_entry.cpp（5 份）",
 "模板复制残留",
 "不在生产 target",
 "生产5/测试0/文档1/登记0（命令：git ls-files 「lib/algorithms/*/src/module_entry.cpp」 => 5；机器表 5 条均 PROD）",
 "是——五份都是各模块的 descriptor/工厂入口，被生产 target 编译；其中三份被 lib/algorithms/*/CMakeLists.txt 显式列出",
 "保留并说明理由：module_entry.cpp 是本仓的**模块入口命名约定**（一模块一入口），不是模板复制残留；标准 04 §3:32「每个模块有唯一职责与清晰端口」正是它承载的",
 "无",
 "高（若误判为模板残留批量删 ⇒ 五个模块的注册入口全断）；入表目的是给开发节点一个「这类不要动」的正面名单",
 "高"],

["lib/algorithms/coverage/src/cuda_bridge_stub.cpp",
 "占位模块",
 "不在生产 target",
 "生产1/测试0/文档1/登记0（命令：git grep -cw -e cuda_bridge_stub -- lib eng CMakeLists.txt；机器表 PROD / astrocs_phase2）",
 "是——在 astrocs_phase2 生产源清单内 ⇒ 已进生产二进制",
 "保留并说明理由：GPU 桥的 CPU 侧桩件，用于在无 CUDA 平台（本仓正式平台是 Windows x64 与 Linux amd64 纯 CPU 生产）保持符号存在；删之 ⇒ astrocs_phase2 链接期缺符号",
 "无",
 "高（「stub」这个名字极易被当占位删）：它是纯 CPU 生产面的**必需桩**，不是未完成实现",
 "高"],

["lib/algorithms/upm/{module.yaml, README.md, memory.md}（模块目录内无任何源文件）",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档2/登记2（命令：git ls-files lib/algorithms/upm => 3 文件 0 源；实现物理位于 lib/algorithms/coverage/src/{upm.cpp,sampler.cpp,rejection.cpp}）",
 "是——module.yaml 是登记面且被 CHK-REGISTRY-IR-PARITY/CHK-REGISTRATION-ANCHORS 读取（ID 出处 eng/ci/checks.json）；其 :138 自记 legacy_paths=「lib/algorithms/coverage upm sources」",
 "保留并说明理由：module.yaml 是模块身份的正本登记（不能因「目录无源」就删）；整改方向是把 module.yaml:85 的注释性符号列表与 :110-115 的「已撤下符号」叙述收敛，或把目录与实现对齐",
 "本清单行 22-23（同符号的 README/memory 残留）；docs/modules/registry/astrocs.phase2.upm-{apply,fit}.md",
 "高：module.yaml:110-115 已**正确**把退役符号从 source_symbols 撤下并写明退出条件——这是全仓唯一处理规范的例子；反倒是 prod_wiring_baseline.json:192 的 manifest.source_symbols 条目已成陈旧冻结（见行 24）",
 "高"],

["lib/infrastructure/{benchmark,hips_browser,observability,pipeline}/PENDING.md（4 份）",
 "退役未清理",
 "不被任何 target 编译",
 "生产0/测试0/文档4/登记0（命令：git ls-files | grep -c PENDING.md => 4）",
 "否——门不读 PENDING.md；但 DOCUMENT_INDEX/文档面检查可能把它当 docs 面外文件",
 "改注册：过程性「待办」台账不留在 lib/ 生产树（标准 04 §4:41）；其内容若仍有效应进 docs/KNOWN_LIMITATIONS.md 或对应工单，若已失效直接删",
 "各目录 README 若指向 PENDING.md 须同步",
 "低（对门）；中（对读者）：lib/ 下留「待办」文件＝把过程状态混进代码树，且与「文档内禁历史」口径冲突",
 "高"],

["eng/tests/backend/ 的 19 个 TU（abi_selftest_main.cpp, bench_candidates_main.cpp, bench_harness_main.cpp, candidates_probe_main.cpp, cheat_backend.cpp, fixture_backend.cpp, hips_properties_probe_main.cpp, kernel_bench_main.cpp, kernel_oracle_main.cpp, loader_probe_main.cpp, mon003_synthetic_main.cpp, p3_output_fsync_interposer.cpp, p3_output_fsync_probe.cpp, p3_output_probe_main.cpp, phase1_fixture_main.cpp, phase2_fixture_main.cpp, profile_gen_main.cpp, syn008_seam_main.cpp 等）",
 "占位模块",
 "不被任何 target 编译",
 "生产0/测试19/文档0/登记0（本审查独立普查：eng/ 面跟踪 TU 204 个，其中 46 个文件名不出现在 88 个跟踪 CMakeLists.txt/*.cmake 文本中；分布 backend 19／cpu 15／tools/quality 7／abi 3／validation 2）",
 "否——不经 CMake；但**被 pytest 现场编译**：复核 eng/tests/backend/test_bench_harness.py:36 直接以编译器吃 cheat_backend.cpp ⇒ 有测试消费者，不是无引用死码",
 "不许删（改注册）：四档字面是「不被任何 target 编译」，但处置必须是「接线进 CMake 或如实登记为运行期编译夹具」。本仓根 CMakeLists.txt:4 禁 GLOB、要求显式源清单 ⇒ 这批绕开构建事实源属**结构性缺口**",
 "若要接线：新增 add_executable/add_test ⇒ ctest 计数与红灯数台账（须附档位与 skip 计绿口径）需同步",
 "高（判反即错）：按「不被任何 target 编译」直删，会让现场编译它们的 pytest 由「能跑」变「文件不存在」，而多数 harness 会**静默跳过**缺失夹具 ⇒ 从「有测试」退化为「无测试仍绿」，这是最坏的 fail-open",
 "高"],

["eng/tests/cpu/{avx2,avx512,...} 的 15 个 TU（provider_avx2_capability_gate_test.c, provider_avx2_handshake_test.c, provider_avx2_oracle_main.cpp 等）",
 "占位模块",
 "不被任何 target 编译",
 "生产0/测试15/文档2/登记0（同族普查；复核 eng/tests/cpu/avx2/run_provider_avx2_checks.py:41 以运行期编译吃 provider_avx2_capability_gate_test.c）",
 "否——不经 CMake；被 run_provider_avx2_checks.py 现场编译，且其结论被 docs/architecture/cpu/CPU_003_AVX2_PROVIDER.md:79,:139 当作「ALL PASS」证据引用",
 "不许删（改注册）：它们是 CPU provider 的门面证据；而**其被测对象**（lib/infrastructure/benchmark/cpu/** 的 4 个 provider TU，见 AUD-404 行 44-47）却不被任何 target 编译 ⇒ 形成「测试现场编、被测件不在图」的双层错位",
 "lib/infrastructure/benchmark/cpu/** 四件；docs/architecture/cpu/CPU_003_AVX2_PROVIDER.md",
 "高（与行 44-47 互为因果）：若先删 provider 侧 ⇒ 这些测试与文档证据同时失去对象，但门不会红（因为它们不在 checks.json 的门面上）⇒ 静默失去 CPU 变体的全部证据",
 "高"],

["eng/tests/abi/{abi002_lifecycle_probe.c, abi003_loader_probe.c, abi004_registry_probe.c}",
 "占位模块",
 "不被任何 target 编译",
 "生产0/测试3/文档2/登记0（同族普查；abi003/004 分别对应 secure_loader.c / module_registry.c 的探针）",
 "否——不经 CMake；与 AUD-404 行 42-43 的 loader/registry 两件同源，由 eng/tests/abi/*.py 现场 cc",
 "不许删：它们与 secure_loader.c／module_registry.c 构成 ABI-003/004 合同的**唯一**验证面（行 42-43 已判「不许删」），删探针等于解除 ABI 验证",
 "lib/infrastructure/pipeline/module_loader/{secure_loader.c, module_registry.c}；docs/architecture/abi/ABI_003_SECURE_LOADER.md",
 "高",
 "高"],

["eng/tools/quality/ 的 7 个 TU ＋ eng/tests/validation/ 的 2 个 TU",
 "待证",
 "不被任何 target 编译",
 "生产0/测试9/文档0/登记0（本审查普查命中的文件名集，见复算件 eng_unnamed.txt）",
 "未裁——需逐个跑 git grep 其文件名在 eng/ci/checks.json 与 eng/tests 的调用面",
 "待证＋缺什么：缺「该 TU 是否被某 harness 运行期编译」的逐条判定；本表先登记不处置，避免误删",
 "待定",
 "中：未判定前不得删",
 "低"],

["lib/algorithms/calibration/src/v6_calibration_covariance.cpp:54 与 :680-706（PSFSW-RETIRE-01 退役对象拒绝面与「不是残留清理」的说明）",
 "退役未清理",
 "已退役",
 "生产2/测试2/文档3/登记3（本文件属 astrocs_v6_phase1_product / astrocs_v6_phase2_integrate / **p3_rsmp_retired_object_negative** 三 target）",
 "是——第三枚 target 名 p3_rsmp_retired_object_negative 就是「退役对象负例」门（复核：AUD-401 机器表 targets 列）；另有 CHK-PSFSW-RETIRED-STATIC（command=eng/ci/check_psfsw_retired.py）",
 "不许删：:680-682 逐字说明「删除即变成静默接受」，:706 是 fail-closed 拒绝路径；这是仓库自己写明的「不可删理由」",
 "无",
 "高（最高优先级不许删项之一）：源码注释本身就在防止后人把这段当残留清理",
 "高"],

["lib/algorithms/drizzle/healpix_drizzle/v6_drizzle_science.cpp:65 与 :93（PSFSW-RETIRE-03：原 RETIRED 占位行已物理删除 ＋ 退役对象显式拒绝段）",
 "退役未清理",
 "已退役",
 "生产2/测试3/文档2/登记3（同文件在 astrocs_v6_phase1_product / astrocs_v6_phase2_integrate / p3_rsmp_retired_object_negative）",
 "是——同上 p3_rsmp_retired_object_negative 负例 target ＋ CHK-PSFSW-RETIRED-STATIC",
 "不许删：:65 是「占位行已物理删除」的正面陈述（合规：不留历史叙述，只说明当前无该行），:93 起的显式拒绝段是判据本体",
 "无",
 "高",
 "高"],

["lib/algorithms/coverage/src/stage2_common.cpp:445（「该键既不能被设、也不能被读：出现即 fail-closed 拒绝（退役对象的…）」）",
 "退役未清理",
 "已退役",
 "生产1/测试1/文档1/登记1",
 "是——与 coverage.cpp:369-390 同一拒绝族；C-004.3 词表条款与 CHK-PSFSW-RETIRED-STATIC",
 "不许删：拒绝面",
 "无",
 "高",
 "高"],

["eng/contracts/data/v6_clause_registry_v1.json 的 weight_modes.retired 段（4 处 RETIRED 命中）",
 "登记面残留",
 "已退役",
 "生产0/测试1/文档1/登记4（复核：git grep -c RETIRED -- eng/contracts/data/v6_clause_registry_v1.json => 4；docs/contracts/PUBLIC_API.md:2175 明确以 #weight_modes.retired 为留痕锚）",
 "是——eng/contracts/data/ 是机器校验的合同数据面（唯一事实源，AGENTS §7）；被合同 schema 族门读取",
 "不许删：它是退役对象「接受面 = 空」这一裁决的**合同载体**；PUBLIC_API.md:2175 的作废标注正指向此处",
 "docs/contracts/PUBLIC_API.md:2175；docs/contracts/DATA_SEMANTICS.md §31.3",
 "高：删了即失去「该对象被显式拒绝」的机器凭据；负例门的判据要义正在此处",
 "高"],

["eng/contracts/schemas/{product_family_field_constraints.schema.json（3 处）, projection_registry.schema.json（2 处）}",
 "登记面残留",
 "已退役",
 "生产0/测试2/文档1/登记5",
 "是——JSON Schema 合同正本（eng/contracts/schemas/ 是 schema 唯一事实源）；product_family 面由 eng/tests/contracts/product_family/{field_constraints_oracle.py, test_field_constraints_integration.py} 消费",
 "不许删：schema 里的 retired 枚举值就是「显式拒绝」的机器形式",
 "field_constraints_oracle.py（8 处 RETIRED 命中，是 Oracle 面，被 CHK-RETIRED-CODE 以 *_oracle.py 排除规则豁免）",
 "高",
 "高"],

["eng/ci/{polarity_evidence.json（1 处）, polarity_probe.py（2 处）}",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记3",
 "是——极性证据面；polarity_evidence.json 属 eng/ci/ 的门证据输入族",
 "保留并说明理由：这是「判据极性」证据登记（防恒真门），与本项目「判据必须非退化」纪律直接对应；不属死码",
 "无",
 "高（删之会削弱「恒真门无证据资格」这一防线）",
 "中——未逐行读其 retired 命中是否确为极性登记"],

["docs/ci/01_CHECKS.md（5 处 RETIRED）",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档5/登记1（门说明面）",
 "是——本文件是门台账的**文档化说明**（与 eng/ci/checks.json 配对），被 CHK-DANGLING/文档一致性族核对",
 "先解引用再删：其中描述 CHK-RETIRED-CODE / CHK-PSFSW-RETIRED-* 的段落是这些门的对外说明；改门必须同批改此处",
 "eng/ci/checks.json；eng/ci/check_retired_code.py 文件头（两处口径须一致）",
 "中：文档与门定义分两处描述同一判据 ⇒ 属「口径唯一」违规，长期会漂移",
 "中"],

["eng/ci/check_no_weight_mode.py（1 处）与 eng/ci/check_no_weight_mode_code.py（5 处）",
 "退役未清理",
 "不被任何 target 编译",
 "生产0/测试2/文档1/登记6",
 "是——两脚本自身是门（NWM 族；复核 docs/ci/ 与 checks.json 的 no_weight_mode 条目族，含 --self-test 入口）",
 "不许删：它们是「权重模式退役」的**执行门**；其 retired 命中是拒绝面 token 表",
 "lib/algorithms/coverage/tests/weight_mode_retire_negative_test.cpp（配套负例）",
 "高：删门 = 退役对象回流无人拦，属最危险的一类「看起来是旧门其实正在守红线」",
 "高"],

["eng/ci/check_aio_io_boundary.py（2 处）与 eng/ci/ledgers/aio_io_boundary_inventory.json（9 处）",
 "登记面残留",
 "不被任何 target 编译",
 "生产0/测试0/文档1/登记11",
 "是——门 CHK-AIO-IO-BOUNDARY 及其清单台账（ID 出处 eng/ci/checks.json）；清单里逐条登记 lib/infrastructure/aio/** 的路径（含 AUD-404 行 42-43 的 secure_loader.c / module_registry.c）",
 "不许删：清单是该门的输入；本审查的 healpix_db／aio_pipeline_engine 判定即依赖其「登记了但不在图」的事实",
 "被登记路径自身（行 42-43、48、19-31）",
 "高：改清单不改编排 ⇒ 门与事实分离；删清单条目 ⇒ 该路径脱离边界核对（aio 全域又被 CHK-RETIRED-CODE 白名单排除）⇒ 双重失控",
 "中"],

["eng/tests/config/test_cfg004_unified_contract.py（2 处）与 eng/tests/contracts/test_unified_object_contract.py（14 处）",
 "退役未清理",
 "不在生产 target",
 "生产0/测试16/文档2/登记0",
 "是——C-004 统一对象合同的 pytest 面（coverage.h:89 明确「本头文件不得另造词表（C-004.3）」，其配对测试即此处）；test_unified_object_contract.py 的 14 处 retired 命中是「14→13 退役」这一数量断言",
 "不许删：它们是「退役对象数量 = 13」的机器断言载体；与 unified_object_compatibility_map_v1.json:133-143 互为凭据",
 "eng/contracts/data/unified_object_compatibility_map_v1.json:133-143",
 "高（典型「改对反而判红」）：新增任一退役对象 ⇒ 数量断言红；解除任一 ⇒ 也红。这是设计使然的强制同步，开发节点若不知道会误判为门坏",
 "高"],

["eng/tests/api/test_cli_protocol.py（2 处）与 eng/tests/integration/v6_p1/{EVIDENCE.md, oracle/v6_p1_reopen_oracle.py}（1/2 处）",
 "登记面残留",
 "不在生产 target",
 "生产0/测试5/文档1/登记0",
 "部分——CLI 协议测试是命令面合同（三命令划分）的验证；v6_p1_reopen_oracle.py 属 Oracle 面，被 CHK-RETIRED-CODE 的 */oracle/* 排除规则豁免",
 "不许删：命令面与 Oracle 面的判据载体；本表把它们的 retired 命中如实登记，供开发节点理解「删任何退役件前先看这两面是否断言它仍在」",
 "无",
 "中：Oracle 文件被检查器豁免 ⇒ 其内部历史对照不会被 CHK-RETIRED-CODE 判红，但也因此无人核对它是否已过期",
 "中"],
]
