# -*- coding: utf-8 -*-
MODE = "init"
CM = "git grep -nw -e %s -- lib docs eng CMakeLists.txt"

ROWS = [
["lib/algorithms/coverage/include/astro/phase2/upm.h:181",
 "退役未清理",
 "已退役",
 "生产2/测试0/文档16/登记7，计 25 行（命令：" + (CM % "p2_upm_normalized_weights") + "）",
 "是——CHK-DANGLING 步内 CON-DOC-SYMBOLS（ID 出处 eng/ci/checks.json，command=eng/tools/quality/contracts/check_doc_symbols.py）以 lib/**.h 文本构成「公开头语料」判符号可解析（见该脚本 _header_corpus 只 rglob('*.h')）；复核证明本行是该符号在 lib/**/*.h 中唯一存活文本",
 "先解引用再删：本行是文档侧 16 处引用的存活凭据，必须与 AUD-404 行 6-14 同批处理后才可删",
 "docs/contracts/PUBLIC_API.md:1806；docs/contracts/API_CONTRACTS.csv:280；docs/architecture/api_inventory.csv:325；docs/TRACEABILITY.csv:2；docs/algorithms/PHASE2_UPM_IMPL.md 三处；docs/algorithms/UPM_SOLVER.md:115；docs/science/PHASE2_UPM.md:272；docs/modules/ 三条；lib/algorithms/upm/{README.md,memory.md,module.yaml}",
 "高（改对反而判红）：单删本行 ⇒ 公开头语料不再含该 token ⇒ CON-DOC-SYMBOLS 对文档侧 16 处反引号引用全部判悬空。删注释必须晚于或同批于删文档",
 "高"],

["lib/algorithms/coverage/include/astro/phase2/upm.h:355",
 "退役未清理",
 "已退役",
 "生产2/测试0/文档1/登记1，计 4 行（命令：" + (CM % "p2_upm_ma_component_of_control") + "）",
 "是——同上 CON-DOC-SYMBOLS 唯一存活文本",
 "删除本行注释＋同批改 docs/contracts/PUBLIC_API.md:21",
 "docs/contracts/PUBLIC_API.md:21；eng/ci/prod_wiring_baseline.json:140",
 "中：PUBLIC_API.md:21 属该文件自陈「已删」段，与注释同批删即可；分两批会短暂判红",
 "高"],

["lib/algorithms/coverage/include/astro/phase2/sampler.h:133",
 "退役未清理",
 "已退役",
 "生产2/测试0/文档1/登记1，计 4 行（命令：" + (CM % "p2_sample_sky") + "）",
 "是——CON-DOC-SYMBOLS 唯一存活文本；另被 CHK-PROD-WIRING 棘轮基线冻结（eng/ci/prod_wiring_baseline.json:114）",
 "删除本行注释",
 "docs/contracts/PUBLIC_API.md:20（同文档自陈已删）；eng/ci/prod_wiring_baseline.json:114 收紧",
 "低：文档面仅自陈段一处，同批删即可",
 "高"],

["lib/algorithms/coverage/include/astro/phase2/sampler.h:135",
 "退役未清理",
 "已退役",
 "生产2/测试0/文档1/登记1，计 4 行（命令：" + (CM % "p2_sample_sky_cached") + "）",
 "是——CON-DOC-SYMBOLS 唯一存活文本",
 "删除本行注释",
 "docs/contracts/PUBLIC_API.md:20；eng/ci/prod_wiring_baseline.json:115",
 "低",
 "高"],

["lib/algorithms/coverage/include/astro/phase2/rejection.h:416",
 "退役未清理",
 "已退役",
 "生产2/测试0/文档2/登记1，计 5 行（命令：" + (CM % "p2_reject_stack_resolve_ex") + "）",
 "是——CON-DOC-SYMBOLS 唯一存活文本",
 "删除本行注释",
 "docs/algorithms/PHASE2_REJECTION.md:109（行锚表仍给 :2203-2217，指向已删定义）；docs/contracts/PUBLIC_API.md:21；eng/ci/prod_wiring_baseline.json:111",
 "中：PHASE2_REJECTION.md 的行锚须同批改，否则文档行锚门（eng/tools/doccheck/check_alg_line_anchors.py 族）指到不存在区间",
 "高"],

["lib/algorithms/coverage/src/upm.cpp:1999",
 "退役未清理",
 "已退役",
 "生产1(本条注释本身)/测试0/文档0/登记0（命令：git grep -nw -e p2_upm_normalized_weights -- lib/algorithms/coverage/src => 1 行）",
 "否——CON-DOC-SYMBOLS 的公开头语料只取 *.h，源文件不参与符号可解析判定，本行不在任何门输入面",
 "删除本行注释",
 "无",
 "低",
 "高"],

["lib/algorithms/coverage/src/upm.cpp:2849",
 "退役未清理",
 "已退役",
 "生产1(本条注释)/测试0/文档0/登记0",
 "否——同上，源文件不入符号可解析判据",
 "删除本行注释",
 "无",
 "低",
 "高"],

["lib/algorithms/coverage/src/sampler.cpp:1275",
 "退役未清理",
 "已退役",
 "生产1(本条注释)/测试0/文档0/登记0",
 "否",
 "删除本行注释",
 "无",
 "低",
 "高"],

["lib/algorithms/coverage/src/sampler.cpp:1277",
 "退役未清理",
 "已退役",
 "生产1(本条注释)/测试0/文档0/登记0",
 "否",
 "删除本行注释",
 "无",
 "低",
 "高"],

["lib/algorithms/coverage/src/rejection.cpp:2223",
 "退役未清理",
 "已退役",
 "生产1(本条注释)/测试0/文档0/登记0",
 "否",
 "删除本行注释",
 "无",
 "低",
 "高"],

["docs/contracts/PUBLIC_API.md:1806",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档1/登记1（同文件 :20-22 自陈该五条零消费者声明已删；本行仍逐字给出签名）",
 "是——本文件是对外接口合同正本；但 CON-API-CONTRACTS 不读本文件正文（check_api_contracts.py:19 只读 docs/contracts/API_CONTRACTS.csv），故无门拦住这一处自相矛盾",
 "删除 :1806 签名条目；:20-22 的变更叙述按标准 04 §5「注释/文档不含已撤销设计的历史叙述」一并清除",
 "docs/contracts/API_CONTRACTS.csv:280；docs/architecture/api_inventory.csv:325",
 "低：无门承载 ⇒ 删之不红；不删 ⇒ 同一文档一处说已删一处给签名",
 "高"],

["docs/contracts/API_CONTRACTS.csv:280",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档0/登记4（本行 1 ＋ 三份夹具各 1；命令：" + (CM % "p2_upm_normalized_weights") + " 中 eng/ 面 7 行）",
 "是——本行是 CON-API-CONTRACTS 的输入面本身（ID 出处 eng/ci/checks.json，command=eng/tools/quality/contracts/check_api_contracts.py；api_csv 见 :19）。该门以 AST 抽取签名比对，符号不在头内即产 API-SIG-NOREF(P1)（:128）；本行状态列仍写 VERIFIED",
 "先解引用再删：删本行前先取该门现网读数（本审查禁止运行 eng/**，未取），确认本行是已判红还是已被豁免",
 "eng/tools/quality/contracts/fixtures/check_api_contracts/{valid_min,invalid_sig_mismatch,invalid_missing_symbol}.csv 各 :320",
 "高：本行若被门冻结，删行改变 finding 集合；若已判红，删行才是修复。两读法都须以门实际读数裁定，故不能直删",
 "中"],

["docs/architecture/api_inventory.csv:325",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档0/登记1",
 "否——无门承载。复核：API-DOCS 的 command 是 eng/tools/check_api_docs.py（ID 出处 eng/ci/checks.json），而该脚本内不出现 api_inventory 或 PUBLIC_API（git grep -n 'api_inventory\\|PUBLIC_API' -- eng/tools/check_api_docs.py => 0 命中）；唯一读它的 eng/tools/api_doc_consistency.py:126,132 本身未注册为任何门的 command（git grep -rn api_doc_consistency -- eng/ci eng/tests => 0 命中）",
 "可直接删（与 PUBLIC_API.md:1806 同批更干净）：inventory 与 PUBLIC_API.md 由未注册工具对账，删一侧不会被门判红",
 "docs/contracts/PUBLIC_API.md:1806（对账另一侧，同批删以免人工差异）",
 "低：本行两面都无门承载；唯一风险是将来有人重新注册 api_doc_consistency.py 时两侧不同步",
 "高"],

["docs/TRACEABILITY.csv:2",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档0/登记3（本行 symbols 列 ＋ eng/tools/quality/v19r3_traceability.py:62 硬编码同串）",
 "是——追溯矩阵正本行；SCI-UPM-WEIGHT-001 的判据为 VERIFIED，其实现锚 symbols 列即本行（列内还含在产符号 p2_upm_raw_weight / p2_upm_build）",
 "先解引用再删：只从 symbols 列去掉退役 token，保留在产两个符号；改后须复跑追溯门",
 "eng/tools/quality/v19r3_traceability.py:62；docs/science/PHASE2_UPM.md:272；docs/algorithms/UPM_SOLVER.md:115",
 "高：整行删除会让 SCI-UPM-WEIGHT-001 失去实现载体 ⇒ 锚存活判红；只能改列内 token",
 "高"],

["docs/algorithms/PHASE2_UPM_IMPL.md:87",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档3(:61 :87 :182)/登记0",
 "是——文档行锚检查族（eng/tools/doccheck/check_alg_line_anchors.py；其陈旧夹具登记见 eng/tools/doccheck/dangling_ledger.json）核本行声明的 :1683-1702 区间，该区间已随定义删除失效",
 "先解引用再删：三处锚同批改",
 "docs/algorithms/UPM_SOLVER.md:115；docs/science/PHASE2_UPM.md:272",
 "中：现网该门是否已红未取读数（禁跑脚本），故列为先解引用",
 "中"],

["docs/algorithms/PHASE2_UPM_IMPL.md:61",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档1/登记0（同行含在产符号 p2_upm_raw_weight 的 upm.cpp:1650-1681 锚）",
 "是——同上文档行锚面",
 "改写而非删除：保留 raw_weight 半边与其锚，只去掉 normalized_weights 半边与 :1683-1710 锚",
 "无",
 "高：整行删除会连带丢掉在产符号的锚 ⇒ 自己制造新悬空",
 "高"],

["docs/algorithms/UPM_SOLVER.md:115",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档1/登记0",
 "是——F1 映射到符号并给测试锚 UPMW-001..003，锚与 docs/TRACEABILITY.csv:2 的 tests 列互为凭据",
 "改写：去掉退役符号，保留 raw_weight 绑定",
 "无",
 "低",
 "高"],

["docs/science/PHASE2_UPM.md:272",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档1/登记0（ALG-UPM-003 行同时列两符号）",
 "是——ALG-UPM-003 是算法锚，被追溯族与锚存活面引用（ID 出处 eng/ci/checks.json 的 CHK-REGISTRY-IR-PARITY / CHK-DANGLING 同族合同层）",
 "改写：去退役符号半边，ALG-UPM-003 仍由 p2_upm_raw_weight 承载",
 "无",
 "高：若把 ALG-UPM-003 整行删掉 ⇒ 该锚失去唯一实现载体 ⇒ 锚存活门判红",
 "高"],

["docs/modules/phase2_upm.md:144",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档3(本行＋registry upm-apply:92＋upm-fit:85)/登记0",
 "是——docs/modules/registry/* 由 CHK-REGISTRY-DOC-SYNC（ID 出处 eng/ci/checks.json，command=eng/ci/check_registry_doc_sync.py）核对；该门比的是模块 ID 还是符号级引用未取读数",
 "先解引用再删：三处同批；若该门只核模块 ID，三处可独立直删",
 "docs/modules/registry/astrocs.phase2.upm-apply.md:92；astrocs.phase2.upm-fit.md:85",
 "中：三处是同一段串行锚列表的复制，单改一处 ⇒ 文档间不一致",
 "中"],

["docs/modules/registry/astrocs.phase2.upm-apply.md:92",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档1/登记0",
 "是——CHK-REGISTRY-DOC-SYNC（ID 出处 eng/ci/checks.json）",
 "先解引用再删（与 :85 及 phase2_upm.md:144 同批）",
 "见上一行",
 "中",
 "中"],

["docs/modules/registry/astrocs.phase2.upm-fit.md:85",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档1/登记0",
 "是——CHK-REGISTRY-DOC-SYNC（ID 出处 eng/ci/checks.json）",
 "先解引用再删（与 :92 及 phase2_upm.md:144 同批）",
 "见上两行",
 "中",
 "中"],

["lib/algorithms/upm/README.md:127",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档3(README.md 2 行＋memory.md 1 行)/登记1(module.yaml:85)",
 "是——lib/**/module.yaml 属模块登记面：eng/ci/check_registration_anchors.py 与 CHK-REGISTRY-IR-PARITY（ID 出处 eng/ci/checks.json）以 module.yaml 锚为输入",
 "先解引用再删：README:127 的行锚 :1325 指向已删定义，须删；module.yaml:85 是注释性说明，改文即可",
 "lib/algorithms/upm/memory.md:57",
 "低：README/memory 非门输入面；module.yaml 改动须过 CHK-REGISTRY-IR-PARITY",
 "高"],

["lib/algorithms/upm/memory.md:57",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档1/登记0",
 "否——未在门输入面命中（同目录只有 module.yaml 在）",
 "删除该行或改写",
 "无",
 "低",
 "高"],

["eng/ci/prod_wiring_baseline.json:149",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档0/登记2（:149 header.P2_API 族 ＋ :192 manifest.source_symbols 族）",
 "是——CHK-PROD-WIRING 棘轮基线（ID 出处 eng/ci/checks.json；默认路径见 eng/ci/check_prod_wiring.py:1397 BASELINE_DEFAULT）。棘轮语义复核：只对新增判红（:1417 new），基线条目消失记 stale/resolved_since_baseline 不判红（:1418,:1481），--update-baseline 拒绝净增（:1468-1470）",
 "改注册：由前台跑 --update-baseline 收紧（本审查禁跑 eng/**，不代跑）。锚符号声明与定义均已撤 ⇒ 本条属陈旧冻结项",
 "无——收紧基线不需改他处",
 "中：门若以 token 文本可达性算 finding，则锚仍被 lib/**/*.h 的退役注释「喂活」，本条不算 stale；两种读法都指回「注释与登记面必须同批改」。未跑门 ⇒ 读数未裁",
 "中"],

["eng/tools/quality/v19r3_traceability.py:62",
 "登记面残留",
 "已退役",
 "生产0/测试0/文档0/登记1（硬编码串 \"p2_upm_raw_weight; p2_upm_build; p2_upm_normalized_weights\"）",
 "是——本脚本产追溯报告面，与 docs/TRACEABILITY.csv:2 同一符号串双写；未查到 checks.json 里有以本脚本为 command 的门（复核：git grep -n v19r3_traceability -- eng/ci/checks.json 无命中）",
 "改注册：去掉退役 token，与 docs/TRACEABILITY.csv:2 同批；因无门承载，删改本身不判红",
 "docs/TRACEABILITY.csv:2",
 "低：非门输入面；但双写不收敛会让下次对账人造差异",
 "高"],
]
