# -*- coding: utf-8 -*-
MODE = "append"
ROWS = [
["lib/infrastructure/aio/healpix_db/ （整目录，跟踪 42 文件）",
 "退役未清理",
 "不被任何 target 编译",
 "生产0/测试0/文档3/登记0（复核命令：git ls-files lib/infrastructure/aio/healpix_db | wc -l => 42；git grep -n healpix_db -- CMakeLists.txt => 0 命中，即无 CMake 源清单引用）",
 "否——整个目录不在任何 CMake 源清单、不在任何门的 changed_paths 或合同输入面（唯一命中是 eng/cmake/ARCH-001-migration-manifest.md 的迁移台账，与 eng/tests/quality/test_module_map.py 一类文档面核对）",
 "删除：标准 04 §4「历史控制包、一次性过程脚本、过期台账不留在生产目录」＋「归档留在生产目录」正是本项；ARCH-001 迁移台账已把 lib/healpix_db 标为 **DONE**，归档件留在 lib/ 生产树下",
 "eng/cmake/ARCH-001-migration-manifest.md:45,90（迁移台账行，删后应把该行的「产物已清」补注）；eng/packaging/launch/start_browser.ps1（见下一行）",
 "中：删整目录会让 ARCH-001 台账里「35 → DONE」的计数复核面（reports/v19r2 台账）不再可比；但 reports/** 非门输入，不判红",
 "高"],

["lib/infrastructure/aio/healpix_db/archive/legacy/healpix_stack/ 的 13 个翻译单元（ahps_reader.cpp, ahps_writer.cpp, hp_stack_api.cpp, hp_stack_hiss.cpp, simple_test.cpp, stack_db.cpp, stack_engine.cpp, gradient/{corrected_stacker,gradient_fitter,gradient_sampler,spherical_spline,test_gradient_sampler,test_snr_evaluator}.cpp）",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（复核：AUD-401 机器表 bucket=ORPHAN 的该 13 条；本审查独立复核 git grep -nw -e stack_engine.cpp -- CMakeLists.txt eng lib => 0 命中）",
 "否——但注意 CON-DOC-SYMBOLS 显式排除 archive：其 _header_corpus 里 `if 「archive」 in str(h): continue`，即 archive 下的头本来就不进符号判据面 ⇒ 删之不影响该门",
 "删除（连同上一行的目录级动作）；其中 simple_test.cpp / test_gradient_sampler.cpp / test_snr_evaluator.cpp 是**归档内的一次性自测**，标准 04 §4 直删",
 "无（archive 被检查器排除，无门无合同）",
 "低：唯一「看起来会被引用」的风险是文档行锚，实测 archive 路径在 docs 面 0 命中",
 "高"],

["eng/packaging/launch/start_browser.ps1:27 与 :43",
 "未跟踪产物名",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（复核：命令内路径为 lib\\healpix_db\\healpix_browser_qt\\build\\healpix_browser_qt.exe；git ls-files 「lib/healpix_db*」 => 0 文件，真身已在 lib/infrastructure/hips_browser/healpix_browser_qt/）",
 "否——该 .ps1 未被任何门引用（git grep -rn start_browser -- eng/ci 仅命中自身）",
 "改注册：把两处路径改成 lib\\infrastructure\\hips_browser\\healpix_browser_qt\\…；这是「启动脚本按已退役路径找 exe」⇒ 脚本必然走 :37 的「未找到则现场构建」分支，且构建目录也不存在",
 "eng/cmake/ARCH-001-migration-manifest.md:22（该迁移行标 DONE，但启动脚本未跟随）",
 "低（对门）／高（对功能）：不判红，但 Windows 平台的浏览器启动面实际是坏的；本条属「改了不红、不改则假可用」",
 "高"],

["lib/infrastructure/aio/third_party/cfitsio/{drvrgsiftp.c, iter_a.c, iter_b.c, iter_c.c, vmsieee.c, windumpexts.c, utilities/fitsverify.c}（7 文件）",
 "死代码",
 "不被任何 target 编译",
 "生产0/测试0/文档0/登记0（复核：对 7 个文件名逐个跑 grep -c 「<name>.c」 eng/cmake/cfitsio_sources.cmake => 全部 0；该白名单唯一名计数 = grep -oE 「[a-z0-9_]+\\.c」 | sort -u | wc -l => 60）",
 "否——但它们在 CHK-RETIRED-CODE 的扫描面之外：PRUNE_DIRS 含 third_party，故该门根本不扫此目录",
 "保留并说明理由：vendored 上游发行包内的**平台/驱动专用**文件（gsiftp 驱动、Iter 迭代器示例、VMS/Windows 端ian、fitsverify 独立工具），本仓按白名单裁剪是**设计选择**不是遗漏；标准 04 §1 要求第三方集中在 third_party/ 并记许可证，未要求逐文件编译",
 "无（若删：须同步 eng/cmake/cfitsio_sources.cmake 的裁剪说明，避免下次上游同步时误判为「上游少了文件」）",
 "中：删 vendored 未用文件会让「与上游发行包 diff」这一核对手段失效；上游同步时会产生假差异。建议保留但在 cfitsio_sources.cmake 注明「白名单=裁剪决定，非遗漏」",
 "高"],

["lib/infrastructure/observability/probes/src/probe.cpp",
 "死代码",
 "不在生产 target",
 "生产0/测试1/文档0/登记0（唯一编译者：根 CMakeLists.txt:443-445 的 astrocs_probes，处于 if(ASTROCS_PROBES) 内；option 默认 OFF，见 CMakeLists.txt:26）",
 "是——OFF 分支在 :458 提供 astrocs_probes INTERFACE 替身，:645 把它列入链接面 ⇒ target 名不可消失；另 ASTROCS_PROBE_LOG 运行期门相关",
 "保留并说明理由：默认 OFF 的可选探针实现，属设计选择；不是死代码。若加退役标注反而误导（它随时可 ON 编译）",
 "无——OFF 时 INTERFACE 替身保证链接面不破",
 "高（若误删）：删 probe.cpp 而 astrocs_probes 的 STATIC 分支还在 ⇒ ASTROCS_PROBES=ON 的配置直接构建失败，而默认构建（OFF）仍是绿的 ⇒ 只有开探针的门/实验会红，属最难发现的破坏形态",
 "高"],

["lib/infrastructure/aio/src/ahpx/aio_ahpx_api.cpp",
 "占位模块",
 "不在生产 target",
 "生产0/测试1/文档1/登记1（唯一编译者 eng/tests/unit/CMakeLists.txt:1396-1403 的 ahpx_hips_format_test，用 target_sources 注入；登记面：eng/ci/checks.json 的门 AHPX-WEIGHT-RETIRED）",
 "是——门 ID **AHPX-WEIGHT-RETIRED**（ID 出处 eng/ci/checks.json；command = eng/tools/quality/deep_ci_driver.py ctest-target --target ahpx_hips_format；ctest_targets=[「ahpx_hips_format」]，changed_paths=[「lib/infrastructure/aio/**」,「eng/tests/unit/**」,「CMakeLists.txt」]）。该门名本身即「RETIRED」，说明 AHPX 权重面是**被登记为退役但仍在测试面承载**的对象",
 "不许删（改注册）：它是 AHPX-WEIGHT-RETIRED 这条门的唯一被测实现载体；删它 = 该门失去对象，门要么恒绿（找不到 target 即 SKIP）要么构建红。正确动作是把它纳入 astrocs_aio 生产源清单（CMakeLists.txt:535）或按标准 04 §4 加统一退役标注并同步撤门",
 "CMakeLists.txt:535（astrocs_aio 生产源清单）；eng/ci/checks.json 的 AHPX-WEIGHT-RETIRED 条目；eng/tests/unit/CMakeLists.txt:1396-1403",
 "高：这是本清单最典型的「改对反而判红」——门名带 RETIRED 容易让人以为实现可随手删，实际它是该门唯一的执行对象",
 "高"],

["lib/infrastructure/aio/src/ahpx/aio_ahpx_reader.cpp",
 "占位模块",
 "不在生产 target",
 "生产0/测试1/文档1/登记1（同上，同一 test target）",
 "是——AHPX-WEIGHT-RETIRED（ID 出处 eng/ci/checks.json）",
 "不许删（与 api/reader/writer 三件同批改注册）",
 "同上",
 "高：三件互为依赖，删任一件都使该测试 target 编译失败 ⇒ 门红",
 "高"],

["lib/infrastructure/aio/src/ahpx/aio_ahpx_writer.cpp",
 "占位模块",
 "不在生产 target",
 "生产0/测试1/文档1/登记1（同上）",
 "是——AHPX-WEIGHT-RETIRED（ID 出处 eng/ci/checks.json）",
 "不许删（三件同批）",
 "同上",
 "高",
 "高"],

["lib/infrastructure/aio/io/hips_core.c",
 "占位模块",
 "不在生产 target",
 "生产0/测试1/文档1/登记0（唯一编译者 w34_hips_core_selftest，eng/tests/unit/CMakeLists.txt:1691）",
 "是——该 selftest 由 ctest 注册；未在 checks.json 找到以其为 command 的门（复核：git grep -n w34_hips_core -- eng/ci/checks.json => 0 命中）⇒ 门面无承载，但测试目标面有",
 "先解引用再删：它承载 HiPS 核心 I/O 的实现语义；要么进 astrocs_aio 生产源清单，要么按标准 04 §4 加统一退役标注并把 w34 selftest 一并撤下",
 "eng/tests/unit/CMakeLists.txt:1691；docs 的 HiPS 产品合同面",
 "中：删 .c 而 selftest 还在 ⇒ 该测试 target 编译失败（ctest 红），属可发现的破坏",
 "高"],

["lib/algorithms/projection/p3_projection.cpp",
 "占位模块",
 "不在生产 target",
 "生产0/测试2/文档1/登记0（编译者：p3_projection_test 于 eng/tests/unit/CMakeLists.txt:1424-1426；v6_p3_proj_legacy_probe 于 eng/tests/unit/v6_p3_proj/CMakeLists.txt:46）",
 "是——两个测试 target；另 lib/algorithms/projection/CMakeLists.txt 只声明 p3_wcs.cpp ⇒ 本 TU 被生产源清单**显式排除**",
 "先解引用再删：本文件是「旧投影实现」，与 p3_proj_v6.cpp 构成同域重复实现（见下两行）；按标准 04 §3「同一能力只有一份实现；重复实现保留一份、其余按退役处置」处置",
 "eng/tests/unit/CMakeLists.txt:1424-1426；eng/tests/unit/v6_p3_proj/CMakeLists.txt:46（legacy probe 本身即「退役探针」）；lib/algorithms/projection/CMakeLists.txt",
 "高：v6_p3_proj_legacy_probe 这个 target 名就表明它在**守旧实现**；删实现而留探针 ⇒ 探针失去对象或编译红。二者必须同批",
 "高"],

["lib/algorithms/projection/p3_proj_v6.cpp",
 "占位模块",
 "不在生产 target",
 "生产0/测试4/文档2/登记1（编译者 p3_projection_registry_test / v6_p3_export_test / v6_p3_proj_probe / v6_p3_proj_test；本文件 :1 起有合规的 RETIRED-CODE-RETAINED 块）",
 "是——ENG/tests/unit/v6_p3_proj/sin_roundtrip_gate.py **编译真实内核**并做「偏差是否仍复现」的判定（其文件头 :6-13 明写：偏差消失⇒rc 1 红，必须同步 p3_proj_v6.h/.cpp 的 RETIRED 已知缺陷段与 p3_projection_registry.h 的已知偏差登记）",
 "不许删：它是 RETIRED-CODE-RETAINED 合规保留件（六 token 齐备，本审查独立复核通过）且被复现门钉住。若内核被修好，走该门声明的三步同步再删",
 "eng/tests/unit/v6_p3_proj/sin_roundtrip_gate.py；lib/algorithms/projection/p3_projection_registry.h 的「已知偏差登记（FIX-406）」段；run/FIX-406/SIN_ROUNDTRIP_ORACLE.md（未跟踪产物指针）",
 "高（改对反而判红的最强例）：把 SIN 内核**修好**会让 sin_roundtrip_gate 由绿转红——该门设计上就是「修好即红」以强制同步文档。这不是缺陷，但开发节点必须知道红是预期动作",
 "高"],

["lib/algorithms/projection/p3_projection.h 的 RETIRED 登记（与 p3_proj_v6.h 配对）",
 "退役未清理",
 "不在生产 target",
 "生产1/测试0/文档0/登记0（复核：本审查的注释块普查在 p3_proj_v6.h 命中 1 个 RETIRED-CODE-RETAINED 块）",
 "否——头文件不入任何源清单，但 p3_proj_v6.h 的块被 sin_roundtrip_gate 的同步清单点名",
 "加统一退役标注（已有，保持）：不得因「看着像退役」就删头——RETAINED 块是 ENGINEERING_SPEC §2 的第二种合法状态",
 "无",
 "低",
 "高"],

["lib/algorithms/noise_snr/cpp/src/snr_estimator.cpp",
 "占位模块",
 "不在生产 target",
 "生产1/测试2/文档1/登记0（编译者 p1noise_tests（lib/algorithms/noise_snr/tests/p1noise/CMakeLists.txt:133）与 p1psf（lib/algorithms/psf/tests/p1psf/CMakeLists.txt:172）；同目录 snr_science.cpp 在产 ⇒ 同域两实现并存）",
 "部分——两个实验 target 直接列源编译；未查到以本文件为输入的门",
 "先解引用再删：与 snr_science.cpp 构成「同一能力两份实现」（标准 04 §3），须先定保留哪一份，另一份按 §4 二选一处置",
 "lib/algorithms/noise_snr/tests/p1noise/CMakeLists.txt:133；lib/algorithms/psf/tests/p1psf/CMakeLists.txt:172；docs/modules/snr_estimator.md（以本文件为实现锚）",
 "高：两份实现都被实验编译，删错一份 ⇒ 绝对 SNR 传递链（SCI-B）的实验单元失去载体，而实验单元是验收核心证据",
 "中——哪一份是权威实现须按 docs/science/ 判定，本审查未裁"],

["lib/infrastructure/scheduler/src/executor.cpp",
 "重复实现",
 "不在生产 target",
 "生产1/测试1/文档1/登记1（按 CMake 源清单只有 executor_provider_race_test（eng/tests/unit/CMakeLists.txt:242）；但生产经**文本 include** 获得：lib/infrastructure/scheduler/src/module_adapters.cpp:255 `#include 「executor.cpp」`）",
 "是——四重承载：(1) eng/tests/unit/CMakeLists.txt:1481 注释显式禁止把本文件与 astrocs_module_adapters 编入同一二进制（重定义⇒链接期显式失败）；(2) finding F-RT-001-04 登记于该注释；(3) lib/include/astrocs/core/executor.h:22 声明「本头为 RT-004 冻结合同；实现见 …」；(4) 文本 include 本身",
 "不许删，且四档定位须按「经文本 include 进生产二进制」记录：本条不是死代码，是**编译归属错位**。整改=归位：根 CMakeLists 为 astrocs_module_adapters 追加本 TU 并删除 :255 的 include（该注释本身写明了这个整改方向）",
 "lib/infrastructure/scheduler/src/module_adapters.cpp:250-256；eng/tests/unit/CMakeLists.txt:1481；lib/include/astrocs/core/executor.h:22；RT-004 合同条款",
 "高：按「仅测试 target 编译」字面理解去删本文件 ⇒ 生产 astrocs_module_adapters 直接失去 executor 实现，链接失败；这是全清单里最容易被误判成死代码的一条",
 "高"],

["lib/phase3_session/p3_v6_export.cpp",
 "占位模块",
 "不在生产 target",
 "生产0/测试1/文档1/登记0（唯一编译者 v6_p3_export_test，eng/tests/integration/v6_p3/CMakeLists.txt:34；不在 astrocs_phase3_session 源清单——根 CMakeLists.txt:933-943 只列 p3_session.cpp）",
 "是——本文件与其头各有 1 个**合规** RETIRED-CODE-RETAINED 块（本审查普查：六 token 齐备）⇒ 它是 ENGINEERING_SPEC §2 第二种合法状态下的保留件，同时被 v6_p3_export_test 编译",
 "不许删（保留并说明理由）：已按规范标注退役原因与去向；删除须等其 EXIT 条件成立",
 "若将来删：连同 v6_p3_export_test 与 p3_v6_export.h 的块同批",
 "中：它的「不在生产 target」是**已登记的有意保留**，不是缺陷；与其它 TEST-only 条目处置方向相反，必须区分",
 "高"],

["lib/phase1_session/p1_session.cpp",
 "占位模块",
 "在生产调用面零引用",
 "生产1/测试2/文档4/登记0（在 astrocs_phase1_session STATIC 库源清单：根 CMakeLists.txt:913，并出现在 :1012 与 :1070 的链接面 ⇒ **已编入 acsd**）",
 "部分——无门以其文件名为输入；但 README/memory/module.yaml 三面声明「P1Api 保留仅作兼容面（当前无工厂委托）」",
 "先解引用再删：它编译进产品却无调用者。P1Api 在全仓代码面只有 1 个命中=其自身定义（git grep -nw P1Api -- lib eng => module_adapters.cpp:1193），即会话的 C ABI 包装无人构造 ⇒ 主动作是**删注册面**（见 AUD-404 行 71-72），不是接线",
 "lib/infrastructure/scheduler/src/module_adapters.cpp:1193-1216（P1Api 包装 struct）；lib/phase1_session/{README.md,memory.md,module.yaml}；标准 04 §1:20（会话目录归并后应退役）",
 "中：ASTROCS_DESIGN §8.4 与标准 04 §1 对同一目录给**相反**要求（前者要求保留 lib/phase{1,2,3}_session 目录，后者要求归并后退役），冲突已登记上呈；在该裁决落地前删目录会违背其中一份权威",
 "中——权威打架，未裁"],

["lib/phase2_session/p2_session.cpp",
 "占位模块",
 "在生产调用面零引用",
 "生产1/测试2/文档6/登记3（根 CMakeLists.txt:925 建 astrocs_phase2_session 并 :1012/:1070 链接进 acsd）",
 "是——被 astrocs.phase2.resample 的工厂注册挂载（git grep -nE 「astrocs\\.phase2\\.resample([^2]|$)」 => 45 行 27 文件；其中 eng/tests/unit/rt005_registry_test.cpp:33 CHECK(reg.has_factory(「astrocs.phase2.resample」)) 正向断言注册必须存在）",
 "先解引用再删：删本文件前必须先解除注册并撤掉 rt005 对该 has_factory 的断言（见行 71-72、74）",
 "eng/tests/unit/rt005_registry_test.cpp:33,37,140；eng/contracts/block_flow/conformance_deviations.json:36,41；eng/ci/ledgers/registry_ir_parity.json；docs/modules/registry/astrocs.phase2.resample.md",
 "高（改对反而判红）：仓库自家台账 registry_ir_parity.json 记其「永不被调度」，看起来可直删；实际 rt005 正向断言工厂存在 ⇒ 直删注册即判红",
 "高"],

["lib/phase3_session/p3_session.cpp",
 "占位模块",
 "在生产调用面零引用",
 "生产1/测试3/文档6/登记3（根 CMakeLists.txt:933-943 建 astrocs_phase3_session；:650 另记 astrocs_p3_rsmp ⇄ astrocs_phase3_session 链接环的处置）",
 "是——被 astrocs.phase3.resample 工厂注册挂载（精确计数：git grep -nE 「astrocs\\.phase3\\.resample([^2]|$)」 => 46 行 26 文件；注意 **substring 陷阱**：朴素 -F 匹配得 110 行 43 文件，其中含真模块 astrocs.phase3.resample2 / 权威 ID astrocs.p3.resample）",
 "先解引用再删：同 p2；且必须先确认哪些命中属于 resample2（真在产模块）**不许动**",
 "eng/tests/unit/rt005_registry_test.cpp；eng/tests/runtime/test_rt005_plan_estimator.py；eng/tests/unit/core_pipeline_test.cpp 与 fixtures/core_pipeline/{valid_pipeline,invalid_pipeline_serial_heavy}.json；lib/infrastructure/scheduler/src/plan_estimator.cpp；docs/modules/registry/module_id_migration_baseline.json",
 "高（双重）：(1) rt005 正向断言；(2) ID 与真模块 resample2 只差一个字符，用 -F 批量替换会**连真在产模块一起改掉**，直接破坏 P3 重采样生产面",
 "高"],

["lib/infrastructure/scheduler/src/module_adapters.cpp:711-729（phase2_descriptor 占位体）",
 "模板复制残留",
 "在生产调用面零引用",
 "生产3/测试3/文档5/登记4（同 astrocs.phase2.resample 精确 45 行的分布；代码面命中 module_adapters.h ＋ module_adapters.cpp ＋ lib/phase2_session/README.md）",
 "是——descriptor 的 module_id 被写成 astrocs.phase2.resample（与真 resample 模块抢名），其 ports 用 DATA-P1-CAL/DATA-P2-RES，携带的 SCI/DATA 锚（如 SCI-P2-RES-001）与实际执行语义（coverage→sampler→UPM→persist）不符",
 "先解引用再删：标准 04 §3 要求「模块端口由注册表单一来源声明，代码注册与注册表一致」——本 descriptor 与 module_ports.registry.json **不一致**（该 JSON 只有 astrocs.phase3.resample2，无 phase2.resample）⇒ 整改方向是删占位 descriptor，而非把它补进注册表",
 "行 71-75 与 AUD-404 行 16-25 的整批文档面；eng/contracts/block_flow/conformance_deviations.json:36,41",
 "高：这是「注册了但不在管线」的根因件；但被 rt005 与 conformance_deviations 双重承载 ⇒ 不能直删",
 "高"],

["lib/infrastructure/scheduler/src/module_adapters.cpp:730-760（phase3_descriptor 占位体）",
 "模板复制残留",
 "在生产调用面零引用",
 "生产3/测试3/文档5/登记4（astrocs.phase3.resample 精确 46 行分布）",
 "是——同上，且其 ID 与**在产真模块** astrocs.phase3.resample2／权威 astrocs.p3.resample 形成人眼易混对",
 "先解引用再删（与 :711-729 同批）",
 "docs/modules/registry/{astrocs.phase3.resample.md, astrocs.phase3.resample2.md, module_id_migration_baseline.json}；eng/tools/quality/check_block_flow_ports_vs_code.py",
 "高（改对反而判红）：删本占位体后 astrocs.phase3.resample.md 这张**生成页**失去来源（页首 GENERATED-ANCHOR tool=eng/tools/quality/gen_module_readmes.py）⇒ 必须重跑生成器而非手删页面，否则 CHK-REGISTRY-DOC-SYNC 判文档与注册表不一致",
 "高"],

["lib/infrastructure/scheduler/src/module_adapters.cpp:15443-15456（两个占位 descriptor 的 register_module + register_factory）",
 "模板复制残留",
 "在生产调用面零引用",
 "生产2/测试3/文档3/登记4（工厂 make_session_module<P2Api> / <P3Api>，注册进生产 registry）",
 "是——CHK-REGISTRY-IR-PARITY 的判据对象（ID 出处 eng/ci/checks.json，command=eng/ci/check_registry_ir_parity.py）；其台账 eng/ci/ledgers/registry_ir_parity.json:7 的 exit_condition 逐字写「从 register_phase_modules 移除 astrocs.phase2.resample…」⇒ **仓库自己规定了删除动作**",
 "先解引用再删：删除顺序=①撤 rt005 的 has_factory 断言 ②解除 conformance_deviations.json 两条 ③把 registry_ir_parity.json 两条置空/转「已解除」 ④删 :15443-15456 与两个 descriptor ⑤重跑 gen_module_readmes.py 更新两张生成页",
 "见上五行的连带面；另 eng/tools/quality/gen_run_graphs.py:248,261 与 eng/tests/unit/rt006_scheduler_test.cpp:185、rt007_artifact_store_test.cpp:59 把该 ID 当「示例节点」用，须改成真模块 ID",
 "高：顺序错一步就红；尤其 rt005/rt006/rt007 与两个 typed_dag 负例测试**同时**引用该 ID（负例测试用它作「禁止出现在计划里」的样本，删掉会让负例失去样本而恒绿=门退化）",
 "高"],

["lib/infrastructure/scheduler/src/module_adapters.cpp:1193-1216（P1Api/P2Api/P3Api 三个 C ABI 包装 struct）",
 "模板复制残留",
 "在生产调用面零引用",
 "生产1(P1Api 仅 :1193 自身定义)/测试1/文档8/登记0（复核：git grep -nw -e P1Api -- lib eng => lib 仅 1 行；P3Api 在 lib 5 行均在 module_adapters.cpp 内自引用）",
 "否——无门以这三名为输入；但 lib/phase1_session/module.yaml:17 注释自陈「P1Api 保留仅作兼容面（当前无工厂委托）」⇒ 兼容面主张与「P1Api 无任何工厂使用」是矛盾的",
 "删除（P1Api）／先解引用再删（P2Api、P3Api，随 :15443-15456 注册解除同批）",
 "lib/phase1_session/{README.md:16,30-31,memory.md:34,99,module.yaml:17} 的「兼容面」叙述须同步（这些正是标准 04 §5 禁止的「已撤销设计的历史叙述」）",
 "中：P1Api 删除不红；但 README 的「保留为兼容面」若无对应代码 ⇒ 从「代码死」变成「文档谎」",
 "高"],

["eng/ci/ledgers/registry_ir_parity.json:entries（2 条 registered_not_in_ir）",
 "登记面残留",
 "在生产调用面零引用",
 "生产0/测试2/文档2/登记1（本台账两条 ID 即 astrocs.phase{2,3}.resample；reason 字段自述「永不被调度/注册了但不在管线」）",
 "是——本文件是 CHK-REGISTRY-IR-PARITY 的棘轮台账（ID 出处 eng/ci/checks.json）；该脚本 :555 的 --self-test 夹具里也硬编码同形条目",
 "改注册：台账本身不是死代码，它是**唯一登记「注册未接线」这一事实**的载体；解除顺序见上一行第③步，不可先删台账（先删 ⇒ 门立即判红而非「已解决」）",
 "docs/KNOWN_LIMITATIONS.md:154（对外以本台账为凭据）；artifacts/evidence/known-limitations-ledger/LEDGER.md:172；ENGINEERING_SPEC §4「不隐藏整阶段 Session」违例条目",
 "高：本台账是「已知限制」的**唯一来源**之一 ⇒ 属于 .md 里「不许删」那组的典型：它是限制陈述的载体，不是残留",
 "高"],

["docs/modules/registry/astrocs.phase2.resample.md 与 astrocs.phase3.resample.md（两张模块登记页）",
 "登记面残留",
 "在生产调用面零引用",
 "生产0/测试0/文档4/登记3（前者 :13 标题即该 ID，:38 声明 module_id；后者页首有 GENERATED-ANCHOR tool=eng/tools/quality/gen_module_readmes.py tool-sha256=4fb971ad…，status: NOT_VERIFIED）",
 "是——CHK-REGISTRY-DOC-SYNC / REGISTRY-DOC-SYNC（ID 出处 eng/ci/checks.json，command=eng/ci/check_registry_doc_sync.py）核 docs/modules/registry/* 与注册表一致性；另 eng/tools/doccheck/doc_hygiene_exempt.json:202,209 已为 astrocs.phase2.resample.md 开了文档卫生豁免",
 "不许手删：改注册——解除代码侧注册后由 gen_module_readmes.py 重新生成；astrocs.phase2.resample.md **没有** GENERATED-ANCHOR（即它是手工页，生成器不覆盖它），删它须同步 doc_hygiene_exempt.json 的豁免条目与 DOCUMENT_INDEX.yaml:953",
 "docs/DOCUMENT_INDEX.yaml:953；eng/tools/doccheck/doc_hygiene_exempt.json 两条；docs/traceability/TRACEABILITY_MATRIX.{csv,json} 的 MOD-astrocs-phase2-resample 行；docs/contracts/unified_object_registry.json:216 与 eng/contracts/data/unified_object_compatibility_map_v1.json:168 的「页面:行号」锚",
 "高：两张页被**合同**当作对象归属锚引用（unified_object_registry / compatibility_map 直接指到 astrocs.phase2.resample.md:22 这一行）⇒ 删页或改行号会让合同锚解析失败判红",
 "高"],

["eng/contracts/block_flow/conformance_deviations.json:36-41（把 astrocs.phase2.resample 登记为「代码额外注册」的合规偏差）",
 "登记面残留",
 "在生产调用面零引用",
 "生产0/测试2/文档1/登记2（该 JSON 以 「contains」: 「astrocs.phase2.resample」 作为**存在性断言**）",
 "是——这是**合同层**文件（eng/contracts/ 是机器校验的合同唯一事实源）；它把「代码注册了 IR 里没有的模块」写进偏差登记，并以 contains 要求该字符串存在于代码面",
 "改注册：解除代码注册时**必须同批**删本偏差条目；本条是偏差合同的载体，不是残留——单独删它等于隐瞒偏差，单独留它等于要求代码里继续存在错误注册",
 "eng/ci/ledgers/registry_ir_parity.json 两条；lib/infrastructure/scheduler/src/module_adapters.cpp:15443-15456；docs/KNOWN_LIMITATIONS.md:154",
 "高（双向陷阱）：contains 是**正向**存在断言 ⇒ 只改代码不改合同 ⇒ 合同门判红；只删合同不改代码 ⇒ 偏差被静默抹掉、门全绿而问题还在。两条都「看起来对」，必须同批",
 "高"],
]
