$ErrorActionPreference="Stop"
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250702@061703-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250702@062109-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250702@062457-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250702@062844-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250702@063231-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250703@051551-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250703@051958-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250703@052346-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250703@052735-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250703@053123-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel1/Galaxy_Center_mosaic1_T4_flying_dutchman-20250813@011752-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250716@002647-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250716@003055-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250716@003443-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250716@003831-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250716@004219-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250717@031324-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250717@031717-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250717@032221-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250717@032620-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250717@033543-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel2/Galaxy_Center_mosaic2_T4_flying_dutchman-20250717@033941-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@001638-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@002045-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@002432-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@002821-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@003210-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@003556-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@003945-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@004333-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@004720-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/Galaxy_Center_T4/lights/panel3/Galaxy_Center_mosaic3_T4_flying_dutchman-20250718@005108-180S-Red.fts'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/T4 calibration files/masterBias_BIN-1_4500x3600.xisf'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/T4 calibration files/masterDark_BIN-1_4500x3600_EXPOSURE-180.00s.xisf'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
$p='F:/Astro dev/Astro CS Normalization Database/testdata/T4 calibration files/masterFlat_BIN-1_4500x3600_FILTER-Red_mono.xisf'
try { $h=Get-FileHash -Algorithm SHA256 -LiteralPath $p; Write-Output ("P|" + $p + "|" + (Get-Item -LiteralPath $p).Length + "|" + $h.Hash) } catch { Write-Output ("E|" + $p + "|" + $_.Exception.Message) }
Write-Output "DONE"
