# 生成: tools/gen_cfitsio_list.py (BLD-001 禁止 production GLOB)
set(ASTROCS_CFITSIO_SOURCES
  lib/astro_image_io/third_party/cfitsio/buffers.c
  lib/astro_image_io/third_party/cfitsio/cfileio.c
  lib/astro_image_io/third_party/cfitsio/checksum.c
  lib/astro_image_io/third_party/cfitsio/drvrfile.c
  lib/astro_image_io/third_party/cfitsio/drvrmem.c
  lib/astro_image_io/third_party/cfitsio/drvrnet.c
  lib/astro_image_io/third_party/cfitsio/editcol.c
  lib/astro_image_io/third_party/cfitsio/edithdu.c
  lib/astro_image_io/third_party/cfitsio/eval_f.c
  lib/astro_image_io/third_party/cfitsio/eval_l.c
  lib/astro_image_io/third_party/cfitsio/eval_y.c
  lib/astro_image_io/third_party/cfitsio/fits_hcompress.c
  lib/astro_image_io/third_party/cfitsio/fits_hdecompress.c
  lib/astro_image_io/third_party/cfitsio/fitscore.c
  lib/astro_image_io/third_party/cfitsio/getcol.c
  lib/astro_image_io/third_party/cfitsio/getcolb.c
  lib/astro_image_io/third_party/cfitsio/getcold.c
  lib/astro_image_io/third_party/cfitsio/getcole.c
  lib/astro_image_io/third_party/cfitsio/getcoli.c
  lib/astro_image_io/third_party/cfitsio/getcolj.c
  lib/astro_image_io/third_party/cfitsio/getcolk.c
  lib/astro_image_io/third_party/cfitsio/getcoll.c
  lib/astro_image_io/third_party/cfitsio/getcols.c
  lib/astro_image_io/third_party/cfitsio/getcolsb.c
  lib/astro_image_io/third_party/cfitsio/getcolui.c
  lib/astro_image_io/third_party/cfitsio/getcoluj.c
  lib/astro_image_io/third_party/cfitsio/getcoluk.c
  lib/astro_image_io/third_party/cfitsio/getkey.c
  lib/astro_image_io/third_party/cfitsio/group.c
  lib/astro_image_io/third_party/cfitsio/grparser.c
  lib/astro_image_io/third_party/cfitsio/histo.c
  lib/astro_image_io/third_party/cfitsio/imcompress.c
  lib/astro_image_io/third_party/cfitsio/iraffits.c
  lib/astro_image_io/third_party/cfitsio/modkey.c
  lib/astro_image_io/third_party/cfitsio/pliocomp.c
  lib/astro_image_io/third_party/cfitsio/putcol.c
  lib/astro_image_io/third_party/cfitsio/putcolb.c
  lib/astro_image_io/third_party/cfitsio/putcold.c
  lib/astro_image_io/third_party/cfitsio/putcole.c
  lib/astro_image_io/third_party/cfitsio/putcoli.c
  lib/astro_image_io/third_party/cfitsio/putcolj.c
  lib/astro_image_io/third_party/cfitsio/putcolk.c
  lib/astro_image_io/third_party/cfitsio/putcoll.c
  lib/astro_image_io/third_party/cfitsio/putcols.c
  lib/astro_image_io/third_party/cfitsio/putcolsb.c
  lib/astro_image_io/third_party/cfitsio/putcolu.c
  lib/astro_image_io/third_party/cfitsio/putcolui.c
  lib/astro_image_io/third_party/cfitsio/putcoluj.c
  lib/astro_image_io/third_party/cfitsio/putcoluk.c
  lib/astro_image_io/third_party/cfitsio/putkey.c
  lib/astro_image_io/third_party/cfitsio/quantize.c
  lib/astro_image_io/third_party/cfitsio/region.c
  lib/astro_image_io/third_party/cfitsio/ricecomp.c
  lib/astro_image_io/third_party/cfitsio/scalnull.c
  lib/astro_image_io/third_party/cfitsio/simplerng.c
  lib/astro_image_io/third_party/cfitsio/swapproc.c
  lib/astro_image_io/third_party/cfitsio/wcssub.c
  lib/astro_image_io/third_party/cfitsio/wcsutil.c
  lib/astro_image_io/third_party/cfitsio/zcompress.c
  lib/astro_image_io/third_party/cfitsio/zuncompress.c
)
