import json
reg=json.load(open('ci/checks.json',encoding='utf-8'))['checks']
SELF=('PRODUCTION-GRAPH','ISA-LEAK-SELFTEST','SERIAL-HEAVY-SELFTEST','PROD-REACH-SELFTEST','LOG-CONTRACT-SELFCHECK','CTEST-REGISTRATION','CTEST-PHASE2-GATES','CONTRACT-GRAPH','DATA-ARTIFACTS','P3-STATUS','DUPLICATION','UNIT-CLOSURE','API-DOCS','CON-COMMENTS','TRACEABILITY','TRACEABILITY-CODE','AGENTS-GOV','WORKFLOW-REGISTRY-BINDING','NO-SERIAL-HEAVY','ABI-BOUNDARY','AIO-OWNERSHIP','CLI-COMMAND-LAYER','CLI-RUN-PRESET','ACR-DORMANT','DOC-L0','GLOSSARY-DOCS','MODULE-READMES','PIPELINE-TRACE','SERIAL-HARDCODE','WARNING-SUPPRESSION','THREAD-BUDGET','AST-API','TASK-RESULT-SCHEMA','DOC-INDEX','VERSION-NAMESPACES','ENG-CONSTRAINTS','TOOLCHAIN-VERIFY','CON-API-CONTRACTS','CON-BUILD-GRAPH','CON-CONFIG-CONTRACTS','CON-DOC-SYMBOLS','CON-EXECUTION-CONTRACTS','CON-FORBIDDEN-PATTERNS','CON-FULL-INTEGRATION','CON-SCIENCE-UNITS','CON-TEST-CONTRACTS','CON-TRACEABILITY','TRACEABILITY-MATRIX','TESTKIT-LIST','WORKSPACE-ADOPTION','RECONCILE-STATE')
for c in reg:
    if c['id'] in SELF:
        print('%-30s %s' % (c['id'], ' '.join(map(str,c['command']))))
